### ISSUE TITLE
mCastSession null 

### ISSUE THREAD

**Issue by danielgssp** [react-native-google-cast/react-native-google-cast#100]
I tryed use methods `initChannel()`, `sendMessage()` and `getCastDevice` but 
I didn't got succeed because my `mCastSession `is always null, why ? 

Apparently when `onApplicationConnected()`  is called  he set value to `CastSession` but `CastSession `is lost whenever I update my application because the constructor of the `GoogleCastModule()` is called and create a new instance of `mCastSession` become null value! 

**try steps**
start connection  //get `CastSession `he's have value !
reload my app   // lost `CastSession`, he's back null
and `sendMessage()` // fail to send because he is null

**Comment by danielgssp** [comment]
When call `setCastSession() `he set `mCastSession` with a value... 
but on `initChannel()` or other methods `mCastSession `is null =)

**Comment by petrbela** [comment]
Hmm this sounds legit, I'll look into it...
