### ISSUE TITLE
Cast button touch event handler

### ISSUE THREAD

**Issue by andy-io** [react-native-google-cast/react-native-google-cast#101]
Hi,

I want to trigger the cast button dialog when user tries to cast a video to tv without connecting to the device earlier. How can this be achieved?

**Comment by petrbela** [comment]
Hmm that's a good question. I'm pretty sure this is not supported by the library at the moment, and quite unsure how to do it in the native code (don't have time to investigate now). If you find a solution, can you please post it here? PRs are also welcome.

**Comment by rangav** [comment]
See the project for reference click handler implemented 
https://github.com/mtkopone/react-native-googlecast-v3
