### ISSUE TITLE
Captions Support

### ISSUE THREAD

**Issue by hitaloramon** [react-native-google-cast/react-native-google-cast#102]
Is it possible to send captions in vtt or srt?

Doc: https://developers.google.com/cast/docs/android_sender/media_tracks

**Comment by petrbela** [comment]
Hi! This will be available in [v4](https://github.com/react-native-google-cast/react-native-google-cast/tree/v4). You can try it out now but it's still very unstable.

**Comment by hitaloramon** [comment]
@petrbela I tried to look for an example of how to use external subtitles and not find, could how to send?

**Comment by petrbela** [comment]
I'll be doing a big push of v4 over the weekend, including docs and finalized APIs, so hopefully, it's not too late for you.

**Comment by hitaloramon** [comment]
@petrbela perfect, I was trying to understand how v4 works, but I'll wait for the doc! Awaiting!

**Comment by hitaloramon** [comment]
@petrbela When will the documentation be available? Any progress?

**Comment by brooklyn097** [comment]
Hi, Any updates here? I would be really appreciate if you can provide a quick doc about Closed Caption @petrbela .Thank you!

**Comment by skantus** [comment]
Hi everyone I give support for `MediaTracks` only for "iOS" in this PR: https://github.com/react-native-google-cast/react-native-google-cast/pull/164 🚀 

If you want to use my repo until the PR is merged feel free to do so:

https://github.com/skantus/react-native-google-cast/releases/tag/v3.2.4

***Note:*** This version only works in Xcode 10.3 or earlier since the new version has security limitations for Xcode 11, check it out:

https://developers.google.com/cast/docs/ios_sender

cc/: @petrbela

**Comment by petrbela** [comment]
@skantus Thanks for the PR. I wonder what security limitations you're referring to. The library works on iOS 13 (just doesn't support Bluetooth Guest Mode currently), and your PR doesn't affect security.

For everyone else, I'm planning to finish v4 this Christmas. It includes, among others, a full API for setting media tracks and styling them. For a preview see the v4 branch.

**Comment by skantus** [comment]
@petrbela I'm having troubles compiling v4 in Xcode 11 any tricks to solve it?

**Comment by petrbela** [comment]
@skantus You'll probably need to use the NoBluetooth version. See https://github.com/react-native-google-cast/react-native-google-cast#installation

**Comment by nriccar** [comment]
Is there anyway of setting an offset in terms of time for subtitles?

**Comment by petrbela** [comment]
@nriccar I don't think that's supported. You'll need to adjust the times in the subtitles file.

**Comment by nriccar** [comment]
Any chance is doable on the custom receiver side? For some reason the VTT file is not in sync with the video. Im extracting the url of the VTT on the manifest, maybe I should add the subtitle manually but expecting the mediaInfo contentUrl to grab the subtitles from its own manifest alone?
