### ISSUE TITLE
How to get List of Chromecast devices without CastButton

### ISSUE THREAD

**Issue by rangav** [react-native-google-cast/react-native-google-cast#103]
How to get List of Chromecast devices in Android without CastButton, as i am developing custom UI functionality.

on iOS i can get it using GCKDiscoveryManager

**Comment by petrbela** [comment]
Hi! This is not available in the current version of this library. I'm not sure Android even supports manual discovery anymore. You'll probably find a better answer at Android / Google Cast forums. If you manage to find a solution, please post back here.

**Comment by rangav** [comment]
Looks like we need to use MediaRouter and OnRouteAdded event. see [#stackoverflow](https://stackoverflow.com/questions/40040689/chromecast-how-to-select-a-castdevice-without-a-castbutton)

**Comment by petrbela** [comment]
Yes, that's how you used to do it in v2. I'm not sure if it works anymore, or if it's officially supported. As mentioned in the SO comment, you should follow Google's design guidelines and the say to use the native button. However, they're guidelines, not strict requirements, so do whatever you want, but you've been warned ;)
