### ISSUE TITLE
[iOS] It don't is working.

### ISSUE THREAD

**Issue by igor-nm** [react-native-google-cast/react-native-google-cast#104]
Hello there!!

I followed the all steps from documentation but it don't working on iOS.
On android it worked normally.

Kind of steps: `CocoaPods`
Google sdk version: `~> 3`

I tried to use the sdk `~> 4.3` but a error happened, after that I followed al steps correctly.
I would like remember that `npm install` and `pod install` builded without errors.

Podfile:
```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'googlecast' do
  # Path from node_modules
  node_modules = "../node_modules"

  # Path from react-native
  react_native = "#{node_modules}/react-native"

  # React deps podspec link
  pod 'React', :path => react_native, :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
  ]

  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => "#{react_native}/ReactCommon/yoga"

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => "#{react_native}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{react_native}/third-party-podspecs/glog.podspec"
  pod 'Folly', :podspec => "#{react_native}/third-party-podspecs/Folly.podspec"

  # Google cast deps podspec link
  pod 'google-cast-sdk', '~> 3'
  pod 'react-native-google-cast', path: "#{node_modules}/react-native-google-cast/ios/"
end
```
AppDelegate.m :
```
  static NSString *const kReceiverAppID = @"RECEIVER_ID";
  GCKCastOptions *options = [[GCKCastOptions alloc] initWithReceiverApplicationID:kReceiverAppID];
  options.physicalVolumeButtonsWillControlDeviceVolume = YES;
  [GCKCastContext setSharedInstanceWithOptions:options];
```
And i imported `#import <GoogleCast/GoogleCast.h>`

App.js:
```
import React, {Component}         from 'react';
import {StyleSheet, Text, View}   from 'react-native';
import GoogleCast, { CastButton } from 'react-native-google-cast'

export default class App extends Component {
  componentDidMount () 
  {
    GoogleCast.getCastState().then(state => console.warn(state));
    GoogleCast.getCastDevice().then(device => console.warn(device));
		GoogleCast.EventEmitter.addListener(GoogleCast.SESSION_STARTED, () =>  console.log("Started"));
  };

  render() {
    return (
      <View style={styles.container}>
        <View style={{width: 42, height: 42, backgroundColor: "#F0000081"}}>
    	    <CastButton style={{width: 36, height: 36, tintColor: 'black'}} />
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: 
  {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  }
});
```

Erros on screen:
![UNADJUSTEDNONRAW_thumb_11](https://user-images.githubusercontent.com/20232832/55239078-b326d180-5214-11e9-915e-ca2ba6cc3153.jpg)

Please guys, I need your help because I don't know where I committed the mistakes.

**Comment by petrbela** [comment]
Hi Igor,

The code seems okay. The warnings you get on screen are not errors. The first two are from 

```js
GoogleCast.getCastState().then(state => console.warn(state));
GoogleCast.getCastDevice().then(device => console.warn(device));
```

because no device is connected yet. The third warning about main queue setup is a future deprecation warning (which will be fixed in a later version) but doesn't affect the current functionality in any way.

The way casting works: you first need to render the CastButton and only continue after the user presses the button and selects a device to connect to. Only after a device is connected can you cast content.

The problem seems to be that the CastButton is not displayed. The framework automatically displays the button only if there is at least on Cast device available. Please make sure your Chromecast is turned on and connected to the network. Also, enable [Access WiFi Information](https://developers.google.com/cast/docs/ios_sender/#xcode_10).

**Comment by igor-nm** [comment]
Ok dude, I enabled the Access WiFi Information how link showed me.
The problem about CastButton still don't render, like the button really don't appear.
Do I need to do anything for appear CastButton to connect ?

Apologize by my confusion :/

**Comment by petrbela** [comment]
Do you use a custom app id (from https://cast.google.com/publish/)? If yes, is it published? If no, is your Chromecast device listed as a development device? Make sure you restart it afterward.

Does the Xcode debug console show any error?

**Comment by igor-nm** [comment]
Do you use a custom app id (from https://cast.google.com/publish/)? Yes, it is.
If yes, is it published? Yes, it is.
If no, is your Chromecast device listed as a development device? Yes, it is.
Make sure you restart it afterward.

Does the Xcode debug console show any error? No, none errors.

I don't get what is happening. No makes sense CastButton don't appear :/

**Comment by alfiedouglas0** [comment]
I had this exact issue, but it was because I hadn't restarted my chromecast since registering my chromecast as a receiver device on https://cast.google.com/publish/, hope this helps!

**Comment by igor-nm** [comment]
I'm closing this issue because this is fixed in the new version, it's working now.
