### ISSUE TITLE
amazon fire tv fling sdk integration

### ISSUE THREAD

**Issue by andy-io** [react-native-google-cast/react-native-google-cast#105]
https://developer.amazon.com/docs/fling/integrating-amazon-fling-with-cast.html

i see that it is possible to integrate amazon fling sdk in the same way as google cast. Could you please add support for it as well ?

**Comment by petrbela** [comment]
Hi! That's a really interesting question. Despite what the article you linked might suggest, fundamentally, Fling and Cast are two independent frameworks with very different code bases, so the most straightforward thing to do would be to create a separate RN library.
