### ISSUE TITLE
[v4] When will be launched?

### ISSUE THREAD

**Issue by talesporto** [react-native-google-cast/react-native-google-cast#106]
Hi, 

I'm building an application that need cast to chrome cast.
I use the v3 of this library and works fine.

But I need to send the tracks to chrome cast too. v3 do not handle tracks. v4 is handling it.

When it will be lauch?
And what is not working yet?

**Comment by petrbela** [comment]
Hi! V4 should be working for the main use cases but I haven't done any extensive testing. I also haven't finalized the APIs which is why I don't want to make it official yet. I'm hoping to get it all finished one of the upcoming weekends.

**Comment by talesporto** [comment]
Ok.
Let me know if I can help you with that.

Thanks by the fast answer and thanks for your time working on this library.

**Comment by lindborg** [comment]
Is there any changes to the install process when using v4? I tried just downloading and overriding the v3 folder adding the xcode project and lib to my project afterwards, but I get these errors: 

`Build input file cannot be found: '/Users/**/node_modules/react-native-google-cast/ios/api/RNGCRemoteMediaClient.m'
Build input file cannot be found: '/Users/**/node_modules/react-native-google-cast/ios/RNGoogleCast/RNGoogleCastButtonManager.m'
Build input file cannot be found: '/Users/**/node_modules/react-native-google-cast/ios/components/RNGoogleCastButtonManager.m'`

**Comment by petrbela** [comment]
Hmm I'm testing with CocoaPods, let me check if there might be an issue with using it from Libraries.

**Comment by lindborg** [comment]
What do you write in your podfile to get the v4 branch? (I'm not that familiar with CocoaPods). I can't seam to deduct the answer from your repo example.

**Comment by lindborg** [comment]
Found the solution. No need to investigate.

**Comment by WeeJeWel** [comment]
+1, also getting 👍 
```
Build input file cannot be found: '<...>/node_modules/react-native-google-cast/ios/RNGoogleCast/RNGoogleCastButtonManager.m'
```

**Comment by talesporto** [comment]
+1

**Comment by gleidsonp** [comment]
Hi! getting on 'pod install' on #v4:

`[!] Invalid Podfile file: [!] No podspec exists at path node_modules/react-native-google-cast/ios/react-native-google-cast.podspec.`
` >    use_native_modules!`

**Comment by petrbela** [comment]
v4 now available in beta. https://react-native-google-cast.github.io/docs/getting-started/installation
