### ISSUE TITLE
Failed to initialize CastContext

### ISSUE THREAD

**Issue by Rafazeon** [react-native-google-cast/react-native-google-cast#107]
Hello I followed the steps of how to install the library on android but I am having this error, how can I solve this in the android folder, Thanks.

**Comment by petrbela** [comment]
Can you provide more information, like source code, when does this error happen, full stack trace etc?

**Comment by Rafazeon** [comment]
I have the following problem now, I installed the library, I made the react native link and when running the project it appears
Can not read propety play of undefined,
In Loadmoduleimplementation.

My MainActivity:
package com.academia;

import android.content.Intent;
import com.facebook.react.ReactActivity;
import com.facebook.react.GoogleCastActivity;

public class MainActivity extends GoogleCastActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "academia";
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
    super.onActivityResult(requestCode, resultCode, data);
        MainApplication.getCallbackManager().onActivityResult(requestCode, resultCode, data);
    }
}

**Comment by Rafazeon** [comment]
> Task :react-native-google-cast:compileDebugJavaWithJavac FAILED
C:\Projeto Surf\React-Native\node_modules\react-native-google-cast\android\src\main\java\com\reactnative\googlecast\GoogleCastOptionsProvider.java:19: error: GoogleCastOptionsProvider is not abstract and does not override abstract method getCastOptions(Context) in OptionsProvider
public class GoogleCastOptionsProvider implements OptionsProvider {

**Comment by Rafazeon** [comment]
Finally works but <CastButton /> don't appear nothing :/ Android
