### ISSUE TITLE
Testing on Samsung TV

### ISSUE THREAD

**Issue by czanella** [react-native-google-cast/react-native-google-cast#108]
I'm trying to test my application on a Samsung Led 40 tv, which has Google Cast support (I'm not using any Custom Receiver, I'm trying to use the Default Media Receiver).

The problem is that the TV is not detected by react-native-google-cast. If I try to run `GoogleCast.getCastState()`, the result is always `NoDevicesAvailable`, and naturally `CastButton` is never rendered. Both the app and the TV are connected to the same wi-fi network.

Other apps, such as Netflix and YouTube, can detect and connect to the TV normally.

Has react-native-google-cast been tested with Google Cast devices other than Chromecast? Does anybody else have problems using react-native-google-cast with a Samsung TV?

Thanks!

**Comment by petrbela** [comment]
Hi! I haven't tested with non-Chromecast devices but in theory, it should still work. Have you enabled [WiFi discovery](https://developers.google.com/cast/docs/ios_sender/#xcode_10)?

**Comment by czanella** [comment]
Thanks for the quick answer! Forgot to mention that I'm developing & testing on an Android device. Does Android have an equivalent of WiFi discovery? Or anything else that must be enabled in order to work with Google Cast?

**Comment by petrbela** [comment]
@czanella Not that I'm aware of. The only thing that comes to mind is if you're building a custom app and it's not published yet, you need to register your receiver device at https://cast.google.com/publish/

**Comment by flexgrip** [comment]
This must be the case @petrbela. My app sees about 1/3rd of the castable locations that, say, the twitch app sees. I don’t quite understand why the hell a custom receiver would make a difference. But right now, this library can only see the physical hardware chromecast devices.

It makes no sense to me that a custom receiver would be needed so that a “google cast device” built into a smart tv can be discovered by your package. Maybe it needs the newest cast sdk? Just shooting in the dark.

**Comment by petrbela** [comment]
I think a custom and default app should be equivalent in terms of discovering and connecting to devices.

Can you test with the latest SDK?

**Comment by ankesh7** [comment]
I am facing the same issue but on iOS device for local development. I only get my Google Home Mini speaker as cast device option but not my Samsung TV. The same device has YouTube app that shows my Samsung TV as option when I try to cast. I have Wifi discovery enabled and followed the guide thoroughly. Was anyone able to resolve the issue?

**Comment by flexgrip** [comment]
This still seems to exist in 4.x.x. I just bought a new vizeo tv. On the tv is a big sticker that says something about "official" chromecast. Or maybe it says "Genuine". Anyway... it shows up in the discovery list. But basically rokus do not. Switch over to the youtube app and 8 total devices in my home show up instead of 2.

What could this possibly be?

**Comment by thgcst** [comment]
Hey guys, any discoveries on this?

**Comment by raphaelcorreaoct** [comment]
Hey!
I have the same problem.
No chromecast device works but, on Samsung TV and apple TV it doesn't work. Do I need to do any extra configuration for these devices?

**Comment by petrbela** [comment]
Apple TV doesn't use the Cast protocol; instead, you'll need to use AirPlay. You might combine `DiscoveryManager` from this package with some RN AirPlay library to display a custom list of devices to stream to (that's what the YouTube app does).

As for Samsung: if the TV officially supports Chromecast, then it *should* show up in the Cast dialog. Unfortunately, I don't have a Samsung TV to test it but maybe one of the following articles might help:
- https://developers.google.com/cast/docs/ios_sender/permissions_and_discovery?hl=en
- https://developers.google.com/cast/docs/discovery?hl=en
- https://developers.google.com/cast/docs/ux_guidelines?hl=en

**Comment by raphaelcorreaoct** [comment]
Hello @petrbela, Thanks for the quick response.
I did a lot of research and it seems that TV's like samsung have a custom implementation of chrome cast. It seems it is necessary to create an App with a custom channel. I believe this should happen with other brands as well.
