### ISSUE TITLE
CastMedia func has no return value in Android

### ISSUE THREAD

**Issue by rangav** [react-native-google-cast/react-native-google-cast#110]
CastMedia for iOS returns mediaInfo but has no return value on android implementation. Just to let you know there is mismatch.

**Comment by Rafazeon** [comment]
up, here don't work CastMedia Android too

**Comment by Rafazeon** [comment]
Hey I fixed android issue

**Comment by petrbela** [comment]
@Rafazeon care to share how you fixed it? :)

**Comment by Rafazeon** [comment]
Yes @petrbela 

I fixed issue with de code below:

componentDidMount() {
   this.registerListeners()
}

registerListeners = () => {

    handleClicked = (event) => {
      const { info } = this.props
      
      if(event === 'SESSION_STARTED') {
        return cast(info)
      }
    }

    cast = (info) => {  
      GoogleCast.castMedia({ 
        mediaUrl: 
          info.videos.url,
        imageUrl:
          info.images.url,
        title: info.name,
        subtitle: 
          info.description,
        studio: 'Surf Evolution',
        streamDuration: 596, // seconds
        contentType: 'video/mp4', // Optional, default is "video/mp4" 
        playPosition: 10, // seconds
      }),
      GoogleCast.launchExpandedControls()
      // GoogleCast.sendMessage('urn:x-cast:com.google.youtube.mdx', 'abc')
      this.sendMessage()  
    }

    const events = `
      SESSION_STARTING SESSION_STARTED SESSION_START_FAILED SESSION_SUSPENDED
      SESSION_RESUMING SESSION_RESUMED SESSION_ENDING SESSION_ENDED
      MEDIA_STATUS_UPDATED MEDIA_PLAYBACK_STARTED MEDIA_PLAYBACK_ENDED MEDIA_PROGRESS_UPDATED
      CHANNEL_CONNECTED CHANNEL_DISCONNECTED CHANNEL_MESSAGE_RECEIVED
    `
      .trim()
      .split(/\s+/)
    console.log(events)
    
    events.forEach(event => {
      GoogleCast.EventEmitter.addListener(GoogleCast[event], function() {
        console.log(event, arguments)
        GoogleCast.getCastState().then(response => response === 'Connected' && handleClicked(event))
      })
    })
  }

sendMessage = () => {
    const channel = 'urn:x-cast:com.reactnative.googlecast.example'

    GoogleCast.initChannel(channel).then((res) => {
      debugger
      GoogleCast.sendMessage(channel, JSON.stringify({ message: 'Hello' }))
    })
  }

and finally render() { <CastButton style={{ width: 24, height: 24, marginRight: 20 }} /> }

Thanks @petrbela for this awesome library
