### ISSUE TITLE
[iOS] App crash on first usage of chromecast over nearby devices

### ISSUE THREAD

**Issue by fi-nik** [react-native-google-cast/react-native-google-cast#113]
Hello, i'm having issue that app crash if i connect to chromecast over nearby devices for first time. Reason for crash is that when calling getCastDevice , device that we get from castSession has deviceVersion nill, which is causing crash. Also device has some strange values like friendlyName is "Nearby device" and not my chromecast name. After first time, and that crash, when i want to cast, i see my cast device, and it's working normally , and getCastDevice return normal values. Do you know how to solve this issue? Or can i make PR which will prevent crashing if deviceVersion is nil.

**Comment by dhamnesh** [comment]
Hi @fi-nik,

Facing the same issue. How to resolve it?

**Comment by fi-nik** [comment]
> Hi @fi-nik,
> 
> Facing the same issue. How to resolve it?

Well, i had to fork library and remove that property from response :/

**Comment by petrbela** [comment]
Hi! Sorry I've missed this one. We can certainly add a check for `nil` to prevent the crash. You can open a PR or I can do it probably later this week.

Just to help me debug, how do you activate the nearby devices search? Is it through the "guest" mode?

**Comment by fi-nik** [comment]
> Hi! Sorry I've missed this one. We can certainly add a check for `nil` to prevent the crash. You can open a PR or I can do it probably later this week.
> 
> Just to help me debug, how do you activate the nearby devices search? Is it through the "guest" mode?

Whatever is faster. 
I think its enough to be in guest mode, but not sure. While are you debugging, please check why icon is not filled with passed color on first render, but as soon you click on button color is changed.

**Comment by petrbela** [comment]
I think this should now be fixed in v4.
