### ISSUE TITLE
Only seeing "Nearby Device" / Can't discover devices

### ISSUE THREAD

**Issue by lindborg** [react-native-google-cast/react-native-google-cast#114]
I'm having trouble discovering devices...

When clicking the cast button on iOS 12 (xCode 10, v4 branch, Google SDK 4.3.0), I only get a list with "Nearby Device". Clicking it will result in "Listening for nearby device" and "Please enter code of nearby device". After typing the code, the dialog closes and nothing. Other apps (Youtube etc.) can easily find my two Google Chromecast's on the same phone / network. 

xCode:

> Activated, Wireless Accessory Configuration

>   GCKDiscoveryCriteria *criteria = [[GCKDiscoveryCriteria alloc] initWithApplicationID:kGCKDefaultMediaReceiverApplicationID]; GCKCastOptions* options = [[GCKCastOptions alloc] initWithDiscoveryCriteria:criteria]; [GCKCastContext setSharedInstanceWithOptions:options];

Install:

> npm install git://github.com/react-native-google-cast/react-native-google-cast.git#v4

Podfile:

> source 'https://github.com/CocoaPods/Specs.git'
> platform :ios, '9.0'
> 
> target 'App' do
>   nmpath = '../node_modules'
>   rnpath = "#{nmpath}/react-native"
>   
>   pod 'React', path: rnpath, subspecs: [
>     'Core',
>     'CxxBridge', # Include this for RN >= 0.47
>     'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
>     'RCTText',
>     'RCTNetwork',
>     'RCTWebSocket', # Needed for debugging
>     'RCTAnimation', # Needed for FlatList and animations running on native UI thread
>     'RCTImage',
>   ]
>   pod 'yoga', path: "#{rnpath}/ReactCommon/yoga"
>   pod 'DoubleConversion', podspec: "#{rnpath}/third-party-podspecs"
>   pod 'glog', podspec: "#{rnpath}/third-party-podspecs"
>   pod 'Folly', podspec: "#{rnpath}/third-party-podspecs"
> 
>   pod 'google-cast-sdk', '4.3.0'
>   pod 'react-native-google-cast', path: "#{nmpath}/react-native-google-cast/ios/"
> end
> 
> post_install do |installer|
> 	installer.pods_project.targets.each do |target|
> 		
> 		# The following is needed to ensure the "archive" step works in XCode.
> 		# It removes React & Yoga from the Pods project, as it is already included in the main project.
> 		# Without this, you'd see errors when you archive like:
> 		# "Multiple commands produce ... libReact.a"
> 		# "Multiple commands produce ... libyoga.a"
> 		
> 		targets_to_ignore = %w(React yoga)
> 			if targets_to_ignore.include? target.name
> 			target.remove_from_project
> 		end
> 	end
> end

**Comment by moodjii** [comment]
Any help with the comment above? @petrbela?
