### ISSUE TITLE
Connecting me directly to the chromecast when there is only

### ISSUE THREAD

**Issue by danielgssp** [react-native-google-cast/react-native-google-cast#118]
hi ;)
when there is only one chromecast it is possible with a click to connect it directly, without the option to select it.
and when you have more than one obviously appear the list of chromecast to connect me ?

**Comment by petrbela** [comment]
Hi! First of all, I believe it might be against the design recommendations. Having said that, it's definitely not possible in v3. It might be doable in v4 which will give you a way to directly manage the connections but the code for that is not finished yet. I'll add it on the roadmap but it's probably not the most critical path.

**Comment by danielgssp** [comment]
Wel, it's ok! ty ;)
