### ISSUE TITLE
The button does not appear in the IO's

### ISSUE THREAD

**Issue by danielgssp** [react-native-google-cast/react-native-google-cast#119]
I manually set up the chromecast following all the steps and activated the `Wireless Accessory Configuration,` but the button does not appear on the iPhone. 
It's all right, it appears on Android, What can I be doing wrong?

and he's with that warning :..
Module `RNGoogleCast` requires main queue setup since it overrides `constantsToExport` but dons't implement `requiresMainQueuesetup`. In a future release React Native will default to initializing all explicity opted-out of.

**Comment by petrbela** [comment]
Does the example project work for you? Which version are you using?

You can safely ignore the warning (will be fixed in the next version).

**Comment by danielgssp** [comment]
Good idea, I'll test the example. 
I'm using v3.

**Comment by danielgssp** [comment]
apparently it worked on the simulator but on the physical device it still does not appear!
