### ISSUE TITLE
Android: error: incompatible types: android.support.v7.app.MediaRouteButton cannot be converted to androidx.mediarouter.app.MediaRouteButton

### ISSUE THREAD

**Issue by leifdroms** [react-native-google-cast/react-native-google-cast#122]
I can't get the app compiled for Android. iOS works fine. I keep getting the following error when I try to run `react-native run-android`  : 

`> Task :react-native-google-cast:compileDebugJavaWithJavac FAILED
./node_modules/react-native-google-cast/android/src/main/java/com/reactnative/googlecast/GoogleCastButtonManager.java:34: error: incompatible types: android.support.v7.app.MediaRouteButton cannot be converted to androidx.mediarouter.app.MediaRouteButton
    CastButtonFactory.setUpMediaRouteButton(context, button);
                                                     ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
1 error

FAILURE: Build failed with an exception.
`

It seems to have some problem convertinig the old support library package to the new one (Androidx) but I'm lost on how to fix this.

**Comment by dhamnesh** [comment]
Facing the same issue. How to resolve it.?

**Comment by petrbela** [comment]
Hi! This will be fixed by #121. Until that's merged and released, you can set `castFrameworkVersion` to `16.2.0` as described in the [Android installation](https://github.com/react-native-google-cast/react-native-google-cast#installation)

**Comment by petrbela** [comment]
Released as 3.1.3

**Comment by leifdroms** [comment]
I wrote a script to rewrite all the references in my node modules because it looks like some other libraries I have are running into the same problem. It worked!
