### ISSUE TITLE
How to hide the cast button in Expanded Controller?

### ISSUE THREAD

**Issue by nenjamin2405** [react-native-google-cast/react-native-google-cast#125]
First of all, thank you for creating this awesome library for integrating Google Cast to React Native.

As I read in the documentation, the **Expanded Control** has the exception of receiving session lifecycle (connect/stop casting), so I cannot listen to the **SESSION_ENDED** event when the user stops casting using **Cast Button** inside expanded control. It leads to the problem that my app's UI cannot reflect the correct casting state.

So my question is: is there any way for me to remove the **Cast Button** in **Expanded Controller** in order to prevent users to trigger the **SESSION_ENDED Event**. Instead, I only need to use 

`import { CastButton } from 'react-native-google-cast'`

and display it on my UI and freely listen to the event changing.

Thank you!

**Comment by petrbela** [comment]
Hi @nenjamin2405! Are you sure the SESSION_ENDED event is not triggered? It seems weird it would behave differently based on which UI button you press.

**Comment by tylerfloyd** [comment]
I am running into this issue, too.

**Comment by nenjamin2405** [comment]
Hi @petrbela, sorry for the late response, yes I tested it and the event SESSION_ENDED is not triggered if I stop the Chromecast inside EXPANDED CONTROLLERS. As @tylerfloyd said, it seems to be Android specific problem

**Comment by jonathanm-tkf** [comment]
Yes I have the same problem only Android and only EXPANDED CONTROLLERS thanks

**Comment by jonathanm-tkf** [comment]
any solution for this?

**Comment by ssg-luke** [comment]
I am seeing the same issue with the expanded controller

**Comment by AirborneEagle** [comment]
Can confirm. This is a legit issue, albeit I can only confirm with version: `3.3.0`
Pixel 3 running android 11

Steps to reproduce. on android
- connect to casting.
- on the expanded controls modal, click the cast button in the top right
- stop casting
- SESSION_ENDED event is not triggered.

has anyone been able to reproduce this issue on version 4.0+?

**Comment by petrbela** [comment]
Please upgrade to the latest version. The cast button is still displayed in the expanded controller (that's how it should be) but the session updates should be working properly.
