### ISSUE TITLE
_OBJC_CLASS_$ reference error

### ISSUE THREAD

**Issue by narendrabade** [react-native-google-cast/react-native-google-cast#126]
<img width="319" alt="Screen Shot 2019-06-26 at 2 53 30 PM" src="https://user-images.githubusercontent.com/13159169/60206796-732ab700-9822-11e9-91af-4c6b60a80d90.png">

We have a standalone video playback app, in which we have Chromecast working fine. Now we are trying to convert this app as a framework and add it in the parent app. 
While building framework, reference error pops up. If I comment out the code in RNGoogleCast.m, where these classes are referenced then the framework builds successfully and works fine with parent app. With commented code, I don't see the chromecast button while playing video.

In Build Setting of Framework, other linker flags set to -ObjC. If I remove it or keep the same value as an app,  then frameworks build successfully but don't work with the parent app.

Please let me know if you need more information from the app or framework.

Can someone help me to get rid of these errors and get the chromecast button enabled while playing video?

**Comment by sck-v** [comment]
@narendrabade do you use CocoaPods? If so, try to downgrade version. Downgrading from 1.7.0.to 1.5.3 helped me
