### ISSUE TITLE
CastButton is inactive

### ISSUE THREAD

**Issue by undef1ned** [react-native-google-cast/react-native-google-cast#133]
Hello,

I've integrated 3.1.3v of the lib. However, when I start the app, I can see the CastButton but it's not clickable/not active. There is no popup with device list. The Chromecast device is connected and is seen by other apps.

Followed the setup guide and seems didnt miss anything. Anyway the CastButton is present, which means the lib locates Chromecast around, but tapping on icon results in nothing.

Any ideas?

  ```
React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 22.71 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.3.0 - /usr/local/bin/node
      Yarn: 1.6.0 - /usr/local/bin/yarn
      npm: 6.1.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 16, 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 24.0.1, 24.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.1, 27.0.2, 27.0.3, 28.0.0, 28.0.2, 28.0.3
        System Images: android-23 | Android TV ARM EABI v7a, android-23 | Google APIs ARM EABI v7a, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.10 => 0.59.10 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7


```

**Comment by nbennink** [comment]
We experience a similar problem but it's limited to a few devices. One Plus 6(T) and the Samsung Galaxy S8 to be exact (Android 9). I don't experience problems with other Android devices such as the Galaxy J5 2018, Google Nexus 5X (Android 8.1) or the One Plus 5T (Android 9). 

Do you experience this issue on all devices are only a few?

**Comment by undef1ned** [comment]
@nbennink Tried with LG G4 only (Android 7)

**Comment by nbennink** [comment]
The Chromecast button is quite hard to press on all Android devices. A lot of times I press on the button and it just ignores the press event and goes to the view underneath it.

It's hard to reproduce but these are the steps: build the library using version 3.1.3. Add a view with with a TouchableHighlight. Place the Cast button on top of that view (top right corner in my app). Try to press the cast button a few times. It ignores the press handler on the cast button and uses the onPress handler of the other view. As mentioned above: It's hard to reproduce on some devices and very easy on others.

**Comment by petrbela** [comment]
Hmm, one thing that could be happening is the button area is too small (24x24 by default I believe). I think the recommended minimum size for a button is 44pt, and a lot of design systems use 48. Can you try changing the button style to something like `{{ margin: -12, width: 48, height: 48 }}` (negative margin will make the clickable area larger without moving the button) and see if it helps?

**Comment by ronit-kadwane** [comment]
@petrbela Any update on this issue?
I am also facing the same issue on Samsung S9 and S10 devices.

**Comment by yemd** [comment]
I am also facing the exact same issue on Samsung Galaxy A5, Android 7.0

**Comment by yemd** [comment]
Tried on Galaxy A10, Android 9.0, can't click the button either

**Comment by petrbela** [comment]
I'm testing on Samsung Galaxy S6 without a problem. Unfortunately, I'm not able to verify with other devices but it seems strange it wouldn't work.

You can try downloading a demo app built with Expo https://github.com/react-native-google-cast/RNGCExpo and see if the Cast button shows up and is interactive.

Alternatively, you can add your own Button and use the [DiscoveryManager](https://react-native-google-cast.github.io/docs/api/classes/discoverymanager#getdevices) to populate a custom Cast device chooser.

If you still have trouble, please open a new issue with a code sample.

**Comment by DeabitTech** [comment]
Hi @petrbela , your project github in expo never work, in developer build internal, in expo go client and in build standalone, i want use your library, but if i do build with aes i have the CastButton in my page but without any feedback when i press it, but if i do build with expo build:android, i have a big error: "RNGoogleCastButton" was not found in the UIManager

https://user-images.githubusercontent.com/63302971/194645800-1064e057-2f53-455a-8bbf-ac9b4c3f1293.mp4

**Comment by petrbela** [comment]
@DeabitTech Please see https://github.com/react-native-google-cast/RNGCExpo for usage with Expo. If you're still having trouble please open a new issue with a clear description of what's happening with an example code for how to reproduce it.

**Comment by DeabitTech** [comment]
Hi @petrbela , i reproduce the code of inside your repository, and not work never.
https://github.com/react-native-google-cast/RNGCExpo in cloned this repo, installed all dependencies, take a build with expo build:android and never work, please can you fix the code inside your repository? thank you so muth

**Comment by DeabitTech** [comment]
@petrbela hi, you try the code inside your repo? You can see the cast Button completly inactive, can you help me? Best regards

**Comment by petrbela** [comment]
@DeabitTech Please create a new issue with the type of device you're using and a way to reproduce your problem.

**Comment by DeabitTech** [comment]
@petrbela but is not necessary, because if you clone your repo https://github.com/react-native-google-cast/RNGCExpo or download your apk https://github.com/react-native-google-cast/RNGCExpo/releases/download/1.0.0/0c8faa9c-7f44-424c-9c92-0006064c5e93-7f948c918fce4fa39054c06cf485ac58.apk you can see the button always inactive.
please can you have 5 minutes for try your code?
