### ISSUE TITLE
Example app not finding chromecasts on android

### ISSUE THREAD

**Issue by kullt** [react-native-google-cast/react-native-google-cast#14]
The example app builds and runs on android with no errors but when I search for devices it doesn't find any.

Weirdly it will find only one of my two chromecasts if another app (e.g. netflix) is open and connected to it or has just been connected to it.  As soon as I close the other app the example app won't find any chromecasts again.

I made no changes to the example app just cloned and ran it.

Do you have any idea what might cause this?

I should also say that I get no errors in the app or with remote debugging.

**Comment by codetony25** [comment]
Can we see some examples?

**Comment by codetony25** [comment]
Any plans on resolving this issue? Does anyone happen to have a workaround for this currently?

**Comment by asdrubalivan** [comment]
Same error here!

**Comment by Rogergonzalez21** [comment]
Is there any workaround to this?

**Comment by WilliamAlexander** [comment]
Yup, iOS works like a dream (the irony). Android says there are chromecasts, however does not list them. According to the debug it's there but status is null.
If I connect to (let's say youtube), go back to app and refresh the chromecast, I'm able to connect.
This package used the CastCompanionLibrary-android. When I have time I'll create a new project using that and see if that works...I'm guessing it will

**Comment by charliesbox** [comment]
Hi!

Maybe I can shed some light about the way I'm using the example.

What I do, is to run the example from android studio. And when it does, it shows me the chromecast around me.

Reason I do it in this way is to open the emulators with google play services support (the ones that can be created from android studio). Otherwise, without that package is not possible to detect chromecast.

Thoughts?

**Comment by charliesbox** [comment]
FYI, based on @codetony25 points, I've added a mention to some dependencies required by the castcompanionlibrary.

I hope that those fix the issues :)

(Also, a new version of this project was releases some hours ago!)

Please, reopen the issue if the problems persist.

**Comment by undef1ned** [comment]
Can not detect Chromecast device :( Lib version 0.3.0

**build.gradle**

>     compile ('com.google.android.gms:play-services-cast:10.2.1') {
>         force = true;
>     }
>     compile 'com.android.support:mediarouter-v7:25.2.0'


> 05-29 23:14:38.921 25160 25198 E GoogleCastModule: Stopping Scan
> 05-29 23:14:38.921 25160 25198 E GoogleCastModule: start scan Chromecast 
> 05-29 23:14:38.965 25160 25160 E GoogleCastModule: Chromecast Initialized for the first time!
> 05-29 23:14:39.103 25160 25160 E GoogleCastModule: onCastAvailabilityChanged: exists? true
> 05-29 23:14:39.133 25160 25198 E GoogleCastModule: devices size 0
> 05-29 23:14:39.142 25160 25197 I ReactNativeJS: '[GoogleCastModule] New Devices', []
>

**Comment by charliesbox** [comment]
thanks @undef1ned , will take a further look.

could you try it with the master branch? there are some changes that I hadn't published yet

**Comment by undef1ned** [comment]
@charliesbox 

oh yes, it is from master branch already

one thing I found just now - reconnecting the wifi may help to recognise device. This means the app is running, I call Chromecast.startScan(), logs say there are 0 devices, then I simply keep the app idle (dont close it, dont reload, just simply not touching), then I disconnect the wifi connection and connect it back... finally see my Chromecast in logcat logs

**Comment by undef1ned** [comment]
@charliesbox 

What about this? https://developers.google.com/cast/v2/ccl_migrate_sender

**Comment by charliesbox** [comment]
@undef1ned interesting. Although, I'm using https://github.com/googlecast/CastCompanionLibrary-android as the wrapper for the chromecast library in android.

Will go deeper about this issue in the next couple of days. If you find the fix, or you are in a hurry, open a PR :)

**Comment by charliesbox** [comment]
Wow

```Because the Cast SDK v3 design was influenced by Cast Companion Library, the migration from CCL to v3 involves mostly one-to-one mappings of classes and their methods.```

Time to move forward. I opened an issue to upgrade to cast v3 :)

**Comment by developersoul** [comment]
It's funny, works when the wifi turn off and then on, it can be fixed by that way....

**Comment by petrbela** [comment]
Please upgrade to the latest version, it handles discovery automatically.
