### ISSUE TITLE
Need help in creating new component library

### ISSUE THREAD

**Issue by sureshsamanthapudi** [react-native-google-cast/react-native-google-cast#141]
This issue is not related to 'react-native-google-cast'.
We are creating a new private component library for our organization.
I tried the following:

Component library itself as a separate project with react and react-native as peer dependencies in my project.
But having just the components code in component library is not useful because we have to add new code or fixes and we have to run the story book(Because of peer dependencies could not be able run story book).
Could you please help me with the model I have to follow for creating a react native library?

Thank you in advance.

**Comment by petrbela** [comment]
Not sure if I understand your question correctly but the library usually has `react` and `react-native` defined both as `peerDependencies` (with a flexible version), and also as `devDependencies` (with a more specific version) for local development, e.g. tests, demo, or Storybook.

I'd recommend you follow https://github.com/frostney/react-native-create-library (https://medium.com/wix-engineering/creating-a-native-module-in-react-native-93bab0123e46) or https://github.com/peggyrayzis/react-native-create-bridge
