### ISSUE TITLE
Cast Button in iOS app build with Google Cast 4.4.4 not visible

### ISSUE THREAD

**Issue by normenster** [react-native-google-cast/react-native-google-cast#142]
I've implemented this module with v3.5.6 of GoogleCast and it works fine. Now I've updated the Google Cast SDK Library to 4.4.4 (via pod) and it works in Developer Run Mode on my device. But if  I publish the app to testflight and install it on my device, the cast button ist never showed. Any Ideas on this?  There is a Run Script `strip_unused_archs.sh` for removing unused architectures, but that shouldnt be an issue right?

**Comment by aubert-creation** [comment]
Same issue. Work great on iOS simulator and no cast button on Testflight. I have a run script for unused architecture too. 

Any updates? @normenster do you have fix your issue ?

**Comment by petrbela** [comment]
@normenster @aubert-creation Can you guys check if you're still having issues with v4.1.0? Btw make sure to update native versions as described in https://github.com/react-native-google-cast/react-native-google-cast/releases/tag/4.1.0
