### ISSUE TITLE
react-native-google-cast em TVs smart is possible?

### ISSUE THREAD

**Issue by santosrenanlimer** [react-native-google-cast/react-native-google-cast#146]
Is it possible to detect devices on smarts tvs? I did a test here and CastButton didn't render, only works with chromecast connected devices? If so, what could be the alternative to solve this problem.
Sorry for my english, I'm brazilian.

**Comment by petrbela** [comment]
Hi! In general, Android TVs should be supported. I think other smart TVs don't support the official Google Cast protocol, so they won't work. What TV did you test with? Can you cast to it from other apps?
