### ISSUE TITLE
Android: unable to cast video

### ISSUE THREAD

**Issue by PestiB9** [react-native-google-cast/react-native-google-cast#150]
RN -> 0.61.2
react-native-google-cast -> 3.1.3

After setting all the listeners like in the example i set up the connection and i get:
SESSION_STARTING [null]
SESSION_STARTED [null]

then i can see both the media title on the display and the expanded media control on the device for a little moment and it goes back to the screen i get after connecting (before i call the cast function).

Meanwhile in the console i get this:
MEDIA_STATUS_UPDATED [{"mediaStatus": {"idleReason": 0, "muted": false, "playerState": 5, "streamDuration": 0, "streamPosition": 0}}]
MEDIA_STATUS_UPDATED [{"mediaStatus": {"idleReason": 4, "muted": false, "playerState": 1, "streamDuration": 13, "streamPosition": 0}}]

Now, i know the idleReason: 4 is an error with the playback of the media, but how can i get some more error details or do somebody knows what the issue could be?

**Comment by petrbela** [comment]
Hey @PestiB9, what's the format of the media?

**Comment by PestiB9** [comment]
Hey it's a mp4 video, i tried on different monitors with the same chromecast hdmi device and different different wifi networks but i get always the same error even changing the video (always mp4).
I didn't tried to use a media with different formato yet.

**Comment by petrbela** [comment]
Should be fixed in the latest version.
