### ISSUE TITLE
How to install V4

### ISSUE THREAD

**Issue by neoassyrian** [react-native-google-cast/react-native-google-cast#153]
Hi guys, 

Is there any basic information on how to install the V4 of this branch. I would like to use that one. I have used V3 before, and now would like to trial V4. 

I installed the V4 branch into my RN applicaion using
npm install --save git://github.com/react-native-google-cast/react-native-google-cast#v4

Then did cd android > ./gradlew clean 

Then tried to build it and got the following: 
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :react-native-google-cast.
     Required by:
         project :app
      > Unable to find a matching configuration of project :react-native-google-cast:
          - None of the consumable configurations have attributes.

```

Keep in mind that I had V3 in my project previously, and I was assuming that the same setup instructions are the same, so I simply upgraded. 

Is there are things that needs to be removed/added to link or setup V4? 

I would like to test it and perhaps contribute to it. I'm only testing the "Android" application for now.

**Comment by petrbela** [comment]
Hey! Thanks for your interest! Right now, v4 works with the example project in the repo, so I'd recommend checking that out. However, I'd still consider it in alpha/preview stage, so things might still break. I probably wouldn't recommend it yet if you're not comfortable with RN libraries. I hope to get back to finalizing a beta of v4 in December. (Sorry, it's a side project and startups don't leave much free time to play around :))

**Comment by neoassyrian** [comment]
Hi @petrbela 
Has been any progress on this one? :) 

Thanks

**Comment by petrbela** [comment]
@neoassyrian https://react-native-google-cast.github.io/docs/getting-started/installation

**Comment by petrbela** [comment]
As this is now described in the new docs, I'm closing this issue.
