### ISSUE TITLE
[ANDROID] Google cast not available.

### ISSUE THREAD

**Issue by seeocon** [react-native-google-cast/react-native-google-cast#154]
**Describe the bug**
So I've set everything up, as stated in the docs. iOS version of the app can detect devices, however the android version is not detecting anything. I get message "NoDevicesAvailable". 

**Versions:**
- RNGC Library Version: 3.2.1
- Android Version (if applicable): above 27 I believe.
- OS Version (if applicable): 7+ (everything above 7 has been tested)

**To Reproduce**
1. Open app
2. navigate to wherever google chrome cast button is
3. no button, no devices detected.

**Expected behavior**
Devices should be showing up, button should be showing.

**Screenshots**
No screenshots needed, the ChromeCast button doesn't show.

**Additional context (LOG)**
Error: Google Cast not available
NoDevicesAvailable

**Comment by egorzvuzdetskyi** [comment]
+1

**Comment by Stenbaek** [comment]
+1

**Comment by paramaggarwal** [comment]
+1

**Comment by juanpetterson** [comment]
+1

**Comment by petrbela** [comment]
This should now be working properly if you follow the instructions for v4.
