### ISSUE TITLE
Error: Google Cast not available

### ISSUE THREAD

**Issue by johnbowdenatfacet** [react-native-google-cast/react-native-google-cast#162]
**Describe the bug**
Install app on Android device builds but results in (from GoogleCast.getCastState):
Error: Google Cast not available

**Versions:**
- RNGC Library Version: 3.2.2
- Android Version (if applicable): api 29 on emulator
- OS Version (if applicable): 10 and 9
- RN:  0.61.1
- React: 16.9.0

**To Reproduce**
Follow setup instructions

**Expected behavior**
Chrome cast to at least connect using sdk.

**Comment by petrbela** [comment]
This looks like you don't have Google Play Services installed. On an emulator, you need to install Google Play Services manually. You can install them either from http://opengapps.org or follow tutorials online.

**Comment by johnbowdenatfacet** [comment]
This also happens on my S10 adb device with Play etc installed.

**Comment by johnbowdenatfacet** [comment]
Sorry, I had the meta-data tag in the wrong place.  Closing this.
