### ISSUE TITLE
use local image instead of internet link image

### ISSUE THREAD

**Issue by raphaelluiz128** [react-native-google-cast/react-native-google-cast#166]
I am testing on android and can not put an image that is inside the application in the 'imageUrl' part. You got it ? I can only use image links from the internet.

**Comment by petrbela** [comment]
Your local phone images cannot be used on Chromecast. The Chromecast device is like a separate computer, so it can only load remote images.

You could, in theory, create a local server on your phone and serve images from there (so-called "local streaming"). Not sure if that's what you want (it's a bit complicated) but you should be able to find guides on how to do it. Unfortunately, it's beyond the scope of this library.
