### ISSUE TITLE
[iOS] Google Cast Player's progress bar is overlapped by the Notch in landscape mode

### ISSUE THREAD

**Issue by nenjamin2405** [react-native-google-cast/react-native-google-cast#169]
**Describe the bug**
In landscape mode, Google Cast Player's progress bar is overlapped by the Notch of iOS devices

**Versions:**
- RNGC Library Version: [e.g. 3.2.0]
- iOS Version (if applicable): [e.g. 13.3]

**To Reproduce**
1. Cast video on iPhones with Notch in landscape mode
2. See the problem of overlapping

**Expected behavior**
A progress bar of Google Cast player will be not overlapped

**Screenshots**
![image](https://user-images.githubusercontent.com/16648769/72694929-53b1fd80-3b69-11ea-9479-a21fc1153519.png)

**Comment by petrbela** [comment]
Hey, I think this goes beyond the scope of this package. You might try googling general Google SDK or iPhone X horizontal video questions but I'm not sure if there's a good common solution to this issue.

**Comment by frknnay** [comment]
Hi, does this package have this screen by default?
