### ISSUE TITLE
AndroidX support 

### ISSUE THREAD

**Issue by knifedge** [react-native-google-cast/react-native-google-cast#170]
Android Build failure with React-native v0.60.5. Since latest android versions uses androidx.appcompat:appcompat:1.0.0 and RNGC is expecting  package android.support.v7.app.

**Versions:**
- RNGC Library Version: [v3.2.2]
- Android Version : 29.0.0 
- Android OS: Q

**Comment by petrbela** [comment]
Hey, are you using [jetifier](https://github.com/mikehardy/jetifier)? It should work as per #131. Which reminds me I need to update the docs.

**Comment by knifedge** [comment]
Hi @petrbela, i just followed the docs. Yeah updating document will help! Thankyou.

**Comment by knifedge** [comment]
I am using react-native-navigation in my project, so i can't Change your MainActivity to extend GoogleCastActivity and also project doesn't consist android.support.v7.app.AppCompatActivity support since it's AndroidX.

If i add *CastContext.getSharedInstance(this);*  inside onCreate function, build fails.. even with jetify.

**Comment by knifedge** [comment]
@petrbela : i was able to integrate this library, however not finding cast button on android... anyway to fix this?

**Comment by iandonov** [comment]
@knifedge How did you manage to build it?
Thanks

**Comment by knifedge** [comment]
Hi @iandonov , i integrated everything into mainapplication.java... Left mainactivity file as it is. 
And also ran jetlifier after node_module installation..

However cast button inconsistencies and issue on ios remains..
