### ISSUE TITLE
iOS 13 Permission Changes and Update to Cast SDK 4.4.4

### ISSUE THREAD

**Issue by danielgssp** [react-native-google-cast/react-native-google-cast#171]
**Describe the bug**
There was a problem with current versions iOS >= 13, recently google release a new [permissions changes ](https://developers.google.com/cast/docs/ios_sender/ios13_changes) from iOs 13 now we must add `Privacy - Bluetooth Always Usage` and then update `google-cast-sdk` to cast SDK 4.4.4, I tried to update with `CocoaPods` from `3.2.2` to `4.4.4` it can't because that error bellow!

```
CocoaPods could not find compatible versions for pod "google-cast-sdk":
  In Podfile:
    google-cast-sdk (~> 4.4)

    react-native-google-cast (from `../node_modules/react-native-google-cast/ios/`) was resolved to 3.2.2, which depends on
      react-native-google-cast/Default (= 3.2.2) was resolved to 3.2.2, which depends on
        google-cast-sdk (<= 4.3.0)

Specs satisfying the `google-cast-sdk (~> 4.4), google-cast-sdk (<= 4.3.0)` dependency were found, but they required a higher minimum deployment target.
```

**Versions:**
- RNGC Library Version: [e.g. 3.2.0]
- iOS Version (if applicable): [e.g. 13.3.0]

**Comment by petrbela** [comment]
It's a known issue. Please read the [installation instructions](https://github.com/react-native-google-cast/react-native-google-cast#installation) for CocoaPods and let me know if anything's unclear.

**Comment by ashnfb** [comment]
I found on iOS 14, the expanded controller caused the app to crash using google-cast-sdk 4.3.0.  I got around this by using the no-bluetooth subspec, which hilariously doesn't specify a google-cast-sdk version (so it uses the latest available).

in my podfile:
```
'react-native-google-cast', :path => '../node_modules/react-native-google-cast/ios', :subspecs => [
    'NoBluetooth'
  ]
```
