### ISSUE TITLE
Incorrect README, or missing feature

### ISSUE THREAD

**Issue by jasonbodily** [react-native-google-cast/react-native-google-cast#174]
**Describe the bug**
The documentation says there is a function `getCurrentDevice` available on GoogleCast. No such function exists in the source.

**To Reproduce**
1. Invoke `GoogleCast.getCurrentDevice()`

**Expected behavior**
Device information should be returned. Instead I get function is not defined.

**Comment by jasonbodily** [comment]
The intent is to get information on the currently connected device. getCurrentDevice does not work, and `getCastDevice` returns `undefined` even when `getCastState` is `Connected`

**Comment by petrbela** [comment]
Ha! Indeed it's missing. Do you want to make a PR? I'm not sure when I'll have time to fix this.

**Comment by petrbela** [comment]
Implemented in v4. See https://react-native-google-cast.github.io/docs/api/classes/castsession#getcastdevice
