### ISSUE TITLE
Is there any way to send custom headers to default receiver?

### ISSUE THREAD

**Issue by brooklyn097** [react-native-google-cast/react-native-google-cast#183]
Hi, Thanks for great package!

I'm wondering how to send custom headers like cookie or something else to do authentication to default receiver? I've done some research and it seems could be done with a custom receiver but i just want to use default receiver.

**Comment by grovertb** [comment]
+1 I need send header referer

**Comment by petrbela** [comment]
I don't think this is possible. The Cast protocol only takes a URL of the media to load. If you want to provide authentication, you need to build a custom receiver (you could pass auth as a query param into the default receiver but I strongly recommend against it).

Fortunately, creating a custom receiver is [pretty easy](https://developers.google.com/cast/docs/web_receiver/basic). Then just register it in the [Console](https://cast.google.com/publish) and voila!

Closing as this is a limitation of the underlying SDK, not an issue with this library.
