### ISSUE TITLE
Android Attempt to invoke virtual method getDeviceId()

### ISSUE THREAD

**Issue by mezalejandro** [react-native-google-cast/react-native-google-cast#189]
**Describe the bug**
On firebase I have the error: 
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.android.gms.cast.CastDevice.getDeviceId()' on a null object reference
       at com.reactnative.googlecast.GoogleCastModule$3.run(GoogleCastModule.java:185)

**Versions:**
- RNGC Library Version: 3.1.3
- Android Version (if applicable): 6.0.1

**Comment by jonathanm-tkf** [comment]
Same problem here but not need Firebase integration, please help

**Comment by petrbela** [comment]
This should no longer be an issue in v4.
