### ISSUE TITLE
Where is V4?

### ISSUE THREAD

**Issue by msal4** [react-native-google-cast/react-native-google-cast#195]
Hi there, I see that the last commit for v4 is from 6 months ago, so I wanted to know if it's still under development or it's cancelled or something?

If you need help with an issue or something, I'll be more than happy to help.

Thanks.

**Comment by petrbela** [comment]
Hey, @msal4 it's about 90% done but I've been pretty busy lately launching a new startup and all stopped all side projects. I'd be more than happy to add you as a contributor if you're interested. I'll try to find some time this weekend to sum up what's missing and what my thoughts are.

**Comment by vilius** [comment]
@petrbela that is great to hear. We're also relying on this project to power our iOS and Android apps. Got it working fine, but there are some hiccups that could be solved in V4. I would be glad to find some time to contribute on getting V4 out.

**Comment by dcalhoun** [comment]
@petrbela is there a set of issues that is blocking a V4 launch? If not, would it be possible to capture those issues with a special label or use [GitHub Projects](https://github.com/react-native-google-cast/react-native-google-cast/projects) to organize them so that others (hopefully including myself) can help bring V4 across the finish line?

**Comment by jacob-israel-turner** [comment]
Hey @petrbela!  Thanks for the great work you do on this project - I'm really excited to use it!  I'm integrating v4 into our project right now.

What can we, as a community, do to help get v4 out?  Is it just documentation that needs writing?  Are there pending bugs or features that need written?  Would it help to add a few collaborators who can keep the project moving?

Thanks again!

**Comment by james-relyea** [comment]
I forked v4 earlier this year and made some changes to get it working for our app - I need to clean up a few things but I'll start preparing some PRs to contribute back into this project.

**Comment by petrbela** [comment]
Hey everyone. Sorry it's been taking so long. I've just released the first beta of v4 to npm. You can install it using `npm i react-native-google-cast@next` / `yarn add react-native-google-cast@next`, read more instructions in the [brand new documentation](https://react-native-google-cast.github.io/docs/getting-started/installation).

There are still some outstanding issues and missing features (namely custom channel support and a few others). I'm keeping track of them in the [Project](https://github.com/react-native-google-cast/react-native-google-cast/projects/1); please label any issues you find with the `v4` milestone, and I'll be sure to fix them before making an official v4 release.

**Comment by petrbela** [comment]
FYI beta.5 is probably the last beta version. Assuming no more serious issues are found, once the [remaining tasks](https://github.com/react-native-google-cast/react-native-google-cast/milestone/1) are finished, I'll make a full v4 release and merge it to master.

**Comment by neoassyrian** [comment]
@petrbela the beta 6 looks solid. The only thing is the notification that comes up, it doesn't not have the "next" button when adding items to the queue or when having a playlist. 
I will be testing it in the upcoming days on both devices (but mainly Android). 
#252
