### ISSUE TITLE
Audio Support

### ISSUE THREAD

**Issue by jerson** [react-native-google-cast/react-native-google-cast#20]
what if i need to cast mp3 :(

**Comment by charliesbox** [comment]
oh, i have the feeling that this is a good one. It shouldn't be hard to prepare the library to support it.

I can take look into this in one week or two.

Feel free to open  PR if you already have an implementation :)

**Comment by alburdette619** [comment]
Hey, how's this effort going?  I'll be needing this functionality with background imagery if possible within the next couple months.  I could put a dev to work on it and at least get a working integration if no steps have been undertaken thus far.

**Comment by petrbela** [comment]
@alburdette619 Good question! I think mp3 files might already be working, though I haven't tested them. There's also support for setting a cover image in the current version, which might be what you're looking for. Let us know if something doesn't work or is missing.
