### ISSUE TITLE
Can't Click Android Button Inside TouchableWithoutFeedback

### ISSUE THREAD

**Issue by redreceipt** [react-native-google-cast/react-native-google-cast#202]
**Describe the bug**

Can't click the cast button on Android devices when nested inside `TouchableWithoutFeedback`

**Versions:**
- RNGC Library Version: 3.3.0
- Android Version (if applicable): 10

**To Reproduce**
```
<TouchableWithoutFeedback>
  <View>
    <CastButton style={{height: 40, width: 40}}/>
  </View>
</TouchableWithoutFeedback>
```

**Expected behavior**

Should be able to click the  button and have the menu show up

**Screenshots**

![Screenshot_20200623-091029](https://user-images.githubusercontent.com/2659478/85420813-b147dd00-b541-11ea-9f68-03be22f7d2a4.png)

**Comment by redreceipt** [comment]
Any ideas or updates on this issue?

**Comment by redreceipt** [comment]
Could this potentially be a related fix?

https://github.com/wix/react-native-navigation/commit/4b755a3884c2ddd74c1e1817e14b748180d77a5d

**Comment by redreceipt** [comment]
So slight update, it seems when I wrap in a `View`, I can only click the left edge of the button space:

```
<TouchableWithoutFeedback>
  <View>
    <CastButton style={{height: 40, width: 40}} />
  </View>
</TouchableWithoutFeedback>
```

But when I don't wrap in a `View` it works perfectly. 

```
<TouchableWithoutFeedback>
    <CastButton style={{height: 40, width: 40}} />
</TouchableWithoutFeedback>
```

Any ideas on what may be happening?

**Comment by petrbela** [comment]
Hmm, I'm not an Android expert so not sure exactly what might be the problem/fix here.

Btw why are you wrapping the button in a touchable? If you're trying to make the touchable area of the button larger, could you just add `padding`? The `CastButton` already handles touches.

**Comment by redreceipt** [comment]
> Btw why are you wrapping the button in a touchable?

the background is touchable so the controls disappear, the screenshot above might give you a little better context.

**Comment by petrbela** [comment]
Oh you mean the whole screen is wrapped with `Touchable`. Gotcha.

I'm sorry I don't have an answer for you right now but I'll try to look into it.

**Comment by redreceipt** [comment]
Excellent, thanks. I put in a workaround, not wrapping the whole screen anymore. Just a flexed view outside the cast button so not urgent.
GitHub <notifications@github.com> wrote:
“Oh you mean the whole screen is wrapped with Touchable. Gotcha.


I'm sorry I don't have an answer for you right now but I'll try to look into it.”

**Comment by bittu1028** [comment]
Any solution here @redreceipt  i am stuck with this casting button not being clickable inside TouchableWithoutFeedback

**Comment by redreceipt** [comment]
It’s definitely a bug. I just un-nested it 🤷‍♂️ So now my button and my controls are in a separate bottom section and the rest of the screen is flexed out.

**Comment by EyMaddis** [comment]
I think this works:
```tsx
<TouchableWithoutFeedback
  onPress={() => {
    GoogleCast.showCastDialog()
  }}
  hitSlop={{
    top: 10,
    bottom: 10,
    right: 10,
    left: 10,
  }}
>
  <View
    // same size as CastButton, because for RN it seems to be 0x0 while layouting
    style={{
      margin: 20,
      width: 20,
      height: 20,
    }}
  >
    <CastButton
      style={{
        width: 20,
        height: 20,
      }}
    />
  </View>
</TouchableWithoutFeedback>
```

I also added hitSlop, because the button is very hard to press.

It seems that `GoogleCast.showCastDialog()` only works if CastButton is rendered without it nothing happens...

**Comment by SimoneCarnio** [comment]
Same problem, just find this solution:

replace 

<TouchableWithoutFeedback
  onPress={() => {
    yourFunction();
  }}>

with 

<View onStartShouldSetResponder={ yourFunction} >
