### ISSUE TITLE
The view is not clickable and cast process not working  on iOS 13.3

### ISSUE THREAD

**Issue by andrea-valenti-sky-it** [react-native-google-cast/react-native-google-cast#205]
**Describe the bug**
[TableView] Warning once only: UITableView was told to layout its visible cells and other contents without being in the view hierarchy (the table view or one of its superviews has not been added to a window). This may cause bugs by forcing views inside the table view to load and perform layout without accurate information (e.g. table view bounds, trait collection, layout margins, safe area insets, etc), and will also cause unnecessary performance overhead due to extra layout passes. Make a symbolic breakpoint at UITableViewAlertForLayoutOutsideViewHierarchy to catch this in the debugger and see what caused this to occur, so you can avoid this action altogether if possible, or defer it until the table view has been added to a window. Table view: <UITableView: 0x1560d4000; frame = (0 0; 414 896); clipsToBounds = YES; opaque = NO; autoresize = RM+BM; tag = 9992; gestureRecognizers = <NSArray: 0x28181ae80>; layer = <CALayer: 0x2810e3e80>; contentOffset: {0, 0}; contentSize: {414, 73}; adjustedContentInset: {0, 0, 0, 0}; dataSource: <GCKUIDeviceConnectionViewController: 0x159023400>>

**Versions:**
- RNGC Library Version: [3.2.0]
- OS Version : [e.g. 13.3]

**To Reproduce**
1. Go to video
2. Show Cast Button
3. Click on 'Cast Button'
4. Show Pop Up 'nearby device'
5. Show Pop Up Connect to nearby device
6. Click on 'Connect'
7. See error

**Expected behavior**
The button works properly 

 **Actual **
The view is not clickable and cast process not working 

**Addition info**
https://developer.apple.com/forums/thread/120790

**Comment by petrbela** [comment]
Hi! Can you please post a screenshot of what your view looks like? I'm wondering why you're getting an error from tableview, which this library doesn't use.

**Comment by usamamoinakhter** [comment]
Facing the same issue but unable to select any option on this screen
[Image URL](http://imgur.com/a/ERNWFxb)

**Comment by anacentea** [comment]
Hello, I am facing the same issue, can't use guest mode on iOS 13.6. The "Connect to nearby devices" view is not tappable and can't close it. Has this been fixed, or are there any workarounds?

**Comment by usamamoinakhter** [comment]
> Hello, I am facing the same issue, can't use guest mode on iOS 13.6. The "Connect to nearby devices" view is not tappable and can't close it. Has this been fixed, or are there any workarounds?

No, still unable to find a workaround.

**Comment by andrea-valenti-sky-it** [comment]
Hello, I use the alternative procedure "pod react-native-google-cast/NoBluetooth", and this work for me but not with same UI interface

**Comment by usamamoinakhter** [comment]
> Hello, I use the alternative procedure "pod react-native-google-cast/NoBluetooth", and this work for me but not with same UI interface

Thanks i will have a look at it. Hopefully it would work.

**Comment by anacentea** [comment]
I integrated the no blueetooth one and it works but it lacks the guest mode feature
