### ISSUE TITLE
posterUrl does not work on IOS

### ISSUE THREAD

**Issue by hapo-thinhnh** [react-native-google-cast/react-native-google-cast#206]
When cast, I have added **_posterUrl_** to display the background in **_Expanded Media Control_**:

```js
startCast = (linkCast, title, mediaType) => {
    try {
     GoogleCast.castMedia ({
       mediaUrl: linkCast, // Stream media video uri
         imageUrl: "imageUrl"
         posterUrl: "posterUrl",
         title, // Media main title
         contentType: mediaType, // Optional media type, default is 'video / mp4'
      }
    } catch (error) {
       console.log ('An error has ocurred, reason:', error);
    }
};
```

But **_posterUrl_** does not work on **_iOS_**, it will take **_imageUrl_** as the background of **_Expanded Media Control_**. On **_Android_**, it works normally.

**Comment by petrbela** [comment]
I think this is now obsolete in v4, which should pass all images down to the native SDK.
