### ISSUE TITLE
react native chromecast "no media selected"

### ISSUE THREAD

**Issue by ritambrata** [react-native-google-cast/react-native-google-cast#209]
i have many videos in my app. i want to cast the video by clicking it. i set a receiver and sender for cast. it successfully pair with my tv but every time it says "no media selected". please help me out of this.

componentDidMount() {
        this.registerListeners()
        GoogleCast.getCastState().then(console.log)
        this.getCast()
 }
 
  registerListeners() {
        const events = `
          SESSION_STARTING SESSION_STARTED SESSION_START_FAILED SESSION_SUSPENDED
          SESSION_RESUMING SESSION_RESUMED SESSION_ENDING SESSION_ENDED
          MEDIA_STATUS_UPDATED MEDIA_PLAYBACK_STARTED MEDIA_PLAYBACK_ENDED MEDIA_PROGRESS_UPDATED
          CHANNEL_CONNECTED CHANNEL_DISCONNECTED CHANNEL_MESSAGE_RECEIVED
        `
            .trim()
            .split(/\s+/);

        events.forEach(event => {
            GoogleCast.EventEmitter.addListener(GoogleCast[event]);
        });
    }
 
 getCast = () => {
        GoogleCast.getCastState().then((res) => {
           
            console.log(res, 'res');
            if(res == "Connected"){
                this.cast()
            }
        })
    }
 
 cast = () => {
        console.log(this.state.videoUrl, this.state.video.title, this.state.video.thumbs['640'], this.state.video.owner.name,this.state.video.duration,  "video");
        GoogleCast.getCastDevice().then(console.log);
     
        GoogleCast.castMedia({
            mediaUrl: this.state.videoUrl,
            imageUrl: this.state.video.thumbs['640'],
            title: this.state.video.title,
            subtitle: this.state.video.title,
            studio: this.state.video.owner.name,
            duration: this.state.video.duration, // seconds
            posterUrl: this.state.video.thumbs['640'],
            playPosition: 0, // seconds
        })
        GoogleCast.launchExpandedControls();
        GoogleCast.showCastPicker()
        this.sendMessage()
    }
![1592828581514](https://user-images.githubusercontent.com/54658062/86809784-dd16a700-c099-11ea-9681-a9aef9680b1f.JPEG)

**Comment by AndriyShpyra** [comment]
@ritambrata have you added  into AppDelegate.m  'initWithApplicationID:@"yourChromecastAppId"  ?

**Comment by petrbela** [comment]
This dialog is from the Cast SDK. It means nothing is casting. Most of the casting issues should be resolved in v4 but if you're still having problems, please open a new issue with specific steps on how to reproduce.
