### ISSUE TITLE
HLS Stream Hangs

### ISSUE THREAD

**Issue by redreceipt** [react-native-google-cast/react-native-google-cast#210]
**Describe the bug**

When using the following HLS playlist, the stream on the cast device hangs. Not sure if there's a way to tell if what's in the playlist is supported. Stream plays fine through `react-native-video`. Also plays fine in Safari.

Side note, it also causes the remote cast device to become unresponsive. When clicking "stop casting" in the app. Nothing happens on the TV.

```
#EXTM3U
#EXT-X-VERSION:7
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-STREAM-INF:AVERAGE-BANDWIDTH=323654,BANDWIDTH=647308,CODECS="avc1.640029,mp4a.40.2",RESOLUTION=256x144,FRAME-RATE=29.97,AUDIO="aud1"
c38c5a18-d5b1-4ce5-aaaa-eab6e3fe33c0/Manifestvideo_323654.m3u8
#EXT-X-STREAM-INF:AVERAGE-BANDWIDTH=508941,BANDWIDTH=1017882,CODECS="avc1.640029,mp4a.40.2",RESOLUTION=480x270,FRAME-RATE=29.97,AUDIO="aud1"
c38c5a18-d5b1-4ce5-aaaa-eab6e3fe33c0/Manifestvideo_508941.m3u8
#EXT-X-STREAM-INF:AVERAGE-BANDWIDTH=710339,BANDWIDTH=1420678,CODECS="avc1.640029,mp4a.40.2",RESOLUTION=640x360,FRAME-RATE=29.97,AUDIO="aud1"
c38c5a18-d5b1-4ce5-aaaa-eab6e3fe33c0/Manifestvideo_710339.m3u8
#EXT-X-STREAM-INF:AVERAGE-BANDWIDTH=1285764,BANDWIDTH=2571528,CODECS="avc1.640029,mp4a.40.2",RESOLUTION=960x540,FRAME-RATE=29.97,AUDIO="aud1"
c38c5a18-d5b1-4ce5-aaaa-eab6e3fe33c0/Manifestvideo_1285764.m3u8
#EXT-X-STREAM-INF:AVERAGE-BANDWIDTH=2091358,BANDWIDTH=4182716,CODECS="avc1.640029,mp4a.40.2",RESOLUTION=1280x720,FRAME-RATE=29.97,AUDIO="aud1"
c38c5a18-d5b1-4ce5-aaaa-eab6e3fe33c0/Manifestvideo_2091358.m3u8
#EXT-X-STREAM-INF:AVERAGE-BANDWIDTH=5000000,BANDWIDTH=10000000,CODECS="avc1.640028,mp4a.40.2",RESOLUTION=1920x1080,FRAME-RATE=29.97,AUDIO="aud1"
c38c5a18-d5b1-4ce5-aaaa-eab6e3fe33c0/Manifestvideo_5000000.m3u8
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aud1",LANGUAGE="en",NAME="English",AUTOSELECT=YES,DEFAULT=YES,CHANNELS="2",URI="c38c5a18-d5b1-4ce5-aaaa-eab6e3fe33c0/Manifestaudio_128000.m3u8"
```

**Versions:**

- RNGC Library Version: 3.3.0
- OS Version (if applicable): 13.5

**To Reproduce**

1. Use this as the `mediaUrl`: https://control.livingasone.com/ns/Manifest.m3u8
2. Cast device hangs

**Expected behavior**

Plays with no problem.

**Screenshots**

<img width="489" alt="Screen Shot 2020-07-14 at 11 43 11 AM" src="https://user-images.githubusercontent.com/2659478/87446400-411ffa80-c5c7-11ea-991f-a1055daa9fdb.png">

![IMG_0137](https://user-images.githubusercontent.com/2659478/87446480-58f77e80-c5c7-11ea-94f6-27d6fd94682c.jpg)

**Additional context**

Their web player streams fine ([LivingAsOne](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjugpeAi83qAhUPhuAKHf26AdwQFjAAegQIARAC&url=https%3A%2F%2Flivingasone.com%2F&usg=AOvVaw13GM2iXYOe7dgQadvPHAW7)) but I don't understand enough about Google Cast and HLS streams to know what could be causing the problem with this library.

**Comment by redreceipt** [comment]
Not even sure how to get visibility into errors happening on the cast device...

**Comment by d3vhound** [comment]
@redreceipt did you ever figure this out?

**Comment by redreceipt** [comment]
No I didn't. Haven't given it any more attention. Are you seeing similar issues?

**Comment by petrbela** [comment]
From what I've tested, it seems Chromecast has issues playing certain HLS streams. I haven't figured out what makes it not work but in any case, I think it's a problem with Chromecast itself and not with this library. I'll close this issue but feel free to post more if you find anything.
