### ISSUE TITLE
[iOS] What is the proper setup for React Native 0.60+ ?

### ISSUE THREAD

**Issue by curiousdustin** [react-native-google-cast/react-native-google-cast#212]
Should this module detect Chromecast devices while using auto linking in RN 0.60+?

When I let auto linking do it's thing, no devices are detected. I notice that the example app works properly, but it is using the no bluetooth version of the no bluetooth version.

My solution was to disable auto linking in `react-native.config.js` and add the no bluetooth pod to Podfile.

```pod 'react-native-google-cast/NoBluetooth', path: '../node_modules/react-native-google-cast/ios/'```

After this, my Chromecast is discovered. (But only after forcing the issue by calling `GoogleCast.showCastPicker()` 🤦 )

This should not be necessary, and the setup documentation is not clear for RN versions 0.60+.

**Versions:**
- RNGC Library Version: 3.3.0
- RN: 0.63

**Comment by petrbela** [comment]
RN 0.60+ is fully supported in v4. Please see the docs https://react-native-google-cast.github.io/docs/getting-started/installation

**Comment by Manouli** [comment]
@petrbela in the docs I couldn't find an example for AppDelegate.swift. Any ideas how I can add the setup bit there?

**Comment by petrbela** [comment]
@Manouli There's a Swift example on Google's site https://developers.google.com/cast/docs/ios_sender/integrate#initialize_the_cast_context. I'll add Swift instructions to our docs, too.
