### ISSUE TITLE
AppDelegate.m:41:38: Use of undeclared identifier 'GCKDiscoveryCriteria'

### ISSUE THREAD

**Issue by msal4** [react-native-google-cast/react-native-google-cast#214]
**Describe the bug**
When building the app for ios in release mode this error occurs.

**Versions:**
- RNGC Library Version: 3.3.0
- OS Version: 13.1

**To Reproduce**
Edit the schema and change the build configuration to release then run the app in the simulator or archive using generic ios device.

**Expected behavior**
To build successfully.

**Screenshots**
<img width="814" alt="Screen Shot 2020-09-09 at 3 25 09 PM" src="https://user-images.githubusercontent.com/30052233/92598670-c830dc80-f2b1-11ea-84c0-77d039b37969.png">

**Additional context**
The app runs fine using the debug schema. 
I wasted days with this issue with no solution, this is my last hope.

**Comment by loria33** [comment]
Hi ,line 30 has an #endif  ... check if you didn't import the GoogleCast into the flipper if Debug statement.

**Comment by msal4** [comment]
Thank you @loria33 👍 , I spent too much time looking to for a solution to the issue that I didn't even stop to look at the code for two minutes to find this stupid mistake.

**Comment by ateeq4112** [comment]
Thanks I have spent much time in this error.. Worked for me
