### ISSUE TITLE
Implementing Bob in the v4 breaks installation

### ISSUE THREAD

**Issue by jacob-israel-turner** [react-native-google-cast/react-native-google-cast#218]
**Describe the bug**
When installing on the v4 branch, I get a bunch of Typescript build errors.  This happens while the `bob build` command is running.

**Versions:**
- RNGC Library Version: v4 branch, latest commit.
- Android Version (if applicable): Not applicable, it's a build-step failure.
- OS Version (if applicable): Not applicable, it's a build-step failure.

**To Reproduce**
1. Freshly clone the repo
2. Run `yarn`
3. See the build step fail

**Expected behavior**
Build should succeed.

**Screenshots**
![Screen Shot 2020-09-15 at 3 55 15 PM](https://user-images.githubusercontent.com/8698364/93269274-e7c17c80-f76b-11ea-960d-45eeeaf5ea54.png)
![Screen Shot 2020-09-15 at 3 55 27 PM](https://user-images.githubusercontent.com/8698364/93269281-e98b4000-f76b-11ea-998a-50f9c6d26fb9.png)

**Additional context**
This may be signs of a global dependency on Typescript. This build step clearly relies on it, but it shouldn't even be building in the installation - it should only build if you're trying to use the playground.

**Comment by nickfujita** [comment]
Also experienced this today, glad I wasn't the only one!

**Comment by nickfujita** [comment]
@jacob-israel-turner Thanks for filing this bug in such detail. Were you able to find a workaround to allow the build to complete successfully?

**Comment by jacob-israel-turner** [comment]
Hi @nickfujita!  I was not able to find a workaround - I ended up forking the repo and reverting this commit, but I ran into a [couple](https://github.com/react-native-google-cast/react-native-google-cast/issues/219) other [issues](https://github.com/react-native-google-cast/react-native-google-cast/pull/217).  We are going to have to wait until these issues are resolved before implementing on our end.

If the contributors are not available to resolve these issues right now, I may take some time next week to dig a bit more - the `bob` issue specifically seems like it shouldn't be too difficult to resolve.

**Comment by younes200** [comment]
Hi @jacob-israel-turner, could you share please you workaround ? I'm facing the same issue to switch to v4.

**Comment by jacob-israel-turner** [comment]
@younes200 I never did get it working 100%.  I think I was close, but had to move onto other projects - I'm hoping to pick this up again in the next couple of weeks.

But the two things were:
1) Reverting the commit that introduced the Bob build step
2) [Pointing to the Podspec properly](https://github.com/react-native-google-cast/react-native-google-cast/pull/217) - this fix has since been merged upstream.

**Comment by petrbela** [comment]
This is now fixed in v4 beta.
