### ISSUE TITLE
Error building v4 on iOS

### ISSUE THREAD

**Issue by jacob-israel-turner** [react-native-google-cast/react-native-google-cast#219]
**Describe the bug**
I'm getting this error on iOS when building from branch `v4`:
```
/Users/jacob/code/freeplay/app/node_modules/react-native-google-cast/ios/RNGoogleCast/types/RCTConvert+GCKMediaInformation.m:92:30: Property 'contentURL' not found on object of type 'GCKMediaInformation *'; did you mean 'contentID'?
```

**Versions:**
- RNGC Library Version: v4 branch
- Android Version (if applicable): N/A
- OS Version (if applicable): N/A
- XCode Version (if applicable): 11.6

**To Reproduce**
1. Install v4 branch into React Native project
2. See build errors

**Expected behavior**
Build happens successfully.

**Screenshots**

**Additional context**
Since there's no documentation for installation on the v4 branch, I just kind of winged it.  Tried to follow the example by including what's `AppDelegate.m`, and followed the [docs from Google](https://developers.google.com/cast/docs/ios_sender/#ios_14) to make sure the proper permissions are setup, but still got this error.  Are there any other steps I missed?

We're implementing Cast for the first time in our project.  It sounds like v4 is mostly completed, and I'd rather use it than an older version.  But if it's incomplete, then I may need to just move back and use v3.

**Comment by petrbela** [comment]
This is now fixed in v4 beta.
