### ISSUE TITLE
iOS build fails when built with Detox and Xcode 12 beta

### ISSUE THREAD

**Issue by snowbillr** [react-native-google-cast/react-native-google-cast#220]
**Describe the bug**
Building my app for iOS fails when building with Detox and Xcode 12 beta.

**Versions:**
- RNGC Library Version: 3.3.0
- Android Version (if applicable): n/a
- OS Version (if applicable): 14? it's really just the build process that's affected, not at runtime

**To Reproduce**
1. Run `detox build` and use Xcode 12 beta to build the app

**Expected behavior**
Build succeeds.

**Actual behavior**
Build fails with this error message:

```
ld: building for iOS Simulator, but linking in dylib built for iOS, file '/my/path/to/ios/Pods/google-cast-sdk/GoogleCastSDK-ios-4.3.0/GoogleCast.framework/GoogleCast' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Additional context**

This appears to be a problem with the `google-cast-sdk` pod. I understand that we are required to use 4.3.0 to avoid the dynamic linking bug during the build, but I am on 4.3.0 and seeing this error. I believe it has something to do with iOS 14. The `google-cast-sdk` pod released an update a couple days ago for iOS 14 - see https://developers.google.com/cast/docs/ios_sender/ios_permissions_changes#ios_14. They are recommending all users start using 4.5.0, but I'm unable to do so with the requirements of this project.

Any advice on how to proceed would be great here. I'm no expert when it comes to iOS builds and am not sure where to go next. Thanks!

**Comment by petrbela** [comment]
Hey, I still need to upgrade to iOS 14 myself (planning to do that for v4) but from your description, it seems the problem is Xcode now also tries to compile the library for `arm64` architecture which is Apple's new ARM-based platform (what they call Apple Silicon). Does Xcode have a setting to disable it for now and just create a standard x64 (Intel-based) build?

**Comment by snowbillr** [comment]
There's something new with [iOS apps being able to be run on MacOS](https://www.engadget.com/ios-apps-arm-powered-macs-192046502.html#:~:text=According%20to%20Apple%2C%20since%20the,Mac%20OS%20without%20any%20modification.), so I wonder if that's contributing to the problem!

**Comment by petrbela** [comment]
I think that shouldn't matter; iOS apps aren't really changing, it's macOS that's getting compatible. I'm installing Xcode 12 now and will test this today.

**Comment by snowbillr** [comment]
Thanks a ton!

**Comment by snowbillr** [comment]
Quick bump on this, do you have any new information?

**Comment by vinnyjth** [comment]
I can reproduce this when building for release on Xcode 12 when targeting the Simulator. I can build release archives fine, and I can build debug Simulator builds fine.

**Comment by snowbillr** [comment]
Interesting. So it seems to be an issue while building for a release for the Simulator, but not for other targets? How bizarre.

**Comment by snowbillr** [comment]
Found a fix for it: https://stackoverflow.com/a/63955114
