### ISSUE TITLE
[iOS] How can receive custom message from cast receiver in v4?

### ISSUE THREAD

**Issue by merongmerongmerong** [react-native-google-cast/react-native-google-cast#223]
### Versions

- Xcode 12
- react-native-google-cast@4.0.0-pre.1
- react-native@0.63.2

### Issue

In v3, I can use `GoogleCast.EventEmitter.addListener` to receive message from the receiver

```javascript
GoogleCast.EventEmitter.addListener(GoogleCast.CHANNEL_MESSAGE_RECEIVED, callback)
```

In v4, `GoogleCast.EventEmitter` is no longer exported and There is new `CastSession` class and it has a `onMessage` method. so I tried

```javascript
const castSession = await GoogleCast.getCurrentCastSession()
castSession?.onMessage(namespace, handler)
```

and got `TypeError: Native.getCurrentCastSession is not a function` error from

`SessionManager.ts`
```javascript
export default class SessionManager {
  getCurrentCastSession(): Promise<CastSession> {
    return Native.getCurrentCastSession() // <<<<--- here :D
  }
}
```

**Comment by petrbela** [comment]
This still needs to be ported to v4. In fact, it's one of the few remaining issues before an official v4 release.
