### ISSUE TITLE
Cast button ios 14 detection problem

### ISSUE THREAD

**Issue by jonathanm-tkf** [react-native-google-cast/react-native-google-cast#225]
**Describe the bug**
I have the problem after updating to version 4.5.0 because I follow the steps in the following link

(https://developers.google.com/cast/docs/ios_sender?hl=es)https://developers.google.com/cast/docs/ios_sender?hl=es

but I am not achieving autodetection of the button, could you help me with an example of Objective C native code, because I do not know the technology.

**Versions:**
- RNGC Library Version: 3.3.0
- OS Version 14.0

Thanks for your help

**Comment by phvillegas** [comment]
I have the same problem, I can see the button but it doesn't detect the device.

It works in the simulator, but on the iPhone I can't see the chromecast

**Versions**:
- iOS 14
- RNGoogleCast Library Version: 3.3.0

**Comment by nbennink** [comment]
#221 is related. Cast SDK 4.5.0 seems to fix this.

**Comment by nenjamin2405** [comment]
I already updated to the latest version of react-native-google-cast 3.4.0 and I can see in the podfile.lock it's showing the latest SDK of Google Cast
```
- google-cast-sdk-no-bluetooth (4.5.0):
  - google-cast-sdk-no-bluetooth/Core (= 4.5.0)
  - GTMSessionFetcher/Core (~> 1.0)
  - Protobuf (~> 3.12)
- google-cast-sdk-no-bluetooth/Core (4.5.0):
  - GTMSessionFetcher/Core (~> 1.0)
  - Protobuf (~> 3.12)
- react-native-google-cast/NoBluetooth (3.4.0):
  - google-cast-sdk-no-bluetooth
  - React
  - react-native-google-cast/RNGoogleCast
- react-native-google-cast/RNGoogleCast (3.4.0):
  - React
- react-native-google-cast/NoBluetooth (from `../node_modules/react-native-google-cast/ios/`)
- react-native-google-cast:
  :path: "../node_modules/react-native-google-cast/ios/"
```

The function works fine on emulator using iOS 12.0 and 14.0, but when I test it on real device (using iOS 14.1), when the app is opened for the first time, the Permission Popup for Local Network (below image 1) is showed, and the cast icon is showed correctly, when I tap on the cast icon, it shows the popup (below image 2), when I tap ok, then the cast button will be disappeared from that moment and I cannot see it again afterward. 

**Image 1**
![image](https://user-images.githubusercontent.com/16648769/98325226-e0f30f80-2020-11eb-9b4b-2b845f1abfc6.png)

**Image 2**
![image](https://user-images.githubusercontent.com/16648769/98325213-d8023e00-2020-11eb-92bb-087cb5ed38c2.png)

Do you guys know what is the issue in this case :(

**Comment by istvan-szilagyi** [comment]
@nenjamin2405 have you tried adding NSBonjourServices & NSLocalNetworkUsageDescription to your Info.plist?

Like mentioned in the documentation: https://developers.google.com/cast/docs/ios_sender/#xcode_10

**Comment by jedashford** [comment]
Adding the below to our info.plist file. This fixed chromecast and amazon fling detection.

```
  <key>NSLocalNetworkUsageDescription</key>
  <string>[MY APP NAME] uses the local network to discover Cast-enabled devices on your WiFi
  network.</string>
	<key>NSBonjourServices</key>
  <array>
    <string>_googlecast._tcp</string>
    <string>_[ID OF YOUR CUSTOM RECEIVER IF YOU HAVE ONE]._googlecast._tcp</string>
    <string>_amzn-wplay._tcp</string>
  </array>
```

**Comment by istvan-szilagyi** [comment]
@jedashford that's exactly what I said 😅

**Comment by jedashford** [comment]
> @jedashford that's exactly what I said 😅

Yup! That helped me. I just gave more detailed specifics that someone can copy and paste. Thanks for the heads up.

**Comment by petrbela** [comment]
This is now documented in the [new docs](https://react-native-google-cast.github.io/docs/getting-started/setup).
