### ISSUE TITLE
Support Cast state event

### ISSUE THREAD

**Issue by Stenbaek** [react-native-google-cast/react-native-google-cast#228]
I would love the possibility to listen to an event for the cast state changing, to know when a cast device is available, and when it is not. As of now, the CastButton is shown or hidden dynamically, depending on the cast state. I would like to be able to change my UI depending on the current state, e.g. removing parent component showing the button.

**Comment by ivanszhuravlev** [comment]
Totally agree with @Stenbaek, that would be awesome

**Comment by petrbela** [comment]
This is now implemented in v4. You can either use an [event](https://react-native-google-cast.github.io/docs/guides/events#cast-state-events) or a [hook](https://react-native-google-cast.github.io/docs/guides/hooks#cast-state-hooks).
