### ISSUE TITLE
how to cast image by using this npm?

### ISSUE THREAD

**Issue by brandtiwari007** [react-native-google-cast/react-native-google-cast#229]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by petrbela** [comment]
You may pass a url to an image, along with a correct contentType, to [loadMedia](https://react-native-google-cast.github.io/docs/api/classes/remotemediaclient#loadmedia):

```ts
const client = useClient()

client.loadMedia({
  mediaInfo: {
    contentUrl:
      'https://sample-videos.com/img/Sample-png-image-500kb.png',
    contentType: 'image/png',
  },
})
```

Note that this code example uses the upcoming v4, which is currently in beta, but it works similarly in v3.
