### ISSUE TITLE
Casting a .ts stream fails

### ISSUE THREAD

**Issue by cocool97** [react-native-google-cast/react-native-google-cast#231]
**Bug description**
I'm using this library to cast an IPTV stream to my chromecast. 
The stream I receive is encoded as .ts (Content-Type: **"video/m2ts"**), and the casts from my application fails with this format. It works perfectly if I transcode this stream as mp4 (but seems to be hard to do on-the-fly with react native).

**Versions:**
- RNGC Library Version: master branch
- Android Version (if applicable): Android 9

**To Reproduce**
Here is my (very simple) code : 
```
GoogleCast.castMedia({
        mediaUrl: "<Stream URL>" // Stream media video uri
        title: "Test stream", // Media main title
        imageUrl: "<Image URL>",
        streamDuration: 1600, // Stream duration in seconds,
        isLive: true
      })
```

**Comment by petrbela** [comment]
Hey, for (live) streaming, cast devices support [MPEG-DASH, SmoothStreaming, and HLS](https://developers.google.com/cast/docs/media#delivery_methods_and_adaptive_streaming_protocols). The most common format, HLS, uses `.ts` files as the individual video chunks but you need to provide a `.m3u8` file that provides the metadata about how and when these `.ts` chunks should be sent. Does your stream provide such file?. You'd pass that `.m3u8` URL as `mediaUrl`, and the player should do the rest.

**Comment by cocool97** [comment]
I do not have such a ```.m3u8``` file, but I do have a ```.m3u```.
Isn't it possible to provide the ```ts``` stream directly to the ```castMedia``` method by providing a proper ```contentType``` ?

**Comment by petrbela** [comment]
`.m3u` is an alternative name of `.m3u8` (similar to `jpg`/`jpeg`).

You cannot use `.ts` directly because `.ts` is a single video file (typically 2-5 seconds long), and the stream consists of many `.ts` files delivered as the stream progresses. (In theory, you could perhaps provide a `.ts` file but that would only play that single chunk. Think of every `.ts` chunk as a short standalone mp4 file that is being downloaded and played separately, in the order given by the `m3u8` manifest.)

**Comment by cocool97** [comment]
Do you know if it's possible to convert a ```m3u``` playlist to a ```m3u8``` ? 
Do you have a working m3u8 template with such a ```ts``` stream ?

**Comment by petrbela** [comment]
m3u and m3u8 is the same thing. There's no need to convert.

You can search Google for sample m3u8 files, there should be plenty.

**Comment by petrbela** [comment]
There's a similar discussion in #58, closing this one.
