### ISSUE TITLE
Disconnecting causes a crash

### ISSUE THREAD

**Issue by jlandrum** [react-native-google-cast/react-native-google-cast#232]
**Describe the bug**
When disconnecting from Chromecast, the SDK causes a crash.

**Versions:**
- RNGC Library Version: 4.0.0-beta.1
- OS Version: 14.2

**To Reproduce**
1. Begin casting media
2. Bring up the controls screen
3. Select "Stop Casting"

**Expected behavior**
No crash

If you can point me in the direction of where any disconnection handlers may be, I could give it a shot to fix this issue myself.

**Comment by Bang9** [comment]
+1

**Comment by uttrasey** [comment]
Seeing this too
