### ISSUE TITLE
Rewind/Forward buttons are always disabled in expanded controls

### ISSUE THREAD

**Issue by goncalo-assuncao** [react-native-google-cast/react-native-google-cast#235]
**Describe the bug**
The forward and rewind buttons are always disabled in live stream

**Versions:**
- RNGC Library Version: 3.4.0

**To Reproduce**
1 - Connect the sender to the receiver
2 - Start playback
3 - Launch expanded controls
4 - Check forward/rewind buttons 

**Expected behavior**
Buttons to be enabled and rewind/forward the stream if clicked

**Comment by goncalo-assuncao** [comment]
Any support on this issue @petrbela ?

**Comment by petrbela** [comment]
The expanded controls are part of the Cast SDK so you might search for general Google Cast iOS/Android answers as I believe it's not specific to this React Native wrapper library.

**Comment by goncalo-assuncao** [comment]
@petrbela  the issue was in the receiver code.

Cheers
