### ISSUE TITLE
Events on V4 branch

### ISSUE THREAD

**Issue by neoassyrian** [react-native-google-cast/react-native-google-cast#237]
hi @petrbela 

Is the Events finalised in the V4 branch? I have tried to use the onMediaStatusUpdated but it was not working. 
Also the useMediaStatus is not firing when media is updated.

**Comment by petrbela** [comment]
The native listeners are not currently being initialized. I'll hook them up probably today or tomorrow.

**Comment by neoassyrian** [comment]
Thanks for that. 
I've also noticed that these don't work. They might be all related.

client.getMediaStatus returns an error: 
 WARN     Possible Unhandled Promise Rejection (id: 12):
Error: Attempt to get length of null array
Error: Attempt to get length of null array
    at promiseMethodWrapper (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:4976:45)
    at getMediaStatus (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:152466:37)

useCastState does not get fired

it would be good if there is a hook to get the mediaStatus when changed. It should cover most needed cases such as getting the media metadata, or when the player is playing/buffering/etc...

**Comment by neoassyrian** [comment]
Hi @petrbela,
Any progress on this? 😊 

Thanks.

**Comment by neoassyrian** [comment]
@petrbela can you push this to NPM as beta5 please.

**Comment by neoassyrian** [comment]
@petrbela is this implemented for iOS?

**Comment by petrbela** [comment]
Oh it works but it's nested under an extra key. I'll make a fix.

**Comment by neoassyrian** [comment]
> Oh it works but it's nested under an extra key. I'll push a fix.

ok, please let me know when it is done and I can test it out.
Thanks
