### ISSUE TITLE
Queue action buttons on receiver app and notification V4

### ISSUE THREAD

**Issue by neoassyrian** [react-native-google-cast/react-native-google-cast#238]
Hi, 
When adding items to the queue, is the notification supposed to show the SKIP next button together with the play/pause and stop buttons? I can see that in the code, but it doesn't seem to show up. 
I can see this set in the GoogleCastOptionsProvider but it is not displayed. 
```
...
 @Override
  public CastOptions getCastOptions(Context context) {
    NotificationOptions notificationOptions =
        new NotificationOptions.Builder()
            .setActions(
                Arrays.asList(MediaIntentReceiver.ACTION_SKIP_NEXT,
                              MediaIntentReceiver.ACTION_TOGGLE_PLAYBACK,
                              MediaIntentReceiver.ACTION_STOP_CASTING),
                new int[] {0, 1, 2})
            .setTargetActivityClassName(
                RNGCExpandedControllerActivity.class.getName())
            .build();
...
```

Also, when loading items to the queue, is the receiever app (e.g. TV or chromecast) supposed to display the next and previous buttons? 

I have also tried to set the queue type (in the queueData field) to be a "Playlist" 
https://react-native-google-cast.github.io/docs/api/enums/mediaqueuetype

**Comment by petrbela** [comment]
The notification buttons should be working properly in the latest version.

> Also, when loading items to the queue, is the receiever app (e.g. TV or chromecast) supposed to display the next and previous buttons?
I don't think it does, or at least I haven't really seen it. Either way, I don't think it's configurable by the sender library.

> I have also tried to set the queue type (in the queueData field) to be a "Playlist"
I don't think the queue type matters, it's just meta.
