### ISSUE TITLE
Couldn't access the SessionManager 

### ISSUE THREAD

**Issue by sujithln** [react-native-google-cast/react-native-google-cast#239]
i Can not access the session related Events like onSessionStarted and onSessionEnded.

**I have tried the following code but i couldn't access getSessionManager from GoogleCast**

import GoogleCast from 'react-native-google-cast'

const sessionManager = GoogleCast.getSessionManager()

const listener = sessionManager.onSessionStarted((session) => {
  /* callback */
})

**Versions:**
"react": "16.13.1",
"react-native": "0.63.2",
"react-native-google-cast": "^4.0.0-beta.4",

Inside the Pod file:
  pod 'react-native-google-cast/NoBluetooth', path: '../node_modules/react-native-google-cast/ios'
I have tried 'google-cast-sdk-no-bluetooth' in pod file wit the version '4.5.0' and '4.5.3'

**Please help. Thanks in advance.**

**Comment by petrbela** [comment]
The documentation is incorrect, here's how to get `SessionManager`:

```
import { SessionManager } from 'react-native-google-cast'

const sessionManager = new SessionManager()

const listener = sessionManager.onSessionStarted((session) => {
/* callback */
})
```

(also, I think the other events are current broken #237; I'll push a fix this weekend)

**Comment by sujithln** [comment]
I couldn't find the SessionManager under 'react-native-google-cast'. They haven't exported that way i think. I some how managed to import like this:

 import { SessionManager } from 'react-native-google-cast'
const sessionManager = new SessionManager()

**onSessionStarted**  event worked for me. But if i listen to any of the events related to sessionManager, in IOS, on clicking the **stop casting** from the cast control overlay crashing the app, only in ios.  Thanks for the quick response @petrbela , i'll be waiting for session events related fix. :)

**Comment by petrbela** [comment]
The documentation has been updated.
