### ISSUE TITLE
Cannot resolve symbol 'CastContext'

### ISSUE THREAD

**Issue by lukepighetti** [react-native-google-cast/react-native-google-cast#240]
**Describe the bug**
When trying to setup the `react-native-google-cast` plugin, import symbols are not resolving.

**Versions:**
- RNGC Library Version: "^4.0.0-beta.4"
- Android Version (if applicable): buildToolsVersion = "29.0.2"

**To Reproduce**
1. Generate new project
2. Try to follow Setup guide https://react-native-google-cast.github.io/docs/getting-started/setup

On `import com.google.android.gms.cast.framework.CastContext;` I get the error `Cannot resolve symbol 'CastContext'`

**Expected behavior**
Expect it to work

**Screenshots**
<img width="1070" alt="Screen Shot 2020-12-07 at 7 03 04 PM" src="https://user-images.githubusercontent.com/666539/101419846-e1502600-38be-11eb-9055-29d44153dc22.png">

**Additional context**
N/A

**Comment by petrbela** [comment]
Hmm that should be pulled in as a transitive dependency of this package. Can you try resyncing gradle (File > Sync Project with Gradle Files)?

**Comment by uttrasey** [comment]
I have this same issue, I can see CastContext in the external library dependencies but for some reason it can't be resolved from MainActivity.

![Screenshot 2020-12-08 at 10 01 55](https://user-images.githubusercontent.com/1884388/101469323-83faba00-393c-11eb-9c03-fbe81386f94b.png)

**Comment by uttrasey** [comment]
> I have this same issue, I can see CastContext in the external library dependencies but for some reason it can't be resolved from MainActivity.
> 
> ![Screenshot 2020-12-08 at 10 01 55](https://user-images.githubusercontent.com/1884388/101469323-83faba00-393c-11eb-9c03-fbe81386f94b.png)

Just to follow up that the screenshot was not v4 but on v4 the same problem happens for me but version of `cast-framework` and `cast` is @v19

**Comment by uttrasey** [comment]
For what it's worth I got this working. AndroidStudio tries to be useful and ask's if you want to add the cast library which is the wrong one.

I added this to `android/app/build.gradle`

```
dependencies {
    implementation 'com.google.android.gms:play-services-cast-framework:19.0.0'
}
```

**Comment by petrbela** [comment]
Yes 19.0.0 is the latest one. I wonder why it downloaded 16.1.2 though. Did you set `castFrameworkVersion` as described in [step 4 of the installation](https://react-native-google-cast.github.io/docs/getting-started/installation#android)?

**Comment by uttrasey** [comment]
> Yes 19.0.0 is the latest one. I wonder why it downloaded 16.1.2 though. Did you set `castFrameworkVersion` as described in [step 4 of the installation](https://react-native-google-cast.github.io/docs/getting-started/installation#android)?

yeh sorry the 16.1.2 was a screenshot from non v4 branch. On v4 I get the right one pulled into External dependencies (19.0.0) but as per @lukepighetti 's original description... it's not available on the classpath despite appearing in External deps.

**Comment by uttrasey** [comment]
> Yes 19.0.0 is the latest one. I wonder why it downloaded 16.1.2 though. Did you set `castFrameworkVersion` as described in [step 4 of the installation](https://react-native-google-cast.github.io/docs/getting-started/installation#android)?

Also, step 4 sounds very optional to me. 

> By default, the react-native-google-cast package automatically loads the latest version (+) of the Cast SDK and support libraries as its dependencies. **To use a specific version, set it in the root android/build.gradle:**

**Comment by lukepighetti** [comment]
The docs don't seem to reflect the situation on the ground, or perhaps they make an assumption about the knowledge of the reader.

```
  <meta-data
    android:name="com.google.android.gms.cast.framework.OPTIONS_PROVIDER_CLASS_NAME"
    android:value="com.reactnative.googlecast.GoogleCastOptionsProvider" />
```

The docs say to add this to `AndroidManifest.xml`, but a fresh RN project creates two. One in `app/src/main` the other in `app/src/dev`. Do I add it to both?

**Comment by lukepighetti** [comment]
> Also, step 4 sounds very optional to me.

I agree that most of the steps on that page seemed optional, unless you were using < 0.59 RN, and possibly more optional than that.

**Comment by petrbela** [comment]
> Please forgive me as I work through this again today.
> 
> The docs don't seem to reflect the situation on the ground, or perhaps they make an assumption about the knowledge of the reader.
> 
> ```
>   <meta-data
>     android:name="com.google.android.gms.cast.framework.OPTIONS_PROVIDER_CLASS_NAME"
>     android:value="com.reactnative.googlecast.GoogleCastOptionsProvider" />
> ```
> 
> The docs say to add this to `AndroidManifest.xml`, but a fresh RN project creates two. One in `app/src/main` the other in `app/src/debug`. Do I add it to both? Does it go inside the `manifest` tag or the `application` tag?

It should go to the one in `app/src/main`. `app/src/debug` adds additional attributes/permissions specific to development and is merged into the main one when building the app in debug mode. I can clarify that in the docs. (Btw I understand your confusion but this is a general Android rule; the documentation for this library can't possibly cover all of the platform specifics :))

**Comment by petrbela** [comment]
> > Also, step 4 sounds very optional to me.
> 
> I agree that it sounds like most of the steps on that page are specific to < 0.59 RN, which doesn't apply to me, and step 4 seemed totally optional.
> 
> I wonder if this is going to turn into a setup/first-hour documentation issue.

In theory, step 4 should be optional. If you don't specify it, `castFrameworkVersion` defaults to `+` which fetches the latest version (19.0.0). However, I'm not sure why the compiler doesn't see it, as you're describing. I generally test the setup instructions on a fresh project and haven't run into this before.

**Comment by lukepighetti** [comment]
> It should go to the one in `app/src/main`. `app/src/debug` adds additional attributes/permissions specific to development and is merged into the main one when building the app in debug mode. I can clarify that in the docs. (Btw I understand your confusion but this is a general Android rule; the documentation for this library can't possibly cover all of the platform specifics :))

Totally get it, there are tricks in technical documentation though.

> Add the snippet above to your main `AndroidManifest.xml`

**Comment by lukepighetti** [comment]
Still can't get this to show up. Pushing up a MVCE here: https://github.com/lukepighetti/react-native-google-cast-mvce

<img width="925" alt="Screen Shot 2020-12-08 at 1 31 35 PM" src="https://user-images.githubusercontent.com/666539/101525746-b2d35900-3959-11eb-92ed-88e30d7be198.png">

**Comment by lukepighetti** [comment]
Adjusting build.gradle so it contains this doesn't resolve the issue:

```
    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 16
        compileSdkVersion = 29
        targetSdkVersion = 29
        castFrameworkVersion = "19.0.0" // <-- Cast SDK version
    }
```

**Comment by lukepighetti** [comment]
I added this to `android/app/build.gradle` and it didn't resolve any issues.

```
dependencies {
    implementation 'com.google.android.gms:play-services-cast-framework:19.0.0'
}
```

**Comment by lukepighetti** [comment]
Trying with `3.4.0`, it looks like https://github.com/react-native-google-cast/react-native-google-cast is missing step 4 from https://react-native-google-cast.github.io/docs/getting-started/installation#android

**Comment by lukepighetti** [comment]
The next button on the documentation doesn't work on this page: https://react-native-google-cast.github.io/docs/getting-started/setup#android

**Comment by lukepighetti** [comment]
Got it working on next, I had to do everything in the `<0.59` section even though I'm on `0.63.4`

**Comment by petrbela** [comment]
You guys were right, the cast-framework dependency needs to be added to the project in order to be used in MainActivity (looks like having it as a transitive dependency is not enough). I'm updating the documentation to make it clearer. Thanks for your help!
