### ISSUE TITLE
Programatically disconnect from device

### ISSUE THREAD

**Issue by uttrasey** [react-native-google-cast/react-native-google-cast#241]
**Is your feature request related to a problem? Please describe.**

I would like to be able to disconnect from casting device via unmount of a RN screen

**Describe the solution you'd like**

An API method on the right API object so I can do it via hooks.

**Describe alternatives you've considered**

I'm not sure how else to do this.

**Additional context**

**Comment by petrbela** [comment]
This should be doable using `endSession` on SessionManager ([Android](https://developers.google.com/android/reference/com/google/android/gms/cast/framework/SessionManager#endCurrentSession(boolean)) / [iOS](https://developers.google.com/cast/docs/reference/ios/interface_g_c_k_session_manager#a25fb07952abae96d2a10fd9a479ca4e3)). Feel free to submit a pull request, or I might probably get to it later this week.

**Comment by uttrasey** [comment]
@petrbela I've had a stab at this https://github.com/react-native-google-cast/react-native-google-cast/pull/242

Let me know what you think and I can tidy it up
