### ISSUE TITLE
useCastState doesn't reflect the actual cast state

### ISSUE THREAD

**Issue by lukepighetti** [react-native-google-cast/react-native-google-cast#243]
If you `useCastState` and it's `disconnected` then you connect to a Chromecast device it won't update to reflect the new status. However, if you restart the app an event will fire that it's `connected`. 

In short, useCastState isn't actually updating to match the current state.

I am wrapping a class component with a functional component to pass the hooks through, but I don't think this is problematic.

```javascript
const PlayView = ({ ...props }) => {
  const castState = useCastState();
  const castSession = useCastSession();
  const castClient = useRemoteMediaClient();

  return <_PlayView castService={{ castState, castSession, castClient }} {...props} />;
};
```

I'm getting better results by using `castClient !== null`

**Comment by neoassyrian** [comment]
I think this is related to
https://github.com/react-native-google-cast/react-native-google-cast/issues/237
