### ISSUE TITLE
Update tags to remove "v" prefix

### ISSUE THREAD

**Issue by nickfujita** [react-native-google-cast/react-native-google-cast#246]
**Describe the bug**
The "v" prefix on tag/release version starting with 3.2.1 is out of sync with version in podspec. Now that react-native uses CocoaPods, there are some cases when a native iOS app using a react-native component tries to install react-native-google-cast as a CocoaPod, but fails since it's [looking for tag](https://github.com/react-native-google-cast/react-native-google-cast/blob/master/ios/react-native-google-cast.podspec#L14) `3.4.0` listed in the `podspec` file, but the tags are prefixed with "v", so it's unable to resolve the dependency.

Furthermore, the `podspec` should be migrated to the root directory, since this is where [CocoaPods expects](https://guides.cocoapods.org/using/the-podfile.html#:~:text=The%20podspec%20file%20is%20expected,outlined%20in%20the%20sections%20below.) `podspec` files to be located. Without having it in the root, CocoaPods does not recognize this as a valid pod. I've created a PR for this small change [here](https://github.com/react-native-google-cast/react-native-google-cast/pull/245)

**Versions:**
- 3.2.1 and newer

**Comment by petrbela** [comment]
That's a good point. I'll fix it going forward!
