### ISSUE TITLE
Error 'No CastSession!' when disconnecting chromecast V4

### ISSUE THREAD

**Issue by neoassyrian** [react-native-google-cast/react-native-google-cast#251]
I'm getting an error when disconnecting the chromcast session using the CastButton

it is throwing the exception from this call

```
protected With<RemoteMediaClient> with = new With<RemoteMediaClient>() {
    @Override
    protected RemoteMediaClient getX() {
      final CastSession castSession = CastContext.getSharedInstance(getReactApplicationContext())
        .getSessionManager()
        .getCurrentCastSession();

      if (castSession == null) {
        throw new IllegalStateException(("No castSession!"));
      }

      final RemoteMediaClient client = castSession.getRemoteMediaClient();

      if (client == null) {
        throw new IllegalStateException(("No remoteMediaClient!"));
      }

      return client;
    }
```

Is that normal? If so, how do I catch it? 
I'm not getting why is this called when disconnecting the chromecast session

This is on Android. I haven't tested on iOS. 
Also using the latest beta V4 build (beta 5)

**Comment by petrbela** [comment]
Ahh, sorry, it looks like I introduced an error in the last version. I'll release a new version today.

**Comment by petrbela** [comment]
Fixed in beta.6
