### ISSUE TITLE
cast notification not displaying "next" button when queue of items is loaded V4 (Android)

### ISSUE THREAD

**Issue by neoassyrian** [react-native-google-cast/react-native-google-cast#252]
Hi @petrbela 
The notification does not display the next button when items are added to the queue.

**Comment by petrbela** [comment]
The compact notification can only show two buttons, specified as indices in https://github.com/react-native-google-cast/react-native-google-cast/blob/ca56a242e057b3d0aaabe439d02b886dc200d934/android/src/main/java/com/reactnative/googlecast/GoogleCastOptionsProvider.java#L29

The full list of action buttons is only displayed when you expand the notification.

I'm not sure if there's a better way to do it than it is now. Do you have an example of an app that does this in a better way?

**Comment by petrbela** [comment]
Btw the action buttons can be adjusted dynamically based on whether you're playing a single item or multiple but I'm still not sure what should be the two primary buttons then. I guess play/pause and next, with the stop button moved to the expanded view?

**Comment by neoassyrian** [comment]
Probably the react-native-track-player implementation is the best as an example.

By default it displays the play/pause and next. 
Then when expanded, it displays almost all of them, previous, play/paus, next and stop. 
I think they are also configurable when setting up the player. 

You are right in 
Display play/pause and next for compact view
Display play/pause, next and stop button when expanded. 

Having said that, I did try to add the indecies to the configuration but the notification was still not displaying the next button when loading a queue.

**Comment by neoassyrian** [comment]
Here is the documentation for the track player. It would be awesome if the configuration gets matched (overall)
https://react-native-track-player.js.org/documentation/

That way, media applications can switch between the track player and Google casting. 

Personally think the 2 plugins should be combined into one. 😊

**Comment by neoassyrian** [comment]
> The compact notification can only show two buttons, specified as indices in
> 
> https://github.com/react-native-google-cast/react-native-google-cast/blob/ca56a242e057b3d0aaabe439d02b886dc200d934/android/src/main/java/com/reactnative/googlecast/GoogleCastOptionsProvider.java#L29
> 
> The full list of action buttons is only displayed when you expand the notification.
> 
> I'm not sure if there's a better way to do it than it is now. Do you have an example of an app that handles this more optimally?

The next button is not getting displayed on the expanded notification for sure. 
I'm using a custom OptionsProvider, not sure if that's the issue.

**Comment by petrbela** [comment]
> I'm using a custom OptionsProvider, not sure if that's the issue.

That's certainly the issue. You'll need to add the actions when initializing the options. I'll try to come up with a way that allows you to pass a custom app id without having to reimplement the provider.

**Comment by petrbela** [comment]
> Here is the documentation for the track player. It would be awesome if the configuration gets matched (overall)
> [react-native-track-player.js.org/documentation](https://react-native-track-player.js.org/documentation/)
> 
> That way, media applications can switch between the track player and Google casting.
> 
> Personally think the 2 plugins should be combined into one. 😊

I'll take a look at it. Not sure about combining as the libraries have different goals but maybe there's some integration that could be improved.

**Comment by neoassyrian** [comment]
> > Here is the documentation for the track player. It would be awesome if the configuration gets matched (overall)
> > [react-native-track-player.js.org/documentation](https://react-native-track-player.js.org/documentation/)
> > That way, media applications can switch between the track player and Google casting.
> > Personally think the 2 plugins should be combined into one. 😊
> 
> I'll take a look at it. Not sure about combining as the libraries have different goals but maybe there's some integration that could be improved.

Yes of course, combining them is a whole new project. 
The current v4 branch is a step closer to the track player plugin.
