### ISSUE TITLE
Cast Button not visible [Android]

### ISSUE THREAD

**Issue by Manouli** [react-native-google-cast/react-native-google-cast#253]
**Describe the bug**
After installing the package it seems that the CastButton isn't showing at all. Tried versions 3 and 4. I am running the app on a physical device but I still can't see it. When I run `GoogleCast.showCastPicker();` I can see the modal say searching... 
Any ideas as to why the button isn't showing? 

**Versions:**
- RNGC Library Version: 3.4.1
- Android Version (if applicable): 29.0.0

**Comment by petrbela** [comment]
Hey, I'd recommending using v4 which will be coming out of beta in a few days. Then, make sure you initialize the CastContext in your MainApplication as described in [step 3 of Setup](https://react-native-google-cast.github.io/docs/getting-started/setup#android)

**Comment by Manouli** [comment]
@petrbela Could it be that we are using :

`android.useAndroidX=true`
`android.enableJetifier=true`

I have just installed the v4 and it seems that the CastButton gets added listens to the width and height but it's not visible. Its almost like an empty View that takes space.

**Comment by petrbela** [comment]
The two settings are correct.

Can you see what `useCastState()` returns? If no devices are available, the Cast button remains hidden.

**Comment by Manouli** [comment]
@petrbela indeed that returns `noDevicesAvailable` So if that is the case the button is always hidden then. Sorry I must have completely missed this.

**Comment by petrbela** [comment]
If you have a Cast device on your network, I'd check if other apps (e.g. Google Home) can see it. If yes then I'd double-check that you followed all the setup steps, specifically adding CastContext to MainApplication. If even after that you can't see any device, try closing (home button, not killing it) and reopening the app. If that doesn't help either, then I don't know 😆

**Comment by Manouli** [comment]
Ok I will give these steps a go and I will update the ticket ;)

**Comment by Manouli** [comment]
@petrbela Closing this. Works as expected 🥳
