### ISSUE TITLE
Add media events to v4 (MediaProgressUpdated, MediaPlaybackStarted, MediaPlaybackEnded, etc.)

### ISSUE THREAD

**Issue by maliotti** [react-native-google-cast/react-native-google-cast#257]
**Is your feature request related to a problem? Please describe.**
I would like to update the scrubber position on my app with the `streamPosition` while casting. In v4, there doesn't appear to be a way to get media progress updates. While the `MediaStatus` does indeed contain the `streamPosition`, it appears to only be updated when the `playerState` changes (i.e. `PLAYING`, `PAUSED`, etc.).

**Describe the solution you'd like**
It would be nice to have something similar to what was available in v3, where we could listen specifically for when the media progress was updated (`GoogleCast.EventEmitter.addListener(GoogleCast.MEDIA_PROGRESS_UPDATED, ({ mediaProgress }) => {},)`), as well as other media events (i.e. `MEDIA_PLAYBACK_STARTED`, `MEDIA_PLAYBACK_ENDED`, etc.).

**Describe alternatives you've considered**
If the `mediaStatus` simply updated when the streaming position changed, we could handle it in `getMediaStatus` and/or `onMediaStatusUpdated`. Right now, this doesn't work as the `streamPosition` does not update unless the `playerState` changes. (I've tested this using a timer to call `getMediaStatus` every second, and the `streamPosition` does not change.)

**Comment by petrbela** [comment]
Yes, these are planned to be added to v4. The frequency of native `progressUpdated` callbacks differs on Android (which triggers it roughly every second) vs iOS (which doesn't have the callback at all and instead updates `mediaStatus` once every ~10 seconds) so we'll need to find a consistent way.

**Comment by maliotti** [comment]
@petrbela Awesome! Thanks for such a quick response. Any idea on when this might be implemented?

**Comment by petrbela** [comment]
@maliotti I'm hoping to finally release v4, along with this feature, around Christmas. 🎄

**Comment by maliotti** [comment]
@petrbela That would be awesome! Thanks again for all the great work so far! Will be checking back frequently.
