### ISSUE TITLE
No Listener when coming from other app  

### ISSUE THREAD

**Issue by farhanmeo** [react-native-google-cast/react-native-google-cast#259]
**Describe the bug**
RNGC is working perfectly so far, one thing I faced while testing my app that I am casting an audio file which is working properly then I switch to youtube and cast a video from there so then that video is being cast from youtube here is where the issue comes now when I go back to  my app it show playing in background while that audio is not being played there so there must be a listener when some other app started using chromecast so i can stop my app through RNGC

**Versions:**
- RNGC Library Version: [3.4.0]

**To Reproduce**
1. Go to RNGC's app cast anything 
2. then go to some other app e.g youtube , cast video from here
3. now come back to our RNGC app
4. here we did not get any listener which tells that youtube or some other app is using chrome cast or RNGC disconnected

**Expected behavior**
I think RNGC should tell that casting is suspended because some other app is using chromecast 

**Screenshots**
![Screenshot_2020-12-22-19-17-47-20_0e837df69e87979a5198ceee1c1e4e9d](https://user-images.githubusercontent.com/32193401/102897805-6bd18180-448a-11eb-9136-b061baf3ad21.jpg)
Here in this screenshot you can see it showing in my app that its playing in background where in reality youtube is being played on chromecast

Hope I have describe it well :) looking froward to here from you ASAP , 
Thanks

**Comment by petrbela** [comment]
This should be fixed in the latest versions.
