### ISSUE TITLE
PromisesObjC/FBLPromises.h file not found

### ISSUE THREAD

**Issue by mirco22** [react-native-google-cast/react-native-google-cast#268]
Hi,
I can't run my iOS project after install the version 4.0.0 of this library. Android project works fine and also library works fine, but iOS is blocking on project building.
When I try running it on Xcode this error appears "PromisesObjC/FBLPromises.h file not found".
Do you have any solution?
Sometimes (without a specific logic) Xcode gave me also this error for library react-native-track-player: "Command CompileSwift failed with a nonzero exit code". Obviously the error appears just after install react-native-google-cast library.
Any advice, or fix or else?

Thank you so much.

**Comment by petrbela** [comment]
Hi! `PromisesObjC` should be available after running `pod install` and building your xcworkspace. Not sure what might be wrong. Could you create a reproducible example?

**Comment by mirco22** [comment]
I've solved. There was some conflict with another library (react-native-photo-editor) and with his pod specification. I attach this library on this thread so you can check and fix if you like: https://github.com/prscX/react-native-photo-editor.

Thank you so much.
