### ISSUE TITLE
Keep App Alive In Background

### ISSUE THREAD

**Issue by shariqs** [react-native-google-cast/react-native-google-cast#269]
I have a music player that plays music on a mobile device and is controlled by a web application.

Without Chromecast, I wake up the device after every song to see if there is a change in the playlist.

Is there a way to wake up the device to do an API call between each track through Chromecast?
Currently, when playing music through Chromecast, my device goes to sleep and is unable to check for updates.

Please advise!

**Comment by petrbela** [comment]
Hmm, I guess this could be implemented through the background audio mode (at least on iOS; not sure about Android). I'm not sure if adding it to the library itself is the best approach. At the very least, you'll have to add "background audio" mode capability in your app. Have you tried that?

**Comment by shariqs** [comment]
Background audio mode doesn't keep the device alive when playing through Chromecast because technically music isn't being played through the device.

**Comment by EyMaddis** [comment]
This is something that a custom receiver can achieve where you run JS on the cast device.

**Comment by shariqs** [comment]
@EyMaddis, can you share more information?

**Comment by EyMaddis** [comment]
Instead of using the default player (receiver), you can build your own: https://developers.google.com/cast/docs/web_receiver

**Comment by krunalbad** [comment]
You can do something like this https://stackoverflow.com/a/49743668/14117686
