### ISSUE TITLE
Play specific item in a queue

### ISSUE THREAD

**Issue by marcinkieruzel** [react-native-google-cast/react-native-google-cast#274]
Hi, is there any way to play a specific item from a queue? Like I'm loading 10 items and want to start from 5th.

**Comment by petrbela** [comment]
Hey, this should be possible using [`startIndex`](https://react-native-google-cast.github.io/docs/api/interfaces/mediaqueuedata#optional-startindex), e.g. `loadMedia({ ..., queueData: { ..., startIndex: 4 })`
