### ISSUE TITLE
How to get duration in v4?

### ISSUE THREAD

**Issue by gavrichards** [react-native-google-cast/react-native-google-cast#275]
In the previous version it was possible to get streamDuration from mediaStatus. This no longer appears to be there. Is there another way?
If not, could this be brought back?
Thanks

**Comment by petrbela** [comment]
It's now [`mediaStatus.mediaInfo.streamDuration`](https://react-native-google-cast.github.io/docs/api/interfaces/mediainfo#optional-streamduration). Btw you can use "search" in the documentation ;)

**Comment by gavrichards** [comment]
Thanks for the quick response @petrbela - I did search the docs, but I got the impression that was for when passing a duration into the loadMedia method, not for reading an automatically calculated duration. I'll give it a try though.
