### ISSUE TITLE
Provide support to set hlsSegmentFormat on mediaInfo

### ISSUE THREAD

**Issue by isamuhiro** [react-native-google-cast/react-native-google-cast#278]
Hi, we have a case where we need to play audio streams on chromecast, but the library is not able to reproduce the follow content: http://rcavliveaudio.akamaized.net/hls/live/2006635/P-2QMTL0_MTL/playlist.m3u8

According to this issue: https://stackoverflow.com/questions/59974413/live-audio-hls-stream-fails-to-play , this should be pretty straightforward. Just define the hlsSegmentFormat on mediaInfo to : `ts_aac`. 

I'm also setting the content type to: audio/aac, but not having any success.

**Comment by tomas-lejdung** [comment]
This would be great, as well as HlsVideoSegmentFormat

**Comment by petrbela** [comment]
Yeah, looks like these are new properties that haven't been included in this library yet. If you want to go ahead and make a PR, just add the segment formats to [TS](https://github.com/react-native-google-cast/react-native-google-cast/blob/main/src/types/MediaInfo.ts), [iOS](https://github.com/react-native-google-cast/react-native-google-cast/blob/main/ios/RNGoogleCast/types/RCTConvert+GCKMediaInformation.m) and [Android](https://github.com/react-native-google-cast/react-native-google-cast/blob/main/android/src/main/java/com/reactnative/googlecast/types/RNGCMediaInfo.java).

**Comment by tomas-lejdung** [comment]
I have created the PR now, though it seems that iOS does not support theses properties.
https://developers.google.com/cast/docs/reference/ios/interface_g_c_k_media_information

Though there was already a file created for HLSSegmentFormat in this repo for iOS but it is not used.
https://github.com/react-native-google-cast/react-native-google-cast/blob/main/ios/RNGoogleCast/types/RCTConvert%2BGCKHLSSegmentFormat.m

**Comment by petrbela** [comment]
That would explain why I forgot to include it. It looks like on iOS the property can be set in [GCKMediaRequestItem](https://developers.google.com/cast/docs/reference/ios/interface_g_c_k_media_request_item) but I don't see where the GCKMediaRequestItem is being used.

**Comment by tomas-lejdung** [comment]
Me neither. Have you seen my PR?

**Comment by petrbela** [comment]
Yes. There's an open [issue to possibly remove the properties altogether and let the SDK handle the format automatically](https://issuetracker.google.com/issues/183529130). Still, for the time being, I think going forwards with the PR to at least fix Android is reasonable. I'll add comments there.

**Comment by petrbela** [comment]
Resolved via #323
