### ISSUE TITLE
cast button not showing in android

### ISSUE THREAD

**Issue by official-bharat** [react-native-google-cast/react-native-google-cast#279]
In MainActivity.java

```java
import android.os.Bundle;

import com.facebook.react.ReactActivity;
import org.devio.rn.splashscreen.SplashScreen;
import androidx.appcompat.app.AppCompatActivity;
import com.google.android.gms.cast.framework.CastContext;
import androidx.annotation.Nullable;

public class MainActivity extends ReactActivity {
  @Override
  protected void onCreate(@Nullable Bundle savedInstanceState) {
     SplashScreen.show(this);
    super.onCreate(savedInstanceState);

    CastContext.getSharedInstance(this);
  }
```
  
  In AndroidMainfest.xml
  
 ```xml
 <meta-data
        android:name="com.google.android.gms.cast.framework.OPTIONS_PROVIDER_CLASS_NAME"
        android:value="com.reactnative.googlecast.GoogleCastOptionsProvider" />
```
        
In build.gradle 
```gradle
        buildToolsVersion = "29.0.2"
        minSdkVersion = 16
        compileSdkVersion = 29
        targetSdkVersion = 29
        supportLibVersion = "29.0.0"
        castFrameworkVersion = "19.0.0"`      
```
        
Cast button not showing on Android please help me to solve the issue. I am done with all installation if any other kind of installation or something else please let me know! 
Thanks in advance

**Comment by official-bharat** [comment]
@petrbela Please help me to fix this issue in android

**Comment by niteshBhardwaj** [comment]
@official-bharat 
I also faced this issue on android on the first load of the app.
And I fixed it with a custom button and on tap, on that, I called "GoogleCast.showCastDialog()"

**Comment by petrbela** [comment]
Could you guys provide a full example app where it's happening? It seems to work for the cases I'm testing.

**Comment by maliotti** [comment]
@official-bharat Do you have Google Play Services installed? If not, make sure it is.

Then try adding the following in `android/app/build.gradle`:

```
dependencies {
  ...
  implementation "com.google.android.gms:play-services-cast-framework:${safeExtGet('castFrameworkVersion', '+')}"
  ...
}

...

def safeExtGet(prop, fallback) {
  rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}
```

The rest of the code you shared looks good to me. Hope this helps!

**Comment by MarcoVPQ** [comment]
I was having the same issue, but found out you need to configure the other end of the channel.

Please follow this link to finalized configuration.

https://developers.google.com/cast/docs/web_receiver

**Comment by rdhox** [comment]
@petrbela here what I coded, you could use it as a starting base: 

```javascript
import React, {useMemo} from 'react';
import { Alert } from 'react-native';
import GoogleCast from 'react-native-google-cast';
import { useCastState, CastState } from 'react-native-google-cast'
import { Feather } from '@expo/vector-icons';


interface Props {}

const ChromeCastButton: React.FC<Props> = (props) => {

  async function handleCast() {
    try {
      if (isDevices) {
        await GoogleCast.showCastDialog();
      } else {
        Alert.alert('No device available to chromecast')
      }
    } catch (error) {
      console.log(error)
    }
  }

  const stateDevices = useCastState();
  const isDevices = useMemo(() => {
    if (stateDevices === CastState.NO_DEVICES_AVAILABLE) {
      return false;
    }
    return true;
  }, [stateDevices]);

  return (
    <Feather onPress={handleCast} name="cast" size={28}  />
  );
}
```

**Comment by rdhox** [comment]
Ok ignore my post above, it was not working. Here what I understood, the button `CastButton` have to be rendered for the library to works. So to solve the problem of the none rendering, here what I did: 

```javascript
import React from 'react';
import { StyleSheet } from 'react-native';
import styled from 'styled-components/native';
import GoogleCast from 'react-native-google-cast';
import {  CastButton } from 'react-native-google-cast'
import { Feather } from '@expo/vector-icons';

import { veryLightGrey } from '../../config/colors';


interface Props {}

const ChromeCastButton: React.FC<Props> = (props) => {

  async function handleCast() {
    try {
      GoogleCast.showCastDialog();
    } catch (error) {
      console.log(error)
    }
  }

  return (
    <Container>
      <CastButton style={styles.btnCast} />
      <HideNativeButton />
      <Feather onPress={handleCast} name="cast" size={28} color={veryLightGrey} />
    </Container>
  );
}

const styles = StyleSheet.create({
  btnCast: {
    position: 'absolute',
    top: 0,
    left: 0,
    height: 30,
    width: 30,
  }
});

const Container = styled.View`
  position: relative;
  width: 30px;
  height: 30px;
  justify-content: center;
  align-items: center;
`;

const HideNativeButton = styled.View`
  position: absolute;
  top: 0;
  left: 0;
  width: 30px;
  height: 30px;
  background-color: white;
`;

export default ChromeCastButton;
```

So I hide the the CastButton which not really work under a View that let appear the button that will call `GoogleCast.showCastDialog()` and let the pop up of devices appear.

**Comment by daogurtsov** [comment]
> Ok ignore my post above, it was not working. Here what I understood, the button `CastButton` have to be rendered for the library to works. So to solve the problem of the none rendering, here what I did:
> 
> ```js
> import React from 'react';
> import { StyleSheet } from 'react-native';
> import styled from 'styled-components/native';
> import GoogleCast from 'react-native-google-cast';
> import {  CastButton } from 'react-native-google-cast'
> import { Feather } from '@expo/vector-icons';
> 
> import { veryLightGrey } from '../../config/colors';
> 
> 
> interface Props {}
> 
> const ChromeCastButton: React.FC<Props> = (props) => {
> 
>   async function handleCast() {
>     try {
>       GoogleCast.showCastDialog();
>     } catch (error) {
>       console.log(error)
>     }
>   }
> 
>   return (
>     <Container>
>       <CastButton style={styles.btnCast} />
>       <HideNativeButton />
>       <Feather onPress={handleCast} name="cast" size={28} color={veryLightGrey} />
>     </Container>
>   );
> }
> 
> const styles = StyleSheet.create({
>   btnCast: {
>     position: 'absolute',
>     top: 0,
>     left: 0,
>     height: 30,
>     width: 30,
>   }
> });
> 
> const Container = styled.View`
>   position: relative;
>   width: 30px;
>   height: 30px;
>   justify-content: center;
>   align-items: center;
> `;
> 
> const HideNativeButton = styled.View`
>   position: absolute;
>   top: 0;
>   left: 0;
>   width: 30px;
>   height: 30px;
>   background-color: white;
> `;
> 
> export default ChromeCastButton;
> ```
> 
> So I hide the the CastButton which not really work under a View that let appear the button that will call `GoogleCast.showCastDialog()` and let the pop up of devices appear.

THX, the only way it works for me

**Comment by petrbela** [comment]
In v4.1.0 the cast button is always visible (make sure to update your iOS Cast SDK, too). Please let me know if you still experience issues with the button not being available.
