### ISSUE TITLE
Calling invalid method in setActiveMediaTracks

### ISSUE THREAD

**Issue by niteshBhardwaj** [react-native-google-cast/react-native-google-cast#280]
https://github.com/react-native-google-cast/react-native-google-cast/blob/c50ed1065c7f1479ea506fdb553a80361918efec/src/api/RemoteMediaClient.ts#L179

@petrbela 
There is invalid method mapping in "RemoteMediaClient.ts". 
Check line no 179 where "Native.setActiveTrackIds(trackIds)" is called but that method doesn't exist on "RCGCRemoteMediaClient.java" file. I think the method name is misspelled here and this should be "setActiveMediaTracks".
Can you please update the correct name of the method?

Thank you.
<img width="334" alt="Screenshot 2021-01-25 at 1 11 10 PM" src="https://user-images.githubusercontent.com/12727179/105676775-fdf8f980-5f10-11eb-9b8b-3acefb65c635.png">
<img width="527" alt="Screenshot 2021-01-25 at 1 16 38 PM" src="https://user-images.githubusercontent.com/12727179/105676782-02251700-5f11-11eb-857f-c14dbe7bacec.png">

**Comment by petrbela** [comment]
Yes, that looks like a bug (I didn't notice the method name on iOS is different than on Android). I'll push a fix today.

**Comment by ajaysaini-sgvu** [comment]
Can you pls publish new package @petrbela  ?

**Comment by petrbela** [comment]
@ajaysaini-sgvu See 4.0.1
