### ISSUE TITLE
IOS build is failing: clang: error: no such file or directory: '... /node_modules/react-native-google-cast/ios/RNGoogleCast/types/RCTConvert+GCKMediaLoadOptions.m' clang: error: no input files

### ISSUE THREAD

**Issue by goncalo-assuncao** [react-native-google-cast/react-native-google-cast#281]
Versions:

RNGC Library Version: 4.0.0
RN: 0.59 (Not upgradable, unfortunately)

I installed the the 4.0.0 version of the lib, ran 'react-native link react-native-google-cast'
installed the google-cast-sdk-no-bluetooth via pod install
Added the RNGoogleCast.xcodeproj manualy just like the docs, and followed all the steps.
Also had to change the RNGoogleCast build Settings - Framework Search Paths to match the Pods/google-cast-sdk-no-bluetooth

After all that, when I run the ios build, I'm getting the error: 

`info ../node_modules/react-native-google-cast/ios/RNGoogleCast/types/RCTConvert+GCKMediaLoadOptions.m -o project/ios/build/../Build/Intermediates.noindex/RNGoogleCast.build/Debug-iphonesimulator/RNGoogleCast.build/Objects-normal/x86_64/RCTConvert+GCKMediaLoadOptions.o
clang: error: no such file or directory: 'project/node_modules/react-native-google-cast/ios/RNGoogleCast/types/RCTConvert+GCKMediaLoadOptions.m'
clang: error: no input files`

I already cleaned the build folder, tried several different emulators, installed/re-installed the frameworks several times

Any clue?

**Comment by goncalo-assuncao** [comment]
@petrbela any clue?

**Comment by petrbela** [comment]
Hmm that looks like an artifact from some older version of the xcproj file. I don't normally use it directly but I think the reference can be safely removed. I'll push a new version with a fix.

**Comment by goncalo-assuncao** [comment]
Hi @petrbela! Thank you for the fix.

Now I' having the same issue, but with the` GCKMediaQueueLoadOptions.m` file

Is there something that I can do, on my end to fix this?

Cheers

**Comment by petrbela** [comment]
That's still the same issue, I haven't published a new version yet ;)

**Comment by petrbela** [comment]
Can you check if you can build the project now with 4.0.1?

**Comment by goncalo-assuncao** [comment]
@petrbela thank you for the fix!

I tested, and I'm getting this error:

`.../node_modules/react-native-google-cast/ios/RNGoogleCast/api/RNGCRemoteMediaClient.m:13:9: fatal error: 'FBLPromises.h' file not found
#import "FBLPromises.h"
        ^~~~~~~~~~~~~~~
23 warnings and 1 error generated.`

Do I need to add another framework to the pods?

cheers

**Comment by petrbela** [comment]
Yes, you'll need `PromisesObjC`. I wonder why it wasn't pulled in as a transitive dependency but if needed check out their installation docs https://github.com/google/promises/blob/master/g3doc/index.md#getting-started
