### ISSUE TITLE
Getting started guide wrong for default receivers

### ISSUE THREAD

**Issue by dani-mp** [react-native-google-cast/react-native-google-cast#289]
In the [Getting started guide](https://github.com/react-native-google-cast/react-native-google-cast/blob/080a672db26288d77e5eb18338828bc18cd0d92d/docs/getting-started/setup.md), I think this line is not correct:
> Make sure to replace ABCD1234 with your receiver app id. If using the default receiver, you may delete that line.

I'm using the default receiver and I get a warning about `_CC1AD845._googlecast._tcp` being missing in my Bonjour services. I guess the default receiver has in fact that id.

**Comment by dani-mp** [comment]
Let me know if I should create a PR. I didn't do it because I wanted first to have someone who could confirm this!

**Comment by petrbela** [comment]
No need it's already published.
