### ISSUE TITLE
IOS 14 , CastButton is not showing.  

### ISSUE THREAD

**Issue by dasDeepankar** [react-native-google-cast/react-native-google-cast#290]
I'm using 

 pod 'react-native-google-cast/NoBluetooth', path: '../node_modules/react-native-google-cast/ios/'
 pod 'google-cast-sdk-no-bluetooth'

Inside AppDelegate.m -->

 GCKDiscoveryCriteria *criteria = [[GCKDiscoveryCriteria alloc] initWithApplicationID:kGCKDefaultMediaReceiverApplicationID];
  GCKCastOptions* options = [[GCKCastOptions alloc] initWithDiscoveryCriteria:criteria];

  [GCKCastContext setSharedInstanceWithOptions:options];

Can I get a help , don't know what i have missing here!

**Comment by alejandrorangel** [comment]
I'm having the same behavior, everything is working fine on android, iOS it's displayed after the permission dialog the cast button disappear

**Comment by dasDeepankar** [comment]
@alejandrorangel Agreed! , it's showing after the permission , don't know what the fix here. Is there any work around for this?

**Comment by petrbela** [comment]
Can you guys try https://developers.google.com/cast/docs/discovery and see if anything helps?

**Comment by alejandrorangel** [comment]
@dasDeepankar we were able to fix it by adding this string to `info.plist` you might need to replace <APP_ID> with your cast app id

```
<key>NSLocalNetworkUsageDescription</key>
    <string>Chromecast needs access to local network</string>
<key>NSBonjourServices</key>
   <array>
	<string>_googlecast._tcp</string>
	<string>_<APP_ID>._googlecast._tcp</string>
   </array>

**Comment by loria33** [comment]
> I'm having the same behavior, everything is working fine on android, iOS it's displayed after the permission dialog the cast button disappear

Did you get this to work . I am having the same issue

**Comment by Balintataw** [comment]
Even with Bonjour configured correctly, I'm seeing this as well. It appears to have something to do with the 'local network access' permission. If that permission popup doesn't show at the start of the app, the cast button won't work. It also appears that apple has not provided an api to check or ask for that permission. It is supposed to happen automatically when the app makes a network request but it seems unreliable at best. Some things to check is that you've enabled the Wifi Capability in xCode and that your provisioning profiles have wifi capability checked in the developers console.

**Comment by petrbela** [comment]
If you're experiencing issues with the local network dialog, you may try setting `options.startDiscoveryAfterFirstTapOnCastButton = false` which will start the discovery immediately.

**Comment by petrbela** [comment]
Also note that the Google Cast SDK 4.6.0 library changed behavior so that the cast button is now always rendered, and displays a troubleshooting dialog when no devices have been found. You can update to the latest version using `pod update`.

**Comment by petrbela** [comment]
Since the button is now always displayed, I'm closing this issue. If you're still having trouble discovering/connecting to devices, please open a new issue (or comment on one of the open ones).
