### ISSUE TITLE
Not getting DEVICE name 

### ISSUE THREAD

**Issue by dasDeepankar** [react-native-google-cast/react-native-google-cast#301]
I want show casting device name.
I'm using :
import { useCastSession } from 'react-native-google-cast'
const castSession = useCastSession()
castSession.getCastDevice()
In side a function component.

But I am getting an error. Don't know what I'm doing wrong. need a help here.

**Comment by petrbela** [comment]
@dasDeepankar What error are you getting? iOS or Android? What versions?

**Comment by petrbela** [comment]
Is this still an issue? If so, can you provide more details?
