### ISSUE TITLE
Stream position not up to date when coming from background

### ISSUE THREAD

**Issue by rickklaasboer** [react-native-google-cast/react-native-google-cast#307]
When using the Hooks API i'm unsure how to get the chromecasts stream position when the app is running in the background. The `useStreamPosition` hook always seems to go back to the position before the app went into the background. This causes the Chromecast to also go back to that time.

So let's say you're watching a video and the app goes into the background at 50 seconds. The chromecast continues playback but the stream position does not update anymore in React Native. When going back to the app, the stream position will say it's at 50 seconds causing the Chromecast to also go back to 50 seconds instead of where it actually was.

I've also created a really simple example app (https://github.com/rickklaasboer/rngc-stream-position). Any help would be appreciated.

**Comment by petrbela** [comment]
Hey sorry forgot to reply to this. Did you manage to solve your problem?
