### ISSUE TITLE
Target has transitive dependencies that include statically linked binaries: GoogleCast.framework

### ISSUE THREAD

**Issue by ajaysaini-sgvu** [react-native-google-cast/react-native-google-cast#309]
Hi, We are using `use_frameworks` in our pod file. When we are trying to do `pod install` then we are getting below error -

`Target has transitive dependencies that include statically linked binaries: GoogleCast.framework google-cast-sdk-no-bluetooth`

I see similar issue and solution is to update in your pod spec https://github.com/react-native-google-cast/react-native-google-cast/issues/305. 

Can you please look into it ?

**Comment by geroale** [comment]
Same problem here!

**Comment by ajaysaini-sgvu** [comment]
@petrbela
