### ISSUE TITLE
Exclude package on Huawei HMS devices without Google Play Services

### ISSUE THREAD

**Issue by marf** [react-native-google-cast/react-native-google-cast#310]
Hello,
we are using this package and it is very good!
The problem is that we have published our app also on Huawei AppGallery which does not have the Google Play Services.
Because of this the app crashes with a device without Google Play Services.
Is there a way through a Build Variant or something like this to exclude this package on Huawei devices without Google Play Services?

Thank you,
Marco

**Comment by petrbela** [comment]
There's a related ticket #287. I haven't had time to deal with it yet but I'd be happy to review a PR if you come up with a fix.
