### ISSUE TITLE
Anyway to defer the initial dialog permission?

### ISSUE THREAD

**Issue by sospedra** [react-native-google-cast/react-native-google-cast#314]
I understand that the dialog has to show up before casting. That has to be approved. That's totally fine. But, it's too aggressive that this dialog is the very first thing any user will face. It's a horrible UX. Anyway to delay such dialog popping up?

Thank you!

**Comment by petrbela** [comment]
See https://react-native-google-cast.github.io/docs/getting-started/setup step 4 for iOS.

**Comment by sospedra** [comment]
Perfect, ty! It wasn't clear to me if that optional step would defer the dialog!

**Comment by marf** [comment]
Hello @petrbela ,
we instantiated the cast with `options.disableDiscoveryAutostart = true`

but continue to see the permission prompt at the beginning.

Are we missing something?

**Comment by vvdodiya** [comment]
Hello

I am facing the same issue please help me. Getting permission popup initially when the app initially launch.

I have done the same and set options like  https://react-native-google-cast.github.io/docs/getting-started/setup step 4 for iOS. and change all possible options but no luck.
Please help me to fix and set the permission popup when users start discovering.
thank you in advance.

**Comment by petrbela** [comment]
By default, the permission dialog does show up until user presses the Cast button. Did you by any chance set `options.startDiscoveryAfterFirstTapOnCastButton = false`?

**Comment by vvdodiya** [comment]
Hello @petrbela 

I did not set anywhere options.startDiscoveryAfterFirstTapOnCastButton = false.  I have created react native fresh project and just set up steps in app delegate and run the project in the real device and got a popup instantly on the launch app.

Here I added stops to reproduce. 

Step 1: Create a new react native project  using 
-     react-native init ChromeCastDemo

Step 2: install react-native-google-cast using below command 
-     npm i react-native-google-cast 

Step 3: Pod install 
- cd ios 
- pod install

Step 4: import GoogleCast in AppDelegate.js

Step 5:  Insert the following in the application:didFinishLaunchingWithOptions method (as described in setup Steps: https://react-native-google-cast.github.io/docs/getting-started/setup)

NSString *receiverAppID = kGCKDefaultMediaReceiverApplicationID; // or @"ABCD1234"
GCKDiscoveryCriteria *criteria = [[GCKDiscoveryCriteria alloc] initWithApplicationID:receiverAppID];
GCKCastOptions* options = [[GCKCastOptions alloc] initWithDiscoveryCriteria:criteria];
[GCKCastContext setSharedInstanceWithOptions:options];


- Here is my demo project link please check it and let me know whats wrong i do 
https://github.com/vvdodiya/ChromeCastDemo/tree/main/ChromeCastDemo

Please help 

Thank you in advance.

**Comment by petrbela** [comment]
You should move the Cast initialization code in `didFinishLaunchingWithOptions` before you create the `RTCBridge`.

As for your problem, I wasn't able to replicate it. You may try looking at how the example and playground projects are set up and run them locally to see if they have the same issue.

**Comment by vvdodiya** [comment]
@petrbela I have move  initialization code in didFinishLaunchingWithOptions before create the RTCBridge, but still popup open initially when app launch. 

Please help

**Comment by thbhavin1986** [comment]
@petrbela 
I am facing same issue, i tried all the possible way but always permission dialog shows when app launch.

**Comment by ashwanihundwani1986** [comment]
@vvdodiya @Bhavin-hyperspace Any solutions to it in 2024 :) to get rid of these first up popups? CC @petrbela
