### ISSUE TITLE
Is there a way to know if the cast button is rendered or not?

### ISSUE THREAD

**Issue by LukasRobertsson** [react-native-google-cast/react-native-google-cast#319]
Hi, I'm trying to add a white circular background to the CastButton component. 
Like this:
![Screenshot from 2021-05-04 15-44-32](https://user-images.githubusercontent.com/6552034/117013474-3407ff80-acf0-11eb-841c-ae76014ac4c2.png)

But the CastButton isn't always rendered(ios: haven't accepted permissions or no devices available) so i'm ending up with an empty white circle :(
Is there a way to know if the cast button is rendered or not??

**Comment by LukasRobertsson** [comment]
`  const castState = useCastState()
`
Will return noDevicesAvailable on iOS when the cast button hasn't been clicked on.

**Comment by petrbela** [comment]
Good point, the cast state is the way to go but we should cover the case before the first use.

**Comment by LukasRobertsson** [comment]
@petrbela Thank you for answering. 
If I set `options.startDiscoveryAfterFirstTapOnCastButton = false` in `AppDelegate.m` the cast state will return `notConnected` even before first user tap. But the local network permission dialog is never displayed. Is the permission auto accepted?

**Comment by petrbela** [comment]
@LukasRobertsson Hmm, based on the Cast SDK docs, in that case, the discovery should start immediately (and display the network permission dialog) when the app is launched. If you're not getting the dialog, it could be that you've already accepted it. Try removing the app and reinstalling it again (if using Simulator, hold press the icon to delete and then rerun from Xcode).

I'm honestly not sure what the exact lifecycle for the cast states is, especially in the not-initialized state; the library just presents whatever the native SDK returns. You might search non-react-native-specific forums as the behavior would be the same for someone using the iOS SDK directly.

**Comment by petrbela** [comment]
The bottom line I think is that when the network permissions and discovery changes were added in Google Cast SDK 4.5.0 to accommodate iOS 14, they didn't add a separate cast state for that case. So it's left up to the application developer (or possibly this library) to keep track of whether it's been initialized or not.

**Comment by petrbela** [comment]
So in RNGC v4.1.0 there's now [isRunning](https://react-native-google-cast.github.io/docs/api/classes/discoverymanager#isrunning) which should tell you whether the discovery has started yet.

However, the Google Cast SDK 4.6.0 library changed behavior so that the cast button is now always rendered, and displays a troubleshooting dialog when no devices have been found. I think that's probably the solution you're looking for; just get the latest version using `pod update`.
