### ISSUE TITLE
App terminates when trying to Chromecast.connectToDevice(id)

### ISSUE THREAD

**Issue by jonburger** [react-native-google-cast/react-native-google-cast#32]
Hi,

Just been trying to set this up and get it working, but I've taken your example class and whenever it get's to the point of connecting to device `Chromecast.connectToDevice(id)` the app just terminates with the following message:

```Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'GCKCastContext has not been created yet with +[setSharedInstanceWithOptions:]'```

Any thoughts?

**Comment by charliesbox** [comment]
hi, are you using master, or the last release?

**Comment by jonburger** [comment]
Hi, I installed using the instructions in the readme.md, the package.json says:

```
"react-native": "0.44.0",
"react-native-google-cast": "^1.3.0"
```

**Comment by charliesbox** [comment]
ok, will take a look

**Comment by DracoBlue** [comment]
I had the same issue with iOS and activly downgraded the sdk to v2 (like in https://github.com/charliesbox/react-native-google-cast/blob/master/example/ios/Podfile.lock but 2.10.x )

@charliesbox Maybe this is possible im Android, too?

**Comment by charliesbox** [comment]
@DracoBlue for sure, there's a line in the gradle file where the version was restricted :)

Looks like new version for iOS - Android was really a major change.

Thank you for finding this workaround.

**Comment by charliesbox** [comment]
I'm testing a new version here -> https://github.com/charliesbox/react-native-google-cast/pull/42

So far, so good, using Cast SDK 3.3

Could you help me testing it?

**Comment by DracoBlue** [comment]
Yep! Will try the #42 tomorrow!

**Comment by drahosistvan** [comment]
I changed the pod definition to `pod 'google-cast-sdk', '3.3.0'` and it works very well!

**Comment by petrbela** [comment]
Please upgrade to the latest version, it handles connection automatically.
