### ISSUE TITLE
Cast client updates while app is in background.

### ISSUE THREAD

**Issue by mishabelokon** [react-native-google-cast/react-native-google-cast#328]
Hello!

My Android app is working with a playlist of videos and I want to make users be able to cast their playlists while app is in background. For some reason when app is in background and the phone is not connected to my Mac with cable cast client(`useRemoteMediaClient` hook) always updates which occurs new onMediaStatusUpdated listener to be created(for some reason old ones cannot be removed via `.remove() `and they are triggering as well). 

`mediaStatus` from `useMediaStatus` hook returns new `mediaStatus` as many times as `onMediaStatusUpdated` listeners created. Looks like memory leak. My app uses this listener to define is video ended and video play/paused on cast device so when video ends it triggers listener tens of times and videos are swapping like crazy.

You need to wait for some time to make it happen from 30 seconds to 15 minutes(better to reload an app if it did not happen in 30 seconds). After you see `castClient CHANGED` log try to make play/pause on cast device using remote controller and you can see that listeners were triggered twice and mediaStatus was updated twice as well.

The repro is very simple. Start video casting, lock your phone, wait. 

Maybe I'm doing something wrong because I do not know how such an issue is not still reported by anyone.

Tested with newly inited app
```
"react-native": "0.64.1",
"react-native-google-cast": "^4.0.3"
```
Sorry for my English
Please help

Here is code sample

```js
import React, {useRef, useEffect} from 'react';
import {Text, TouchableOpacity, View} from 'react-native';

import {
  SessionManager,
  CastContext,
  useRemoteMediaClient,
  useMediaStatus,
  CastButton,
} from 'react-native-google-cast';

const App = () => {
  const mediaStatusUpdate = useRef(null);
  const castClient = useRemoteMediaClient();
  const googleCastConnectListener = useRef(null);
  const sessionManager = useRef(new SessionManager()).current;
  const castClientRef = useRef(null);
  const mediaStatus = useMediaStatus();

  useEffect(() => {
    console.log('castClient CHANGED');
    castClientRef.current = castClient;
  }, [castClient]);

  useEffect(() => {
    console.log('mediaStatus changed');
  }, [mediaStatus]);

  const onCastConnected = () => {
    const mediaPayload = {
      mediaInfo: {
        contentUrl:
          'https://commondatastorage.googleapis.com/gtv-videos-bucket/CastVideos/mp4/BigBuckBunny.mp4',
      },
    };
    castClientRef.current?.loadMedia(mediaPayload);
  };

  useEffect(() => {
    googleCastConnectListener.current?.remove();
    googleCastConnectListener.current = sessionManager.onSessionStarted(() => {
      console.log('session started');
      onCastConnected();
    });
  }, []);

  useEffect(() => {
    mediaStatusUpdate.current?.remove();
    mediaStatusUpdate.current = castClient?.onMediaStatusUpdated(() => {
      console.log('onMediaStatusUpdated listener triggered');
    });
  }, [castClient]);

  return (
    <View>
      <TouchableOpacity
        style={{height: 100, width: 100, backgroundColor: 'orange'}}
        onPress={() => {
          CastContext.showCastDialog();
        }}>
        <Text>cast</Text>
      </TouchableOpacity>
      <CastButton />
    </View>
  );
};

export default App;
```

**Comment by petrbela** [comment]
Hi!

It looks like the problem you're seeing is caused by forgetting to remove the listeners when unmounting. The correct way to use `useEffect` is to remove a listener in the callback that you return.

```
  useEffect(() => {
    const sessionStartedListener = sessionManager.onSessionStarted(() => {
      console.log('session started');
      onCastConnected();
    });

    return () => {
       sessionStartedListener.remove()
    }
  }, []);

  useEffect(() => {
    const mediaStatusUpdateListener = castClient?.onMediaStatusUpdated(() => {
      console.log('onMediaStatusUpdated listener triggered');
    });

    return () => {
       mediaStatusUpdateListener.remove()
    }
  }, [castClient]);
```

Looks like you already use the `useMediaStatus()` and `useSession()` hooks that manage listeners for you and give you the current status and session. I'd just remove the manual listener handling in `useEffects`, and that should fix the problem.

**Comment by mishabelokon** [comment]
@petrbela Thanks for your reply!

Tried "hooks only" way:

```js
  const castClient = useRemoteMediaClient();
  const castSession = useCastSession();
  const castClientRef = useRef(null);
  const currentSessionID = useRef(null);
  const mediaStatus = useMediaStatus();

  useEffect(() => {
    console.log('castClient CHANGED');
    castClientRef.current = castClient;
  }, [castClient]);

  useEffect(() => {
    console.log('castSession change');
    if (castSession?.id && currentSessionID.current !== castSession.id) {
      currentSessionID.current = castSession.id;
      onCastConnected();
    }
  }, [castSession]);

  useEffect(() => {
    console.log('mediaStatus changed');
  }, [mediaStatus]);


```

Both castClient and castSession updates and mediaStatus changes multiple times after some time in background

Tried listeners way:

```js
  const castClient = useRemoteMediaClient();
  const castClientRef = useRef(null);
  const sessionManager = useRef(new SessionManager()).current;

  useEffect(() => {
    const sessionStartedListener = sessionManager.onSessionStarted(
      ({client}) => {
        console.log('session started');
        castClientRef.current = client;
        onCastConnected();
      },
    );

    return () => {
      sessionStartedListener?.remove();
    };
  }, []);

  useEffect(() => {
    console.log('castClient CHANGED');
    castClientRef.current = castClient;
    const mediaStatusUpdateListener = castClient?.onMediaStatusUpdated(() => {
      console.log('onMediaStatusUpdated listener triggered');
    });

    return () => {
      mediaStatusUpdateListener?.remove();
    };
  }, [castClient]);

```
Same again - castClient updates and onMediaStatusUpdated listener triggers multiple times on background

I'm sorry about big snippets just do not want to miss any details.

What may be an issue? I'm guessing why does it work fine when app is in active state or when connected by cable to my Mac(maybe some energy optimisations?) I have made all tests on Samsung devices (S8, S9, A51 2020) Will try tomorrow with some Xiaomi phone

**Comment by petrbela** [comment]
Thanks for the update. It's possible that there's a bug in unregistering the callbacks in the native code when the app goes into the background (there have been some problems before). I'll try to look into it further.

Btw it wasn't entirely clear from your code -- why do you need to know when the playback stops or ends?

**Comment by mishabelokon** [comment]
Wow, great, please update on your progress :)

I need to know what happens on cast device to synchronise my UI with all cast-side actions such as play/pause/seek/video end to switch it to the next one(queue API is not an option). 

Ignoring my use case it looks like there are memory leaks. I'm not too good on native code but seems that there is a background issue that cast client updates when it actually does not and listeners cannot be removed as well.

**Comment by petrbela** [comment]
I added a `ignoreSessionUpdatesInBackground` option to `useCastSession` (and `useRemoteMediaClient`). I think it might solve your problem.

**Comment by petrbela** [comment]
Adding to the previous answer, I think the better solution is to set `options.suspendSessionsWhenBackgrounded = false` when initializing the CastContext in `AppDelegate`. Then it will behave like Android, i.e. continue the session in the background.
