### ISSUE TITLE
App can't cast video from 2nd times.

### ISSUE THREAD

**Issue by phuongit0301** [react-native-google-cast/react-native-google-cast#33]
**App.js:**

`'use strict';

import React, {
  Component
}                           from 'react';
import {
  Text,
  View,
  Dimensions,
  Navigator,
  StatusBar,
  AsyncStorage,
  BackAndroid,
  ActivityIndicator,
  InteractionManager,
  TouchableOpacity,
  Image,
}                           from 'react-native';

import Chromecast from 'react-native-google-cast';

class App extends Component {

  constructor(props) {
    super(props);
      showChromecast: false,
    }
  }

  componentDidMount() {
    this.getUserInfo().done();
    Chromecast.startScan();
    DeviceEventEmitter.addListener(Chromecast.DEVICE_AVAILABLE, (existance) => this.setState({chromecastAround: existance.device_available}));
  }

  render() {
    return (
      <View style={styles.container}>
        { (this.state.showChromecast && this.state.chromecastAround) && <ChromecastList {...this.state} handleShowChromecast={this.handleShowChromecast}
                                        handleConnectedChromecast={this.handleConnectedChromecast} setChromecastId={this.setChromecastId} /> }
      </View>
    );
  }

  renderScene = (route, navigator) => {
    let component = null;

    switch (route.id) {
      case 1:
        const route1 = AppRoutes.getRouteFromRouteId(1);
        component = <Detail ref={route1.refView} navigator={navigator} handlePlayerClose={this.handlePlayerClose} navigate={this.navigate} {...route} isLogin={this.state.isLogin} {...this.state}
                            fullscreenPlayer={this.fullscreenPlayer} />
        break;
      default:
          component = <Home ref={route1.refView} navigator={navigator} navigate={this.navigate} {...this.state} />
          break;
    }

    return (
      <View style={styles.container} onLayout={this._onLayout}>
        {component}
      </View>
    );
  }

  _onLayout = (e) => {
    const {width, height} = e.nativeEvent.layout;

    const _layout = appLayoutAndroid(e.nativeEvent.layout);
    this.setState(_layout);
  }
}

export default App;
`

**Detail.js:**

`import React, {Component} from 'react';
import {
  View,
  Text,
  Image,
  TouchableWithoutFeedback,
  TouchableOpacity,
  Dimensions,
  ActivityIndicator,
  Animated,
  Easing,
  AsyncStorage,
  Alert,
  Navigator,
  DeviceEventEmitter,
  AppState,
  InteractionManager
} from 'react-native';
import styles from '../../styles/Style';
import Video from 'react-native-video';
import {Progress, ProgressChromecast, ProgressLive} from '../../components';
import Chromecast from "react-native-google-cast";
import {CachedImage} from "react-native-img-cache";
import { Icon } from 'react-native-elements';

let FORWARD_DURATION = 7;
let currentChromecastTime = 0;

Navigator.NavigationBar.Styles = {backgroundColor: 'transparent'}

export default class PlayerVideo extends Component {

  constructor(props) {
    super(props);

    this.chromecastCastMedia = this.chromecastCastMedia.bind(this);
    this.onVideoLoad = this.onVideoLoad.bind(this);
    this.onVideoEnd = this.onVideoEnd.bind(this);
    this.onProgress = this.onProgress.bind(this);
    this.onProgressChanged = this.onProgressChanged.bind(this);
    this.updateProgressChanged = this.updateProgressChanged.bind(this);
    this.playOrPauseVideo = this.playOrPauseVideo.bind(this);
    this.playOrPauseChromecastVideo = this.playOrPauseChromecastVideo.bind(this);
    this.resizeModeControl = this.resizeModeControl.bind(this);
    //this.connectToChromecast = this.connectToChromecast.bind(this);
    this.onBuffer = this.onBuffer.bind(this);

    this.state = ({
      appState: AppState.currentState,
      rate: 1.0,
      volume: 1.0,
      muted: false,
      paused: false,
      pausedChromecast: false,
      duration: 0.0,
      currentTime: 0.0,
      isToggle: false,
      dataVideo: [],
      dataRelate: [],
      selectedTab: 'information',
      imageLoading: true,
      linkVideo: '',
      linkKaraoke: false,
      listDetail: null,
      key: new Date(),
      hideProgress: false,
      clicked: false,
      isBuffering: false,
      isBuffering: false,
      isKaraoke: false,
      currentTimeKara: 0,
      isChangeLink: false,
      playVideoEnd: false,
      loading: false,
    });
  }

  componentDidMount() {
    const {receiveDetail, dataDetail, data, passProps, idChild, isLogin} = this.props;

    InteractionManager.runAfterInteractions(() => {
      this.setState({loading: true});

      if(parseInt(idChild) > 0) {
        receiveDetail(idChild);
      } else {
        (passProps && passProps.timelines) && dataDetail(passProps.timelines.content);
      }
    });

    //this.props.chromecastId && this.resetChromecast(this.props.chromecastId);
    DeviceEventEmitter.addListener(Chromecast.MEDIA_LOADED, () => { console.log(3333333) });
    DeviceEventEmitter.addListener(Chromecast.DEVICE_CONNECTED, () => {this.chromecastCastMedia()});

  }

  closeAudio = () => {
    const {handlePlayerClose} = this.props;
    handlePlayerClose();
  }

  async connectToChromecast(id) {
    const isConnected = await Chromecast.isConnected();
    isConnected ? this.chromecastCastMedia() : Chromecast.connectToDevice(id);
  }

  resetChromecast(id) {
    this.connectToChromecast(id).done();
  }

  componentWillReceiveProps(nextProps) {
    nextProps.chromecastId && this.connectToChromecast(nextProps.chromecastId);
  }

  componentWillUnmount() {
    if(this.timeout) {
      clearTimeout(this.timeout);
    }
    AppState.removeEventListener('change', this._handleAppStateChange);
  }

  onVideoEnd() {
    this.setState({paused: true, playVideoEnd: true});
  }

  onVideoLoad(e) {
    this.setState({
      duration: !this.props.isLogin ? 0.0 : e.duration,
      //duration: e.duration,
      currentTime: e.currentTime,
      imageLoading: false
    });

    setTimeout(() => {
      this.setState({hideProgress: true});
    }, 8000)
  }

  onProgress(e) {
    this.setState({
      currentTime: e.currentTime,
      imageLoading: false
    });
  }

  getCurrentTimePercentage(currentTime, duration) {
    if (parseFloat(this.state.currentTime) > 0 && parseFloat(this.state.duration) > 0) {
      return parseFloat(currentTime) / parseFloat(duration);
    } else {
      return 0;
    }
  }

  onProgressChanged(newPercent, paused) {
    let {duration} = this.state;
    let newTime = newPercent * duration / 100;

    if(newTime <= 0) {
      newTime = 0;
    }

    if(newTime > duration) {
      newTime = duration;
    }

    this.setState({currentTime: newTime, paused: paused});
    this.videoPlayer.seek(newTime);
  }

  playOrPauseVideo() {
    if(!this.props.isLogin) {
      this.showMessageIfNotLoggedIn();
    } else {
      if(this.state.paused && this.state.playVideoEnd) {
        this.videoPlayer.seek(0);
      }
      this.setState({paused: !this.state.paused, playVideoEnd: false});
    }
    //this.setState({paused: !this.state.paused});
  }

  playOrPauseChromecastVideo() {
    if(!this.props.isLogin) {
      this.showMessageIfNotLoggedIn();
    } else {
      Chromecast.togglePauseCast();
      this.setState({pausedChromecast: !this.state.pausedChromecast})
    }
    // Chromecast.togglePauseCast();
    // this.setState({pausedChromecast: !this.state.pausedChromecast})
  }

  displayProgress() {
    this.setState({hideProgress: false, isToggle: false});

    if(this.timeout) {
        clearTimeout(this.timeout);
    }

    this.timeout = setTimeout(() => {
      this.setState({hideProgress: true});
    }, 8000);
  }

  chromecastCastMedia() {
    const { listDetail } = this.props.data;
    Chromecast.castMedia(listDetail.content.link, listDetail.content.name, listDetail.content.image, 0);
  }

  resizeModeControl() {
    const {fullscreenPlayer, width, height} = this.props;
    let fullscreen = '';

    Orientation.getOrientation(function(err, orientation) {
        if(err) { return console.log('Error rotate') }

        if(orientation === 'LANDSCAPE') {
          Orientation.lockToPortrait();
          fullscreen = false;
        } else {
          Orientation.lockToLandscape();
          fullscreen = true;
        }

        fullscreenPlayer({
          fullscreen: fullscreen,
          width: height,
          height: width
        })
    });
  }

  updateProgressChanged() {
    const {currentTime} = this.props;
    this.setState({paused: false, pausedChromecast: true});
    currentTime > 0 && this.videoPlayer.seek(currentTime);
  }

  onBuffer({ isBuffering }: { isBuffering: boolean }) {
    this.setState({ isBuffering });
  }

  render() {
    let {data, resizeMode, width, height, fullscreen, isLogin, showChromecast} = this.props;

    let {
        currentTime, duration, paused, dataVideo, volume, hideProgress, isToggle,
        pausedChromecast, isChangeLink, loading} = this.state;

    let backgroundVideo = !fullscreen ? styles.backgroundVideo : styles.backgroundVideoFull;
    let backgroundHeightVideo = !fullscreen ? {height: width/16*9} : {height: height};
    let link = '';
    let iconPlayOrPause = paused ? 'play' : 'pause';
    let isTimeline = false;

    link = data.listDetail.content.link;

    let paddingTop = fullscreen ? 0 : 64;

    return (
      (!loading || data.listDetail == null) ?
        <View style={[styles.centering, styles.waiting]}><ActivityIndicator size="small" color="white" /></View>
      :
        <View style={[styles.container, {marginTop: paddingTop}]}>
          <TouchableWithoutFeedback onPress={() => this.displayProgress()}>
                <View style={[backgroundVideo, backgroundHeightVideo]}>
                  {
                      !showChromecast &&
                        <View style={[backgroundVideo, backgroundHeightVideo]}>
                          <Video source={{uri: link, mainVer: 1, patchVer: 0}}
                          ref={videoPlayer => this.videoPlayer = videoPlayer}
                          rate={this.state.rate}                     // 0 is paused, 1 is normal.
                          volume={Math.max(Math.min(1, volume), 0)}                  // 0 is muted, 1 is normal.
                          muted={false}                  // Mutes the audio entirely.
                          paused={paused}                // Pauses playback entirely.
                          resizeMode={resizeMode}            // Fill the whole screen at aspect ratio.
                          repeat={false}                  // Repeat forever.
                          progressUpdateInterval={250.0} // [iOS] Interval to fire onProgress (default to ~250ms)
                          onLoadStart={this.loadStart}   // Callback when video starts to load
                          onLoad={this.onVideoLoad}
                          onProgress={this.onProgress}      // Callback every ~250ms with currentTime
                          onEnd={this.onVideoEnd}            // Callback when playback finishes
                          onError={this.videoError}      // Callback when video cannot be loaded
                          onTimedMetadata={this.onTimedMetadata}
                          onBuffer={this.onBuffer}
                          playInBackground={false}
                          style={[backgroundVideo, backgroundHeightVideo]}
                          />
                            
                          <Progress isLive={data.listDetail.content.isLive} categoryId={data.listDetail.content.cat_id}
                          paused={paused} isLogin={isLogin}
                          playOrPauseVideo={this.playOrPauseVideo}
                          widthLayout={width} heightLayout={height}
                          changeLinkKaraoke={this.changeLinkKaraoke} link={link}
                          resizeModeControl={this.resizeModeControl}
                          duration={duration} currentTime={currentTime}
                          percent={flexCompleted} remain={flexRemaining}
                          onNewPercent={this.onProgressChanged.bind(this)}
                          fullscreen={fullscreen}
                          onInfo={this.onInfo}
                          isTimeline={isTimeline}
                          hideProgress={hideProgress} />
                           
                  }
                 {
                   showChromecast &&
                    <View style={[backgroundVideo, backgroundHeightVideo]}>
                       <ProgressChromecast isLive={data.listDetail.content.isLive} categoryId={dataVideo.cat_id}
                        widthLayout={width} heightLayout={height}
                         paused={pausedChromecast} isLogin={isLogin}
                         playOrPauseVideo={this.playOrPauseChromecastVideo}
                         changeLinkKaraoke={this.changeLinkKaraoke} link={link}
                         resizeModeControl={this.resizeModeControl}
                         duration={duration} currentTime={currentTime}
                         percent={flexCompleted} remain={flexRemaining}
                         onNewPercent={this.onProgressChanged.bind(this)}
                         onInfo={this.onInfo}
                         hideProgress={hideProgress} />
                     </View>
                   }
                 </View>
            </TouchableWithoutFeedback>

        </View>
    )
  }
}
`

When the application cast video for the first time, it cast video successfully. But the second time or more it can not cast video. Does my code have a problem?

**Comment by charliesbox** [comment]
it is really hard to read all the code pasted in one single place. Do you have a sample repo with it?

**Comment by petrbela** [comment]
Please upgrade to the latest version.
