### ISSUE TITLE
Can we create a custom receiver with this library

### ISSUE THREAD

**Issue by mehthabux** [react-native-google-cast/react-native-google-cast#334]
i want to play a DRM content, but I’m  not sure about how to do this. i have read that we need custom receiver in doing so
Is it possible to create custom receiver with this library ?

**Comment by petrbela** [comment]
Hi! This library helps you build a Google Cast *sender* app for iOS/Android. A *receiver*, on the other hand, is a HTML/JS webpage that the Google Cast device (i.e. Chromecast or Android TV) loads when the sender connects. See the official documentation at https://developers.google.com/cast/docs/web_receiver/basic on how to get started. Note that you'll need to register a developer account (and pay a one-time fee) at https://cast.google.com/publish
