### ISSUE TITLE
Error compiling version 4.1.0

### ISSUE THREAD

**Issue by jspasiuk** [react-native-google-cast/react-native-google-cast#336]
Today I get this error while compiling after the upgrade:

react-native-google-cast/android/src/main/java/com/reactnative/googlecast/types/RNGCHlsVideoSegmentFormat.java:5: error: cannot find symbol
import com.google.android.gms.cast.HlsVideoSegmentFormat;
                                  ^
  symbol:   class HlsVideoSegmentFormat
  location: package com.google.android.gms.cast
  
  Execution failed for task ':react-native-google-cast:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

Already tried to delete node_modules, a fresh install, clean gradlew and so on...

Any ideas? Anyone had the same issue ?

**Comment by petrbela** [comment]
Yeah good point, you need to update to `castFrameworkVersion = "20.0.0"`. I'll add it to release notes.
