### ISSUE TITLE
No CastButton appearing, GoogleCast is not a function.

### ISSUE THREAD

**Issue by DennisdeWitNL** [react-native-google-cast/react-native-google-cast#337]
Dear,

Congratulations on this module. However, this has been the most frustrating module I have ever used. There is little to no usable documentation.

I followed all the steps from Installation and Setup. I even used an example I found here https://gist.github.com/gergardiol/9ad7c73e19feebd910093ca46d5b37d3?fbclid=IwAR0fiz0pIj8er1o7bRQVG0Zw2w-bUzyqapUOcoOltQIc6UKwR6Iyj2RzWlQ

However, the Cast Button is not showing. When starting the app, it asks me for permission to scan my local network. I gave permission. There is simply no CastButton. VLC sees the ChromeCast and can play music, so it really is a problem in this module.

I did GoogleCast on ComponentDidMount, but it says GoogleCast is an undefined function. So I guess you would need to be a rocket scientist to use this module. I have used plenty of modules, all of them worked perfectly. This is the first module that makes me want to bang my head against a wall.

I set up this code:

import GoogleCast, { CastButton, useRemoteMediaClient } from "react-native-google-cast";

```
function MyComponent() {
  return <CastButton style={{ width: 24, height: 24 }} />

   // this will automatically rerender when client is connected
   const client = useRemoteMediaClient()

   if (client) {
     // ...
   }
}
```

Any ideas? I am assuming I don't need to call this function somewhere, as that is NOT part of the documentation. If I try to do so, I get an invalid hook error. Running the latest version with iOS 14. On Android, the button shows as expected.

**Comment by DennisdeWitNL** [comment]
Also, when trying to Cast on Android, it says client is not defined.

```
client.loadMedia({
  mediaInfo: {
    contentUrl:
      'https://commondatastorage.googleapis.com/gtv-videos-bucket/CastVideos/mp4/BigBuckBunny.mp4',
  },
})
```

(probably doing something wrong due to the lack of proper documentation)

**Comment by petrbela** [comment]
@DennisdeWitNL Please try to keep the conversation civil. You're using a free library, made by someone for free, in their free time.

So far, you've described two issues:

1. Adding Access Wifi Capability is described in [Setup](https://react-native-google-cast.github.io/docs/getting-started/setup) page step 2.
2. `can't find variable client` means you have a bug in your JavaScript code. Make sure you define the variable `client`, e.g. using `const client = useRemoteMediaClient()`.

I'm happy to help resolve issues with this library but please bear in mind this is not your personal support chat. I'm closing this issue as there doesn't seem to be any specific bug mentioned.
