### ISSUE TITLE
No visible @interface for 'RCTEventEmitter' declares the selector 'invalidate'

### ISSUE THREAD

**Issue by arnelisk** [react-native-google-cast/react-native-google-cast#339]
After bumping up the package to the newest version `4.1.0`, iOS build fails with the following error

![Screenshot 2021-06-22 at 13 25 54](https://user-images.githubusercontent.com/57091553/122909267-b2326b00-d35d-11eb-80ed-696efbf52ded.png)

I made sure to clean packages, cache and update pods before raising the issue. Any ideas what could this be? The new version works great on Android, therefore it would be nice to get to the bottom of this.

I would be glad to provide a fix, but at the moment I am not sure what is the cause for this error.

**Comment by patricklobo** [comment]
I have updated for react-native 0.64.2 and worked for me.

**Comment by petrbela** [comment]
Sorry my bad, I blindly followed Xcode's prompt and didn't realize this was added in the latest RN. I'll release a new version that makes it backwards compatible with order RN version.

**Comment by sntg-p** [comment]
Seems like this is happening again in 4.6.0. I'm using RN 0.63.5, should I open a new issue?

**Comment by anhquan291** [comment]
Hi guys, facing the same issue on the old RN 0.61. Any update for this guys?

**Comment by hypext1** [comment]
Same issue here, React Native 0.63.3. I have to use this version because it's the most recent that supports another library I'm using.

**Comment by react06** [comment]
+1

**Comment by chadyayoub** [comment]
try commenting the line [super invalidate];
