### ISSUE TITLE
Support for channels

### ISSUE THREAD

**Issue by madki** [react-native-google-cast/react-native-google-cast#34]
Hi,

It'd be great to have support for channels to send and receive custom messages to the receiver. 
Here are the links to relevant documentation: [Android](https://developers.google.com/cast/docs/android_sender_advanced#add_a_custom_channel), [iOS](https://developers.google.com/cast/docs/ios_sender_advanced#add_a_custom_channel).

Any plans for supporting this?

**Comment by charliesbox** [comment]
I don't have the time right now to add this feature. But feel free to open a PR to include this enhancement.

**Comment by madki** [comment]
Cool. Looking into it. Will send a PR soon.

**Comment by jimmywarting** [comment]
status?

**Comment by petrbela** [comment]
@jimmywarting @madki I've implemented support for custom channels in https://github.com/flextv/react-native-google-cast. Note that it's based on Cast SDK v3, and that the API will very likely change before the final release but if you're eager to try it, I'd welcome any feedback.

**Comment by petrbela** [comment]
This is now supported in the latest version.
