### ISSUE TITLE
Are we able to retrieve media info with version 3.4.1 or earlier?

### ISSUE THREAD

**Issue by tombotley** [react-native-google-cast/react-native-google-cast#343]
With version 4 we have the getCurrentCastSession and getMediaStatus which are useful if for instance a user returns to the video component having navigated away or closed the app while casting. I can retrieve the custom data given when the cast was loaded and see which video they are casting and handle the UI accordingly. Is there any way to retrieve this data in version 3.4.1? I can only see getCastState which only tells me if I am connected to a current session.

**Comment by petrbela** [comment]
Hi Tom! I'm not sure actually. But as all the new features go into v4, I think it'd be easier and more future-proof for you to upgrade to the latest version. Is there a reason you can't upgrade?

**Comment by tombotley** [comment]
Hi Petr! I'm stuck on issue [#317](https://github.com/react-native-google-cast/react-native-google-cast/issues/317) with v4 at present (no media selected).

**Comment by hosek** [comment]
I have it for both, but limited info retrieved on v3, I really recommend you to move to v4, we are doing the same, and those versions cant be compared, great work @petrbela !
Inspiration what to add for getting metadata after application resumed or second client joined the session
====================== **v3** =========================
**iOS:**
https://github.com/24i/react-native-google-cast/blob/master/ios/RNGoogleCast/RNGoogleCast.m#L387
also if you want to get notified that data changed:
https://github.com/24i/react-native-google-cast/blob/master/ios/RNGoogleCast/RNGoogleCast.m#L48
https://github.com/24i/react-native-google-cast/blob/master/ios/RNGoogleCast/RNGoogleCast.m#L544
**Android:**
https://github.com/24i/react-native-google-cast/blob/master/android/src/main/java/com/reactnative/googlecast/GoogleCastModule.java#L213
metadataChange
https://github.com/24i/react-native-google-cast/blob/master/android/src/main/java/com/reactnative/googlecast/GoogleCastRemoteMediaClientListener.java#L57

====================== v4 =========================
not much to do, just ask for data :) 
https://github.com/24i/react-native-google-cast/commit/5c0ce7d22ec54d631b29d40158106add0d7c6e2d
