### ISSUE TITLE
M3U8 format when adaptive bitrate stops streming session.

### ISSUE THREAD

**Issue by iSued** [react-native-google-cast/react-native-google-cast#345]
I'm streaming this way:
         client
              .loadMedia({
                mediaInfo: {
                  contentUrl:uri.m3u8
                  contentType: "application/x-mpegURL",
                  streamType: "live" ,
                },
              })
           where client is  =>  const client = useRemoteMediaClient();
           
From the server i'm using, depending on connection, i receive a different quality of the video, i tried to use an url of a non changing bitrate m3u8 video and it works. 

I have the issue only when the bitrates change.

**Comment by znoooo** [comment]
Same problem here

**Comment by petrbela** [comment]
I'm not sure I understand. What is the problem? Does it stop streaming altogether? Or does it change quality?

**Comment by iSued** [comment]
It is not a Streaming but buffered video, and yes stop the cast. It seems as it receives just some parts of the video.

To use streamType: "live" ,i had to import MediaStreamType because it is declared as enum and i did 
streamType = MediaStreamType.buffered


But for the proprerty    hlsVideoSegmentFormat?: MediaHlsVideoSegmentFormat it does not import MediaHlsVideoSegmentFormat.

**Comment by petrbela** [comment]
> It is not a Streaming but buffered video, and yes stop the streaming. It seems as it receives just some parts of the video.

That is generally a problem with the receiving device not having enough downloading speed. I've also noticed the first generation of Google Cast devices don't have powerful enough CPUs and may sometimes freeze and disconnect. Unfortunately, I'm not sure there's anything this library can do to improve that.

> To use streamType: "live" ,i had to import MediaStreamType because it is declared as enum and i did
> streamType = MediaStreamType.buffered
> 
> But for the proprerty hlsVideoSegmentFormat?: MediaHlsVideoSegmentFormat it does not import MediaHlsVideoSegmentFormat.

You're right, I forgot to export `MediaHlsVideoSegmentFormat` from the package. Will fix it in the next version.

**Comment by iSued** [comment]
As i said in the first question: 
-I have this problem only when from the server i receive different qualities of the same video, that in the server are divided in sub-folders of master (different bit-rate => 1 video for 720p , 1 video for 480 etc....)
-I tried to return only the 720p video and not multibit rate i don't have this problem. 

Have you ever encountered a similar problem? Do you have any advice of another way i can try to cast.
The device i'm using as chromecast is Xiaomi Mi TV Stick 

Thank you for attention and for previous answers.

P.S.
If it can be helpful i can send you an example of how is managed in BE the multibit-rate (PHP)

**Comment by iSued** [comment]
As i said in the first question: 
-I have this problem only when from the server i receive different qualities of the same video, that in the server are divided in sub-folders of master (different bit-rate => 1 video for 720p , 1 video for 480 etc....)
-I tried to return only the 720p video and not multibit rate i don't have this problem. 

Have you ever encountered a similar problem? Do you have any advice of another way i can try to cast.
The device i'm using as chromecast is Xiaomi Mi TV Stick 

Thank you for attention and for previous answers

P.S. 
I'm attaching an example of Master m3u8
`#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=688000,RESOLUTION=640x360
360p.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1400000,RESOLUTION=842x480
480p.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2800000,RESOLUTION=1280x720
720p.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5000000,RESOLUTION=1920x1080
1080p.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=9000000,RESOLUTION=3840x2160
4k.m3u8
`

**Comment by petrbela** [comment]
I haven't specifically worked on this problem. I haven't used the Mi TV stick so I'm not sure about its performance. However, it seems like it's not a react-native-specific question, so I'd recommend you try discussing this on general Google Cast (or HLS streaming) forums. I'm sorry I can't help you more here right now but feel free to follow up with any solutions you find.

**Comment by hosek** [comment]
@iSued I would try it with original CastVideo app ([Android](https://github.com/googlecast/CastVideos-android) or [iOS](https://github.com/googlecast/CastVideos-ios)) to be sure that's its not related to the native framework itself
eg edit this file, host it on your server (can be local)
https://commondatastorage.googleapis.com/gtv-videos-bucket/CastVideos/f.json
and change url to the new one here:
https://github.com/googlecast/CastVideos-android/blob/master/src/com/google/sample/cast/refplayer/browser/VideoBrowserFragment.java#L53

if you can reproduce it there, raise issue in [chromecast bug tracker](https://issuetracker.google.com/issues?q=componentid:190205%2B)
if not, then its library issue and we need to investigate what was wrong

**Comment by iSued** [comment]
UPDATE!

We tried with chromecast it seems to be a problem non related to the library.
