### ISSUE TITLE
[ANDROID] No Cast Devices Available

### ISSUE THREAD

**Issue by lcevasco-antorcha** [react-native-google-cast/react-native-google-cast#346]
Hi! I have a problem with CastButton in Android. In iOS, the button works and found devices, but in android the cast state is no devices available.

I completed all the steps in installation, setup, and checked if google play services is available.
Im using the default receiver, android 29 api and react native 0.62.

here is the MainActivity:
```
public class MainActivity extends ReactActivity {
	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		CastContext.getSharedInstance(this);
		RNBootSplash.init(R.drawable.bootsplash, MainActivity.this);
	}
```

and the castButton:

```
 useEffect(() => {
    getCourseRequest(courseId);
    navigation.setOptions({
      headerRight: () => <CastButton style={{ width: 50, height: 50, tintColor: THEME.main }} />
    });
  }, []);
```

Please let me know if I can bring more info to the issue, thanks!!

**Comment by petrbela** [comment]
Hi! What Android device are you using for testing? And did you set `castFrameworkVersion` in `build.gradle`?

**Comment by lcevasco-antorcha** [comment]
Thanks for the quick answer! im using google pixel 3a and yes I do

```
implementation "com.google.android.gms:play-services-cast-framework:${safeExtGet('castFrameworkVersion', '+')}"
  [...]
def safeExtGet(prop, fallback) {
  rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}
```

**Comment by lcevasco-antorcha** [comment]
Update: I try with a physical device and its working now. Maybe was something with de google play services in the AVD ? idk but is working good in physical device.

**Comment by petrbela** [comment]
Yeah, I haven't been able to connect from an emulator recently. So everything works as it should on the device?

**Comment by hosek** [comment]
Afaik you cant cast from Android emulator because its using own subnetwork so it cant see the chromecast device on same LAN (discovery packets cant go through), you have to use real device, or iOS simulator

**Comment by petrbela** [comment]
Yeah, I think it was working when I was using Genymotion as they do automatic NAT. However, they don't support M1 yet, and I'm not sure how to configure NAT for AVD.
