### ISSUE TITLE
No video on TV casting

### ISSUE THREAD

**Issue by tuneerclixlogix** [react-native-google-cast/react-native-google-cast#349]
const client = useRemoteMediaClient();
Client is null or the blank object 

![image](https://user-images.githubusercontent.com/72122766/127630001-93a330c3-3c6b-4f55-a677-b4e9497fd4cd.png)
which gives me this error on `client.loadMedia` or `client.getMediaStatus()`

`Error: No remoteMediaClient!`

I also logged the castState in `useEffect` and the castState is connecting and does not change to connected ever

```ts
const castState = useCastState();
useEffect(() => {
  console.log('castState ', castState);
}, [castState]);
```

**Comment by petrbela** [comment]
The user needs to connect to a device first using the `CastButton`; only after a session has been established the `client` becomes available. See https://react-native-google-cast.github.io/docs/getting-started/usage

Btw in the screenshot, the `client` is defined. Please post a full example if you want to report a bug. Also, see https://react-native-google-cast.github.io/docs/getting-started/troubleshooting on how to resolve connection issues.

**Comment by tuneerclixlogix** [comment]
@petrbela 
I created a demo project and in that everything is working fine, I don't know whats happening in my current project.
I can see the session is created as i was able to increase and decrease the volume of tv on pressing the cast button, so the connection is made but the video is not played on the TV.
I have the following useEffect which i think should trigger when the device is connected but it is not working
`
const client = useRemoteMediaClient();
useEffect(() => {
    if(!client) {
      GoogleCast.getDiscoveryManager()
    }
    console.log('client changed ', client)
    const started = client?.onMediaPlaybackStarted(() =>
      console.log("playback started")
    );
    const ended = client?.onMediaPlaybackEnded(() =>
      console.log("playback ended")
    );

    if(client) { 
      console.log("loading media in client")
      client?.loadMedia({
        mediaInfo: {
          contentUrl:
            "https://commondatastorage.googleapis.com/gtv-videos-bucket/CastVideos/mp4/BigBuckBunny.mp4",
        },
      })
    }

    return () => {
      started?.remove();
      ended?.remove();
    };
  }, [client]);
  `
  Can it be because of any integration issue ? the gradle version or something ?

**Comment by tuneerclixlogix** [comment]
Okay, i got what was causing this issue. It was because of tools:node="replace" in AndroidManifest . I removed it and now it is working.

**Comment by petrbela** [comment]
Interesting. Is it similar to https://github.com/firebase/quickstart-android/issues/477? I'll add it to Troubleshooting.

**Comment by tuneerclixlogix** [comment]
Yes, it was also because of tools:node="replace"

**Comment by petrbela** [comment]
@sajibsaha4647 Please check out [Troubleshooting](https://react-native-google-cast.github.io/docs/getting-started/troubleshooting)
