### ISSUE TITLE
Android app crash

### ISSUE THREAD

**Issue by undef1ned** [react-native-google-cast/react-native-google-cast#36]
Im getting hundreds of such error reports in the Bugsnag console

> java.lang.NullPointerExceptioncom.google.android.gms.common.zzg.isGooglePlayServicesAvailable:-1

> Attempt to invoke virtual method 'android.content.pm.PackageManager android.content.Context.getPackageManager()' on a null object reference

> Unknown:-1com.google.android.gms.common.zzg.isGooglePlayServicesAvailable	
> Unknown:-1com.google.android.gms.common.GooglePlayServicesUtil.isGooglePlayServicesAvailable	
> VideoCastManager.java:238com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.initialize	
> GoogleCastModule.java:215com.googlecast.GoogleCastModule$3.run	
> Handler.java:739android.os.Handler.handleCallback	
> Handler.java:95android.os.Handler.dispatchMessage	
> Looper.java:135android.os.Looper.loop	
> ActivityThread.java:5343android.app.ActivityThread.main	
> Method.java:-2java.lang.reflect.Method.invoke	
> Method.java:372java.lang.reflect.Method.invoke	
> ZygoteInit.java:905com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run	
> ZygoteInit.java:700com.android.internal.os.ZygoteInit.main

Any idea what it can be? May-be some kind of Google Play Services version incompatibility? Any suggestions how to fix that?

**Comment by fabiancarlos** [comment]
looking for that too

**Comment by petrbela** [comment]
Please upgrade to the latest version and check if it's still happening.
