### ISSUE TITLE
Issues with react-native-google-cast in Xcode 13 on Apple Silicon 

### ISSUE THREAD

**Issue by ned-oos** [react-native-google-cast/react-native-google-cast#371]
When building my React-Native project in XCode on an iOS simulator I get the following error:

in /Users/username/WebstormProjects/project_name/ios/Pods/google-cast-sdk-no-bluetooth/GoogleCastSDK-ios-4.6.1_static/GoogleCast.framework/GoogleCast(GCKCastUISubcontext_5869bf02863071b41dbcece03a9cf301.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/username/WebstormProjects/project_name/ios/Pods/google-cast-sdk-no-bluetooth/GoogleCastSDK-ios-4.6.1_static/GoogleCast.framework/GoogleCast' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I currently have the version 4.1.2 installed with React Native version 0.64.2, in Xcode 13 on a Mac with Apple Silicon. My pod file has the following in it:

pod 'react-native-google-cast/NoBluetooth', path: '../node_modules/react-native-google-cast/ios/'
  pod 'google-cast-sdk-no-bluetooth'

**Comment by gavrichards** [comment]
I've just experienced this too on my new Macbook Pro. Relieved to see it's not just me, but would certainly appreciate a fix soon :)
Many thanks!

**Comment by Girum** [comment]
Have you used the excluded architectures, using arm64? It may resolve the issue. I'm running on Macbook Air M1 Xcode 13, and it runs on the first try: 

![Screen Shot 2021-11-05 at 10 03 10](https://user-images.githubusercontent.com/1349300/140514568-a5318089-f6b1-4c65-bd0e-a84bbc6c7d9f.png)

**Comment by petrbela** [comment]
Hope you've managed to solve it (I haven't run into the problem). In any case, I don't think it's an issue with this library, so I'm closing it.
