### ISSUE TITLE
Button appears but is not clickable (Android 7.0) 

### ISSUE THREAD

**Issue by wemow** [react-native-google-cast/react-native-google-cast#372]
The Chromecast button is showing but nothing happens on click, it's not wrapped into anything, it is green like the first time but I can't get it to work.

Any ideas?

**Comment by anhkieet** [comment]
@yemd I am having this issue. Have you addressed it?

**Comment by yemd** [comment]
> @yemd I am having this issue. Have you addressed it?

Yes, I built a custom button it works perfectly.
You can find an example at the bottom of this page https://react-native-google-cast.github.io/docs/components/CastButton

**Comment by anhkieet** [comment]
> > @yemd I am having this issue. Have you addressed it?
> 
> 
> 
> Yes, I built a custom button it works perfectly.
> 
> You can find an example at the bottom of this page https://react-native-google-cast.github.io/docs/components/CastButton

Let me try, thank you
