### ISSUE TITLE
App launch crash in RNGCCastContext java ( Android Only )

### ISSUE THREAD

**Issue by krunalbad** [react-native-google-cast/react-native-google-cast#377]
App launch crash in RNGCCastContext java ( Android Only )

This crash happens at the launch of more than 90% of the Samsung Devices. As soon as the app is launch this crash happens.

Any solution for this?

![App launch crash in RNGCCastContext java ( Android Only )](https://user-images.githubusercontent.com/45413622/141243405-39b10ecf-4b57-4288-a2e2-02c5f9cee030.png)

**Comment by hungvu193** [comment]
any update on this, I'm facing this issue on my SamSung device too, other devices work well

**Comment by hungvu193** [comment]
@krunalbad  try this: https://stackoverflow.com/questions/50313967/google-play-services-are-updating-error-on-release-not-emulator-google-play/50327544#50327544

**Comment by alejandrorangel** [comment]
I think this problem is related to #367
