### ISSUE TITLE
App crashed on (RNGCCastSession.java:298) on Android only

### ISSUE THREAD

**Issue by sohaila786** [react-native-google-cast/react-native-google-cast#381]
Application got crashed as it launched. This is happening mostly on Android 10, Android 5 and Android 6. Here is screen shot is attached of stack trace from Firebase
<img width="1125" alt="Screenshot 2021-12-07 at 2 41 49 PM" src="https://user-images.githubusercontent.com/42419074/145005326-11069e2b-1750-4a88-b62e-13a280798378.png">
.

**Comment by alejandrorangel** [comment]
There is a PR #367  ready to be merge
