### ISSUE TITLE
App Crash on Android 12

### ISSUE THREAD

**Issue by mohammad-alrahahleh** [react-native-google-cast/react-native-google-cast#382]
App Crashes after selecting a device on android 12 , even though it works just fine on android 11 and lower.

"react": "17.0.2",
"react-native": "0.66.3",
"react-native-google-cast": "4.1.2",

no react error , just a crash and the android (ads logs) states the following : 
`java.lang.IllegalArgumentException: com.studio.obe: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.`

**Comment by petrbela** [comment]
Hi! Make sure you update the `castFrameworkVersion` in `build.gradle` to 20.1.0 or newer (currently 21.0.0). See https://developers.google.com/cast/docs/release-notes#november-16,-2021

I'll update the documentation.
