### ISSUE TITLE
Require cycle: node_modules/react-native-google-cast/src/index.ts

### ISSUE THREAD

**Issue by yemd** [react-native-google-cast/react-native-google-cast#388]
I've had a new warning appearing in the RN console since an RN upgrade, 

`Require cycle: node_modules/react-native-google-cast/src/index.ts -> node_modules/react-native-google-cast/src/api/CastContext.ts -> node_modules/react-native-google-cast/src/api/SessionManager.ts -> node_modules/react-native-google-cast/src/api/CastSession.ts -> node_modules/react-native-google-cast/src/api/RemoteMediaClient.ts -> node_modules/react-native-google-cast/src/index.ts
`
  `LogBox.ignoreLogs(['Require cycle'])
`

It's not critical but any help fixing this would be appreciated

**Comment by petrbela** [comment]
Good catch! I'll push a fix.

**Comment by yemd** [comment]
Much appreciated!
