### ISSUE TITLE
Android, no cast button

### ISSUE THREAD

**Issue by fraubungle** [react-native-google-cast/react-native-google-cast#395]
Hi, I am unable to get the bast button to show on an Android Emulator. IOS works fine but for the life of me I cant get it to show up on Android.

I have tried both npx react-native init and expo init, with both being setup with the corresponding instructions and both working on IOS with the cast button showing and finding a cast device but Android not throwing me an error (From what I can see) but the Cast button just not rendering.

I am using a M1 Mac Mini, Visual Studio code, macOS Monterey 12.0.1 and with all of the instructions to install the other 50 billion developer tools followed correctly.

I hope I am just being really dum and someone can just say what I have done wrong or if you need more information, logs please let me know and I will past that here.

**Comment by petrbela** [comment]
Hey! Unfortunately, the Android emulator cannot discover network Cast devices. https://github.com/react-native-google-cast/react-native-google-cast/issues/346#issuecomment-880090479

I'll make it clearer in the documentation.

**Comment by fraubungle** [comment]
@petrbela So just to clarify that would mean the Cast Button would not show at all in the emulator also?

**Comment by petrbela** [comment]
Btw it *might* be possible to fix the emulator by changing NAT settings but I haven't tried that approach. You can start https://developer.android.com/studio/run/emulator-networking and please report back if you succeed :)

**Comment by fraubungle** [comment]
Hi @petrbela I managed to get a build up on to EAS for both Android and IOS but again the Android Version does not have the cast button but the IOS version does.

I can send you a link for the EAS build if you want.

**Comment by fraubungle** [comment]
IOS
![IOS](https://user-images.githubusercontent.com/695833/157116908-3bc215d0-2f20-4e4c-8231-b61e50265fb3.jpg)

Android:
![Android](https://user-images.githubusercontent.com/695833/157116972-2148a740-789f-4547-9582-af15d58a09ed.png)

**Comment by petrbela** [comment]
This was most likely caused by the default color on Android being white and thus appearing invisible, which has now been clarified in the docs.
