### ISSUE TITLE
Crash on expo run:android

### ISSUE THREAD

**Issue by fraubungle** [react-native-google-cast/react-native-google-cast#397]
Hi,

I have been doing some more testing and set up a new project via expo init but as soon as I install react-native-google-cast if I try expo run:android i get the following error, expo run:ios works fine

> Task :react-native-google-cast:compileDebugJavaWithJavac FAILED
/Users/markellis/Development/_ReactNative/monkey/node_modules/react-native-google-cast/android/src/main/java/com/reactnative/googlecast/types/RNGCDevice.java:27: error: cannot find symbol
    final WritableArray capabilities = new WritableNativeArray();
                                           ^
  symbol:   class WritableNativeArray
  location: class RNGCDevice

**Comment by petrbela** [comment]
Sorry, fixed in 4.2.2! Thanks for reporting it.
