### ISSUE TITLE
Android Error 

### ISSUE THREAD

**Issue by mezalejandro** [react-native-google-cast/react-native-google-cast#399]
In Android i have the error:
Cannot read property CAST_STATE_CHANGED of null
<img width="457" alt="Captura de Pantalla 2022-03-11 a la(s) 11 35 06" src="https://user-images.githubusercontent.com/568141/157887800-8cc538a6-41cd-40f6-9bd8-9af3235a1095.png">
<img width="236" alt="Captura de Pantalla 2022-03-11 a la(s) 11 35 22" src="https://user-images.githubusercontent.com/568141/157887841-72dae893-4f04-4a6a-95cf-5d639e025b28.png">

**Comment by petrbela** [comment]
You need to follow the setup instructions and rebuild the native project with the react-native-google-cast package.

**Comment by mezalejandro** [comment]
Hello @petrbela this error occurs in an android emulator when i want to watch a video

**Comment by petrbela** [comment]
Again, you need to build the native project after adding the library. Otherwise `Native` will be null.
