### ISSUE TITLE
[EXPO] bare doesn't work

### ISSUE THREAD

**Issue by AdminGrupoZoe** [react-native-google-cast/react-native-google-cast#404]
hi guys, I try create and run project with expo 44 bare like this example https://github.com/react-native-google-cast/RNGCExpo but the cast button doesn't work, the app don't find devices avaliable anyone pass for this isso too?

**Comment by petrbela** [comment]
Try going through the tips here https://react-native-google-cast.github.io/docs/getting-started/troubleshooting

**Comment by AdminGrupoZoe** [comment]
> Try going through the tips here https://react-native-google-cast.github.io/docs/getting-started/troubleshooting

thanks,
