### ISSUE TITLE
requireNativeComponent: "RNGoogleCastButton"

### ISSUE THREAD

**Issue by martinlp05** [react-native-google-cast/react-native-google-cast#405]
Hola buenos noche, intente implementar react-native-google-cast, pero al intentar correrlo con expo, me genera un error en la consola: me podrán dar una mano para resolverlo. Gracias.
Git del Proyecto: https://github.com/martinlp05/Chromecast2 
Emulador Android 11

Error: 
**Invariant Violation: requireNativeComponent: "RNGoogleCastButton" was not found in the UIManager.**

This error is located at:
    in RNGoogleCastButton (created by CastButton)
    in CastButton (created by MyComponent)
    in MyComponent (created by App)
    in RCTView (created by View)
    in View (created by App)
    in App (created by ExpoRoot)
    in ExpoRoot
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
at node_modules\react-native\Libraries\LogBox\LogBox.js:149:8 in registerError
at node_modules\react-native\Libraries\LogBox\LogBox.js:60:8 in errorImpl
at node_modules\react-native\Libraries\LogBox\LogBox.js:34:4 in console.error
at node_modules\expo\build\environment\react-native-logs.fx.js:27:4 in error
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:104:6 in reportException
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:172:19 in handleException
at node_modules\react-native\Libraries\Core\setUpErrorHandling.js:24:6 in handleError
at node_modules\expo-error-recovery\build\ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0
at node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
at node_modules\regenerator-runtime\runtime.js:294:29 in invoke
at node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
at node_modules\regenerator-runtime\runtime.js:155:27 in invoke
at node_modules\regenerator-runtime\runtime.js:165:18 in PromiseImpl.resolve.then$argument_0
at node_modules\react-native\node_modules\promise\setimmediate\core.js:37:13 in tryCallOne
at node_modules\react-native\node_modules\promise\setimmediate\core.js:123:24 in setImmediate$argument_0
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:123:14 in _callTimer
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:177:14 in _callImmediatesPass
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:437:30 in callImmediates
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:388:6 in __callImmediates
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:132:6 in __guard$argument_0
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:365:10 in __guard
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:131:4 in flushedQueue

**Comment by petrbela** [comment]
Hola! Make sure you [build a native app using `expo run:android`](https://docs.expo.dev/workflow/customizing/#developing-apps-with-custom-native-code). Also check out the example expo project with google cast https://github.com/react-native-google-cast/RNGCExpo

**Comment by petrbela** [comment]
Also, there are some issues with the Android emulator https://react-native-google-cast.github.io/docs/getting-started/troubleshooting which you might run into later; testing with a real Android device is better (iOS simulator works fine, though).

**Comment by martinlp05** [comment]
Perfecto ya lo pude solucionar.
Gracias.
