### ISSUE TITLE
[iOS] No devices available

### ISSUE THREAD

**Issue by nriccar** [react-native-google-cast/react-native-google-cast#408]
Hello, thanks for reading in advance.

I tried all the configs possible. Even tried to change ios version to 12 on podfile and on xcode deployment target, and I still get the No devices available. 

Im testing on a real device, iPhone 12, with ios 15.3.1.

I also added the necessary keys to the info.plist:
![Screenshot 2022-04-11 at 17 19 45](https://user-images.githubusercontent.com/49196314/162771989-3a7510a7-e359-4150-9f9e-67bf476bb04b.png)

I added the capability Access Wifi Information, 

Any guess? Thanks!

**Comment by nriccar** [comment]
I even tried the example project and its not working as well! Checked the app settings and its allowed to scan in the local network.

**Comment by petrbela** [comment]
Can you check https://react-native-google-cast.github.io/docs/getting-started/troubleshooting

**Comment by nriccar** [comment]
Hey! I did check all of those steps, and several times.. Can it be that the example does not work?

**Comment by nriccar** [comment]
Thanks for the response. I tried to cast on my phones with another apps and they work, so, is it from my network?
Tested on Android and its not finding devices as well

**Comment by petrbela** [comment]
Unfortunately, I don't have any more advice to give you. You can try the other example projects and see if they work, or ask on general Google Cast forums. The "no devices available" state is very hard for me to reproduce as it's specific to your Cast device and network. Rest assured that many people use this package in production; however, the underlying Google Cast SDK doesn't make it particularly easy to provide troubleshooting feedback for a specific case. Also note that some other apps (e.g. YouTube or Spotify) don't always use the native Cast SDK protocol when casting to specific devices (namely TVs), even if they use the same Cast icon; that means you wouldn't be to cast to them using this library. Are you testing with Chromecast or some other device?
