### ISSUE TITLE
Session Suspended when app goes to background mode

### ISSUE THREAD

**Issue by ipnet-me** [react-native-google-cast/react-native-google-cast#409]
Hello, I have media player app. It works fine. I have a task to make media control centre when screen is locked. My problem is -after app goes to background mode chrome cast "SessionSuspended" and I can't  send command to castChannel. But after I open app again it "onSessionResumed" and everything is working  again. Is anyone know, how not allow chrome cast go to suspend mode in background.

**Comment by petrbela** [comment]
On iOS, for an app to keep running while in the background, it needs to have one of the background modes enabled. The logical one would be to use [background audio](https://developer.apple.com/documentation/avfoundation/media_playback_and_selection/creating_a_basic_video_player_ios_and_tvos/enabling_background_audio?language=objcaudio"). However, as the Cast sender (i.e. the iOS app) doesn't actually play any audio itself, you might have a hard time convincing the app review team that the background audio mode is necessary. If they don't approve it, I don't think there's a way to build a real-time widget in the control center.

(On Android the situation is different as the device is part of the media framework which provides a native widget in the notification center.)

**Comment by petrbela** [comment]
Oh you'll need to set `options.suspendSessionsWhenBackgrounded = false` when initializing the CastContext in `AppDelegate` https://developers.google.com/cast/docs/reference/ios/interface_g_c_k_cast_options#a0edf44953049a7d888847745a387c9dc

**Comment by ipnet-me** [comment]
Petr Bela, thank you very much for your time and help. Yeah, it working now!

**Comment by vishalhyperspace** [comment]
Session disconnect when locking device in iOS.
When I lock the screen in the real device (press the lock button) and then I open the app again the session gets disconnected
I have already set `options.suspendSessionsWhenBackgrounded = false` in AppDelegate.
Please help to fixed it.
Thanks in advance.

**Comment by petrbela** [comment]
@vishalhyperspace The app needs to have permission to run in the background https://github.com/react-native-google-cast/react-native-google-cast/issues/409#issuecomment-1111622200

**Comment by vishalhyperspace** [comment]
@petrbela  I have already added permission for background. it works fine in the background but when i lock screen and come back after 30 sec it will disconnect.

**Comment by Luan2121** [comment]
@petrbela I'm having the same issue here, after I enabled several background modes and it's only working when I lock the iphone and unlock it immediately if I last more than a minute the session dies, I've been reading about the issue and the only solution I've found it's https://stackoverflow.com/questions/45918375/cast-session-getting-suspended-due-to-gckconnectionsuspendreasonnetworknotreach and & this one https://stackoverflow.com/questions/38897611/how-to-keep-gckcastsession-alive-when-app-goes-to-background/49743668#49743668 however I don't know how to implement this kind of solutions, Can anybody help me :(

**Comment by dianamelga** [comment]
@Luan2121 having the exact same issue as you, did you found a workaround?
how about you @vishalhyperspace ?
