### ISSUE TITLE
Example doesn't list chromecasts

### ISSUE THREAD

**Issue by carlojoerges** [react-native-google-cast/react-native-google-cast#41]
Hi, I'm having problems getting the library to list available devices. When I run the example, it shows that chromecasts are around, but when I press the 'Show chromecasts' button nothing happens. 

I've debugged the issues a fair a bit and it seems that the onCastDeviceDetected function is never called. It randomly seems to work once and then stops working indefinitely.

**Comment by charliesbox** [comment]
iOS or Android? I'm working on a fix that I found on android

**Comment by carlojoerges** [comment]
Ah sorry, yea this is on android

**Comment by RyderMS** [comment]
I was having the same issue on Android as well. Could you share/link your fix @charliesbox

**Comment by charliesbox** [comment]
Sure, it is on `upgrade-google-cast` branch. I already opened a PR, but I'm having some issues testing iOS on my local environment.

Could you help me verify is working right on both of them?

**Comment by RyderMS** [comment]
I am setup to test Android, let me give it a whirl.

**Comment by carlojoerges** [comment]
Unfortunately didn't seem to fix the issue for me. I built the example from the branch on android

**Comment by charliesbox** [comment]
@carlojoerges still can't see any chromecast around? Could you give further details about your environment?

Testing on an emulator or a mobile device?

**Comment by charliesbox** [comment]
thanks @RyderMS

**Comment by carlojoerges** [comment]
The last version I only tested on the Android Studio emulator, on Mac. Previous versions (which had the same issue with) I tested on both the emulator and a connected Android device (Nexus 5). In those previous tests, running it on the emulator and on the device did not make a difference. 

To see wether there's something odd going on with the castcompanion library I also compiled the https://github.com/googlecast/CastVideos-android-v2 demo application. That worked fine on the emulator. Even though they're using the cast button. So they're not relying on the onCastDeviceDetected function to list devices. The CastVideos app showed both my Chromecast Audio and a regular Chromecast device.

**Comment by charliesbox** [comment]
will take a further look then :)

**Comment by carlojoerges** [comment]
thanks @charliesbox! let me know if you have anything to test. happy to help out

**Comment by Diskiddin** [comment]
I am experiencing the same issue, however I have done some digging and found an interesting sequence of events that causes the chromecasts to list.

After leaving the App running for some time the chromecast route will randomly be removed triggering the onRouteRemoved and onCastDeviceDetected methods, consequently adding the route again but this time adding the device to the device list. After this occurs the rest of the functions work properly, however if I restart the app the problem resurfaces. 

Attached I have a log of the events, hopefully this helps with a fix for the problem.
[Android Monitor events.pdf](https://github.com/charliesbox/react-native-google-cast/files/1126345/Android.Monitor.events.pdf)

**Comment by charliesbox** [comment]
Thanks @Diskiddin ! Currently I'm working in refactoring the entire library, focused especially in android and the new chromecast sdk.

Will take a look to the logs, they are great to better debug this case :)

**Comment by charliesbox** [comment]
Folks, could you try with this PR? I create a new example and did some changes to fix the bugs.

I test it both android and iOS. Need a second opinion about it.

If everything goes well, I will release a new version next week.

https://github.com/charliesbox/react-native-google-cast/pull/42

**Comment by jaredgei** [comment]
Pulled your latest, and still having the same issue on android - the event happens, with devices_available: true, but getDevices() sends back an empty array.

**Comment by charliesbox** [comment]
@jaredgei could you provide the following info?

- Real device or emulator?
- If real device, which one is?
- Android version

**Comment by jaredgei** [comment]
Sure, am running on a Galaxy S7 on Android 7.0

**Comment by charliesbox** [comment]
cool, will take a look

**Comment by Diskiddin** [comment]
Is there a way to manually add a device to the device list in JavaScript? I can't get devices to list so it makes testing my implementation difficult, but if I could manually add the device that would help so much. I can see the device in android monitor and can see it's ID and name so I assume I could call some function or create some device object and work from there? I'm not sure.

Thanks!

**Comment by Simba14** [comment]
@charliesbox Did you manage to crack this issue? 🙏

**Comment by pudility** [comment]
@Simba14 @charliesbox It seems like this is still an issue. I ran the example and got the same issue. I have tested this on both a google pixel and google pixel emulator - both android 8. I tested with react native version 0.49.3 and react-native-google-cast version 1.3.0. Here is a gif of the issue if it helps at all:

![gif](https://media.giphy.com/media/l4EpayLgJoM7w3C9O/giphy.gif)

**Comment by petrbela** [comment]
Please upgrade to the latest version, it handles discovery automatically.
