### ISSUE TITLE
Is there any option to update metadata after loadMedia?

### ISSUE THREAD

**Issue by Robiullah2244** [react-native-google-cast/react-native-google-cast#428]
My app is calling an API to get the album art image URL. So for that, I need to update the images in the metadata after the loadMedia.

**Comment by petrbela** [comment]
I think the easiest option would be to fetch the album image URL with the original API call that fetches the items. You could also fetch the metadata dynamically before `loadMedia` (though that would add a short delay).

----------------------------
If I were you, I'd try to avoid having to update the metadata *after* the media has already been loaded; however, here are some thoughts:

I'm not sure if you can update the metadata of the currently playing item without restarting the playback (though you could try setting `startTime` to skip to the current position).

If the item is still in the queue, there are some [queue methods](https://developers.google.com/cast/docs/reference/ios/interface_g_c_k_remote_media_client#a0989ae7936c3c21cc7ada6983851843f) in the native SDKs that are currently not exposed in the RN client; but I'm guessing you're not using a queue, so this doesn't matter.

Obviously, if you create a custom receiver, you'd be able to send messages freely, and render the on-screen metadata however you like. In fact, [this custom receiver example](https://developers.google.com/cast/docs/web_receiver/core_features#message_interception) fetches additional metadata from an API before loading the actual item.

**Comment by Robiullah2244** [comment]
Hi @petrbela, Thank you so much for the quick response. This is a radio app. When music is changed I get the album name and artist name from the radio station but no album art image. For that when the music is changed and as soon as I get the album name and artist name from the radio I call another API to get the image. And then I have to update the metadata. 

So for now, I am calling the `loadMedia` again. But, the radio playing is interrupted for 2-3 seconds after each music is changed on the radio in the cast device.

**Comment by petrbela** [comment]
I'm not sure if I fully understand your workflow but what I wrote above should still apply.

**Comment by rpadilla6** [comment]
Hi @Robiullah2244, did you end up needing to go a native route for this? I also have a radio app and am running into similar issues as yourself, I'd like to update the metadata as items update without interrupting the stream.

**Comment by petrbela** [comment]
@rpadilla6 You don't need to write any native code. In fact, you probably don't need to make any change to the sender (RN) app at all. If I understand it correctly, you have a single m3u8 audio stream, and you want to update the metadata when the song being played in that stream changes. The default/styled receivers are not built for this use case, however, it's easy to create a custom receiver using HTML/JS/CSS. Then the code for checking/updating the current song title can run on the Cast receiver, which has the added benefit of still working even if the sender app disconnects.
