### ISSUE TITLE
WARN  [Error: Media failed to load] only on iOS

### ISSUE THREAD

**Issue by Robiullah2244** [react-native-google-cast/react-native-google-cast#430]
_THIS IS NOT ACTUALLY AN ISSUE WITH THIS PACKAGE I ASSUME._

I created a Styled Media Receiver in Chromecast. My android app casting properly. But the iOS app doesn't. It says  `WARN  [Error: Media failed to load]` and media is not playing but the cast is connecting and shows the app title on the cast receiver device.

But using `EA48D3FC(found from a sample app)` as ApplicationID, cast working properly in iOS also. So, I think some issues on the console side.

I posted it on https://stackoverflow.com/questions/72395202/error-media-failed-to-load-in-chromecast-ios-only. But no answer.

Can anyone help me out, please?

<img width="556" alt="image" src="https://user-images.githubusercontent.com/33126665/170783081-6b814892-78bb-4c62-a68b-97a1d0be1c93.png">

**Comment by petrbela** [comment]
Hmm not sure if the debugger is available for styled (non-custom) receivers? That would allow you to see the console output of the Cast device. https://developers.google.com/cast/docs/debugging/remote_debugger

**Comment by Robiullah2244** [comment]
> That would allow you

Thank you I will try

**Comment by Robiullah2244** [comment]
> Hmm not sure if the debugger is available for styled (non-custom) receivers? That would allow you to see the console output of the Cast device. https://developers.google.com/cast/docs/debugging/remote_debugger

Thank you, I will try
