### ISSUE TITLE
Unable to active texttracks - Error: Media control channel status code 2100

### ISSUE THREAD

**Issue by jomachh** [react-native-google-cast/react-native-google-cast#441]
I'm trying to use texttracks stored in S3 and I get this error:

`Error: Media control channel status code 2100`

**Load media function**
`client.loadMedia({
          mediaInfo: {
            contentUrl: source.uri,
            mediaTracks: [
              {
                "contentId": TEXT_TRACK_URI,
                "id":1,
                "language":"en",
                "name":"English",
                "subtype":"subtitles",
                "type":"text"
               }
             ],
            metadata: {
              title,
              type: "movie",
            },
          },
          startTime: currentTime.current,
        });
`

**Active texttrack function content**
`
if (client) {
    if (selectedTextTrack) {
      client.setActiveTrackIds([
        selectedTextTrack.index,
      ]);
   } else {
     client.setActiveTrackIds([]);
  }
}
`

**Environment**

- Android
- React Native Version: 0.67.4
- RNGC Version: 4.2.8

I hope you can help me! :)

**Comment by petrbela** [comment]
Hmm `selectedTextTrack.index` should be `.id` perhaps?

**Comment by jomachh** [comment]
@petrbela in this case `selectedTextTrack.index` represents the same number that `.id` in the mediaTracks arrays

**Comment by jomachh** [comment]
`selectedTextTrack.index` = 1
`.id` = 1

**Comment by petrbela** [comment]
Not sure what the problem is then. 2100 is a [generic fail](https://developers.google.com/android/reference/com/google/android/gms/cast/CastStatusCodes#public-static-final-int-failed).
If you put together a repro example I can take a look. Or try searching general google cast forums as this might not be an issue with this library.
