### ISSUE TITLE
The fully qualified name of the implementation of OptionsProvider must be provided as metadata in the AndroidMaifest.xml with key OPTIONS_PROVIDER_CLASS_NAME

### ISSUE THREAD

**Issue by j-cimb-barker** [react-native-google-cast/react-native-google-cast#443]
Hello,

I am trying to use this Module on Android. I have installed the module and updated gradle files. However I get the following error when the running on Android...

`The fully qualified name of the implementation of OptionsProvider must be provided as metadata in the AndroidMaifest.xml with key OPTIONS_PROVIDER_CLASS_NAME`

It would be useful to know the value of the key and how it is found. 

Thanks....!

**Comment by j-cimb-barker** [comment]
Solved by taking a look at : https://github.com/react-native-google-cast/react-native-google-cast/blob/main/example/android/app/src/main/AndroidManifest.xml

```
 <meta-data
  android:name="com.google.android.gms.cast.framework.OPTIONS_PROVIDER_CLASS_NAME"
        android:value="com.reactnative.googlecast.GoogleCastOptionsProvider" />
```

**Comment by petrbela** [comment]
This is also described in the docs ;) https://react-native-google-cast.github.io/docs/getting-started/setup#android
