### ISSUE TITLE
Can't Build on Mac M1

### ISSUE THREAD

**Issue by BenDuh** [react-native-google-cast/react-native-google-cast#444]
Hi,

I'm struggling with the installation of the library on Mac M1. I follow the documentation to install the beta lib from google which support arm processor but the projet didn't build also : https://react-native-google-cast.github.io/docs/getting-started/installation

Can you help me or find a solution for my problem ?

**Comment by petrbela** [comment]
Hi, yeah this is a bit complicated still. I've been running into some issues myself which is why it's not properly documented yet. I'll try to take a closer look and set up an example project this weekend.

**Comment by petrbela** [comment]
Okay added support in 4.3.0. See the [installation](https://react-native-google-cast.github.io/docs/getting-started/installation) and let me know if there's any issue.

**Comment by petrbela** [comment]
This seems like a misconfiguration somewhere in your project. Are you able to post the code so I can take a look?

**Comment by BenDuh** [comment]
Sorry i forgot to update the lib version. I follow your guide installation but i have this now 

<img width="1183" alt="Capture d’écran 2022-08-10 à 10 08 57" src="https://user-images.githubusercontent.com/46995140/183849858-77d13286-96b7-43d4-a658-acc4cdeac4ac.png">

**Comment by BenDuh** [comment]
`require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
pod 'react-native-video/VideoCaching', :path => '../node_modules/react-native-video/react-native-video.podspec'

platform :ios, '12.0'

abstract_target 'App' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'AppName' do
    pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
    pod 'react-native-google-cast/NoBluetoothArm', path: '../node_modules/react-native-google-cast'

    target 'AppName' do
      inherit! :complete
      # Pods for testing
    end
  end

  target 'AppName' do
    pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
    pod 'react-native-google-cast/NoBluetoothArm', path: '../node_modules/react-native-google-cast'

  end


  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    installer.pods_project.targets.each do |target|
      if target.name == "React-Core-AccessibilityResources"
        target.remove_from_project
      end
    end
  end
end`

**Comment by petrbela** [comment]
Well for one you define the 'AppName' target twice. Please check the [example project](https://github.com/react-native-google-cast/RNGCArm) for proper setup.
