### ISSUE TITLE
[Android] Null is not an object (evaluating 'Native.SESSION_STARTED') 

### ISSUE THREAD

**Issue by fabio-carvalho88** [react-native-google-cast/react-native-google-cast#448]
Although I believe I have the Installation & Setup for Android I'm currently stuck with this:

```
  const client = useRemoteMediaClient();

  if (client) {
    client.loadMedia({
      data
    });
  }
```

![image](https://user-images.githubusercontent.com/45637344/186458484-e9114399-8b0c-4382-be58-98009e2b24ff.png)

I'm using **Renative** to develop apps for both Android and iOS. 
Dependencies were inserted in `android/app/build.gradle` accordingly to the [Docs](https://react-native-google-cast.github.io/docs/getting-started/installation#android)

Below you can see examples of how I'm editing the AndroidManifest, MainActivity.

![image](https://user-images.githubusercontent.com/45637344/186460725-7dc4747b-3ee1-499c-8a2f-cd6a927c7f77.png)

![image](https://user-images.githubusercontent.com/45637344/186460027-c4d5d695-51f9-425f-a75c-8c921fe4c7f5.png)

**Comment by petrbela** [comment]
Hmm I'm not quite sure how Renative works but this error means that the native module hasn't been loaded.

Do you know what RN version it uses? Maybe the library needs to be [linked manually](https://react-native-google-cast.github.io/docs/getting-started/installation#b-rn-059)?

**Comment by fabio-carvalho88** [comment]
Hello @petrbela, thanks for replying!

This are the versions I'm using: 
```
"react-native": "0.61.2",
 "renative": "0.31.1"
```

According to the docs, I shouldn't need to link it manually. Am I overlooking something?

**Comment by petrbela** [comment]
Is it possible to create a repository that I can check out and build? As I said I'm not very familiar with Renative so I'm not sure what configuration it generates.

**Comment by fabio-carvalho88** [comment]
That's not possible since it's a work related project... I'm sorry!

**Comment by fabio-carvalho88** [comment]
I tried to log `NativeModules.RNGCSessionManager` in my player component and it returns null.

**Comment by petrbela** [comment]
Yeah, the module is not loaded. Unfortunately, I don't have the time to look into Renative right now. You could create a separate project with just the google cast library included, no need to post your entire work code.

**Comment by fabio-carvalho88** [comment]
Some updates @petrbela. At the start of the project I was really confident I had Google Play Services on Android Studio's Emulator, but after opening the SDK Manager I noticed a checkbox to install them which solved those "native errors". 

At the moment, if I click on the GoogleCast Button nothing happens so I decided to log Google Play Services state and `getDevices()` (image below)

![image](https://user-images.githubusercontent.com/45637344/186868356-eb7d083b-5f40-47c0-96fd-8beacf69779f.png)

Despite not finding any devices, shouldn't a popup window show when the CastButton is clicked?

**Comment by petrbela** [comment]
Ahh yeah I guess the error notice for missing Play Services should be clearer...

As for not finding any devices, I actually haven't been able to test using the emulator. From [troubleshooting](https://react-native-google-cast.github.io/docs/getting-started/troubleshooting):

> (Android) If using an emulator, due to it running as a virtual machine with its own network, you might need to configure NAT for the virtual device. If you cannot see any Cast devices on the emulator, please test with a real Android device before reporting an issue. Alternatively, you may try using [Genymotion](https://www.genymotion.com/) but note it [doesn't support M1/ARM Macs yet](https://support.genymotion.com/hc/en-us/articles/360017897157-Does-Genymotion-Desktop-work-on-Mac-M1-).

Do you have an Android device to test with?

**Comment by fabio-carvalho88** [comment]
I have downloaded the build apk and installed on my Android device but the CastButton isn't opening the CastDialog as expected. To my understanding, by clicking in the CastButton something like this should appear:

![image](https://user-images.githubusercontent.com/45637344/186892859-0d02e42d-e2f8-48df-8b8c-94d7fd490651.png)

![image](https://user-images.githubusercontent.com/45637344/186893216-1d63f8ce-caa3-4885-9325-b41f1625c3d6.png)

**Comment by petrbela** [comment]
Can you try calling [`GoogleCast.showCastDialog()`](https://react-native-google-cast.github.io/docs/api/classes/castcontext#static-showcastdialog)? Sometimes the button [doesn't respond](https://github.com/react-native-google-cast/react-native-google-cast/issues/436).

**Comment by fabio-carvalho88** [comment]
The dialog does display if I call "GoogleCast.showCastDialog()," but if I try to call it inside the "onPress" funciton, it doesn't.

**Comment by petrbela** [comment]
Which `onPress` function? Could it be the issue #436?

**Comment by fabio-carvalho88** [comment]
My problem doesn't seem to suit the scenario mentioned on #436, for two reasons:

1. One of my team members was able to open CastDialog using the apk he had installed on his phone. But neither I nor the other team members can make that happen.

2. I double-checked and our CastButton isn't a Pressable/Touchable button's child (like reported in the other issue)

**Comment by fabio-carvalho88** [comment]
I was able to activate the `CastDialog` after seeing #446:

![image](https://user-images.githubusercontent.com/45637344/188107492-5b5d4b7d-215f-4860-a5f7-abaaab10ce8e.png)
![image](https://user-images.githubusercontent.com/45637344/188107573-9126fd9d-3d62-4b9f-9231-46ed2dbedbfe.png)

Our app was tested across two networks.

- only TVs;
- a TV and a TV with Chromecast;

Only the TV with Chromecast could be recognized by the app, all other devices were not displayed in the CastDialog.

**Comment by petrbela** [comment]
> Only the TV with Chromecast could be recognized by the app, all other devices were not displayed in the CastDialog.

Google Cast only supports TVs with Chromecast. If you want a unified dialog for different kinds of destinations (e.g. AirPlay, Samsung etc), you'll need to include those libraries separately, and instead of the `CastButton` component create your own dialog with [DiscoveryManager](https://react-native-google-cast.github.io/docs/api/classes/discoverymanager) (or the `useDevices` hook) to populate it.

**Comment by fabio-carvalho88** [comment]
Thank you, I'll look into that.
However, why does my Chrome Browser recognize smart TVs while the app in the smartphone doesn't?

**Comment by fabio-carvalho88** [comment]
Thanks for your help @petrbela
