### ISSUE TITLE
Channel is not connected or is not registered with a session [iOS ONLY]

### ISSUE THREAD

**Issue by jomachh** [react-native-google-cast/react-native-google-cast#449]
**Describe the bug**
I'm initializing the variables as its shown in the following code snippet

    const client = useRemoteMediaClient();
    const channel = useCastChannel("urn:x-cast:com.google.cast.media");
    const castSession = useCastSession();

*Send cast session message function*

    const sendCastSessionMessage = msg => {
        channel
            .sendMessage(msg)
            .then(() => {
                console.log("SUCCESS");
            })
            .catch(err => console.log("ERROR", err));
    };

*Example of how we implement the function*

    const seekToChromecast = useCallback(
        async time => {
            if (client && castSession && channel) {
                const mediaStatus = await client.getMediaStatus();
                const mediaId = mediaStatus?.currentItemId ?? 1;
                requestId.current += 1;
                const msg = {
                    type: "SEEK",
                    mediaSessionId: mediaId,
                    requestId: requestId.current,
                    currentTime: time,
                };
                sendCastSessionMessage(msg);
            }
        },
        [client, castSession, channel],
    );

**To Reproduce**
 - Real iOS Device
 - React Native v0.67.4
 - Try to send a media message as play, pause or seek. 

**Expected behavior**
Send messages to our receiver.

**Screenshots**
Screenshot from my terminal logs showing the error and the current cast session.

![Screen Shot 2022-09-05 at 12 39 52](https://user-images.githubusercontent.com/43825306/188501352-d288dc65-0bc8-438a-8b7d-348eb6f2f86a.png)

**Device:**
 - Device: Real iPhone 13 Mini
 - OS: iOS 15.6
 - Library Version 4.4.1

**Checklist:**
 - [ DONE ] I have followed [Installation](https://react-native-google-cast.github.io/docs/getting-started/installation) and [Setup](https://react-native-google-cast.github.io/docs/getting-started/setup)
 - [ DONE ] My problem is not described in [Troubleshooting](https://react-native-google-cast.github.io/docs/getting-started/troubleshooting)
 - [ DONE ] I have searched [existing issues](https://github.com/react-native-google-cast/react-native-google-cast/issues?q=is%3Aissue) and have not found a similar one

**Additional context**
We are using a custom receiver.
**Android works fine.**

**Comment by petrbela** [comment]
I'll try to take a look. Btw with a custom receiver, you don't need to create a custom channel to send common events like play, pause, seek; the usual methods on `client` would still work.

**Comment by jomachh** [comment]
Thank you, Using the client methods works for me, but I still need to send messages to our receiver to turn on/off subtitles, our video sources have embedded text tracks 

    const msg = {
        type: "EDIT_TRACKS_INFO",
        language: selectedTextTrack.title,
        isSuggestedLanguage: false,
        mediaSessionId: mediaId,
        sessionId: castSession?.id,
        requestId: requestId.current,
    };
    sendCastSessionMessage(msg)

We get the available text tracks using the onLoad function event.

**Comment by jomachh** [comment]
Any update on this? 😔

**Comment by petrbela** [comment]
Are you using `urn:x-cast:com.google.cast.media` as the channel name? That's not going to work, you need to use a different name.
