### ISSUE TITLE
Chromecast causes app crash on Android getQueueItemCount() on null

### ISSUE THREAD

**Issue by DennisdeWitNL** [react-native-google-cast/react-native-google-cast#453]
**Describe the bug**
When starting to cast the stream to Android, the app crashes, saying 'there is a bug.'

**To Reproduce**
1. Go to the app
2. Click on the cast icon
3. Start casting
4. App crashes with error in Logcat

```
Attempt to invoke virtual method 'int com.google.android.gms.cast.MediaStatus.getQueueItemCount()' on a null object reference
```

5: Stream is audible and continues to play, but the app had crashed on the foreground.

**Expected behavior**
Should stream audio without crashing.

**Screenshots**

**Device:**
 - Android 10 and higher, real device. Tested on numerous brands, I myself have reproduced the issue on the Galaxy S10 Plus.
 - OS: Android 12, One UI 4.1
 - Library Version: 4.5.0

**Checklist:**
 - [X] I have followed [Installation](https://react-native-google-cast.github.io/docs/getting-started/installation) and [Setup](https://react-native-google-cast.github.io/docs/getting-started/setup)
 - [X] My problem is not described in [Troubleshooting](https://react-native-google-cast.github.io/docs/getting-started/troubleshooting)
 - [x] I have searched [existing issues](https://github.com/react-native-google-cast/react-native-google-cast/issues?q=is%3Aissue) and have not found a similar one

**Additional context**
My code here:

```
function GoogleChromeCast({route}) {
  const {streamID} = route.params;
  const client = useRemoteMediaClient();

  useEffect(() => {
    const fetchChromeCastandPass = async () => {
      const resp = await fetch(
        `https://domain.com/folder/getinfoviajson.php?streamID=${streamID}`,
      );
      const ChromeCastInfo = await resp.json();

      if (client) {
        // Send the media to your Cast device as soon as we connect to a device
        // (though you'll probably want to call this later once user clicks on a video or something)
        client.loadMedia({
          mediaInfo: {
            contentUrl: ChromeCastInfo.streamURL,
            contentType: 'audio/mpeg',
            metadata: {
              images: [
                {
                  url: ChromeCastInfo.imageURL,
                },
              ],
              title: ChromeCastInfo.streamName,
              subtitle: ChromeCastInfo.nowPlaying,
              type: 'generic',
            },
          },
        });
      }
    };
    fetchChromeCastandPass();
  });

  // This will automatically rerender when client is connected to a device
  // (after pressing the button that's rendered below)

  return (
    <View style={{marginTop: 7}}>
      <CastButton style={{width: 50, height: 60, tintColor: '#428bca'}} />
    </View>
  );
}
```

**Comment by DennisdeWitNL** [comment]
Seems to be fixed with Google Cast SDK 21.1. Will test further tomorrow.

**Comment by petrbela** [comment]
I think you're missing dependencies in your `useEffect` which means it reruns on every render.

**Comment by petrbela** [comment]
If you just want to run the effect once when the component mounts, you can specify an empty array: `useEffect(() => { ... }, [])`

**Comment by DennisdeWitNL** [comment]
> If you just want to run the effect once when the component mounts, you can specify an empty array: `useEffect(() => { ... }, [])`

Tried this, it is not working at all. When adding and empty array, it isn't loading any track anymore. Any other ideas? Or maybe want to check my code?

**Comment by petrbela** [comment]
actually you should put `client` in the dependency array because it's probably `null` the first time it's called

**Comment by DennisdeWitNL** [comment]
> actually you should put `client` in the dependency array because it's probably `null` the first time it's called

And that indeed fixed the problem! Thank you so much, @petrbela! :)
