### ISSUE TITLE
App chashed when begin connection with chromecast Error: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.google.android.gms.cast.MediaStatus.getQueueItemCount()' on a null object reference

### ISSUE THREAD

**Issue by leoalbirojo** [react-native-google-cast/react-native-google-cast#454]
**Describe the bug**
When I compile the example App in react native in my PC and connect it with my chomecast device this close and give a crash report in flipper with the follow message, even i tested the expo repo and had the same result, except with the compiled Release exposed in the repo  RNGCExp.

`java.lang.NullPointerException: Attempt to invoke virtual method 'int com.google.android.gms.cast.MediaStatus.getQueueItemCount()' on a null object reference

FATAL EXCEPTION: main
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.google.android.gms.cast.MediaStatus.getQueueItemCount()' on a null object reference
	at com.reactnative.googlecast.GoogleCastOptionsProvider$1.hasQueue(GoogleCastOptionsProvider.java:84)
	at com.reactnative.googlecast.GoogleCastOptionsProvider$1.getNotificationActions(GoogleCastOptionsProvider.java:45)
	at com.google.android.gms.cast.framework.media.zzz.zzf(com.google.android.gms:play-services-cast-framework@@21.2.0:1)
	at com.google.android.gms.cast.framework.media.internal.zzs.zzf(com.google.android.gms:play-services-cast-framework@@21.2.0:1)
	at com.google.android.gms.cast.framework.media.MediaNotificationService.isNotificationOptionsValid(com.google.android.gms:play-services-cast-framework@@21.2.0:3)
	at com.google.android.gms.cast.framework.media.internal.zzr.zzw(com.google.android.gms:play-services-cast-framework@@21.2.0:3)
	at com.google.android.gms.cast.framework.media.internal.zzr.zzi(com.google.android.gms:play-services-cast-framework@@21.2.0:11)
	at com.google.android.gms.cast.framework.CastSession.zzi(com.google.android.gms:play-services-cast-framework@@21.2.0:11)
	at com.google.android.gms.cast.framework.zzh.onComplete(com.google.android.gms:play-services-cast-framework@@21.2.0:1)
	at com.google.android.gms.tasks.zzi.run(com.google.android.gms:play-services-tasks@@18.0.1:1)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8105)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)`

**To Reproduce**
1. Simply I downloaded the repo , ran react-native run:android but this give me the next error:
`Execution failed for task ':app:checkDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > One or more issues found when checking AAR metadata values:
     
     Dependency 'androidx.mediarouter:mediarouter:1.3.0' requires 'compileSdkVersion' to be set to 31 or higher.
     Compilation target for module ':app' is 'android-30'
     
     Dependency 'androidx.appcompat:appcompat:1.4.1' requires 'compileSdkVersion' to be set to 31 or higher.
     Compilation target for module ':app' is 'android-30'
     
     Dependency 'androidx.media:media:1.6.0' requires 'compileSdkVersion' to be set to 31 or higher.
     Compilation target for module ':app' is 'android-30'
     
     Dependency 'androidx.appcompat:appcompat-resources:1.4.1' requires 'compileSdkVersion' to be set to 31 or higher.
     Compilation target for module ':app' is 'android-30'
     
     Dependency 'androidx.emoji2:emoji2-views-helper:1.0.0' requires 'compileSdkVersion' to be set to 31 or higher.
     Compilation target for module ':app' is 'android-30'
     
     Dependency 'androidx.emoji2:emoji2:1.0.0' requires 'compileSdkVersion' to be set to 31 or higher.
     Compilation target for module ':app' is 'android-30'
     
     Dependency 'androidx.fragment:fragment-ktx:1.4.1' requires 'compileSdkVersion' to be set to 31 or higher.
     Compilation target for module ':app' is 'android-30'
     
     Dependency 'androidx.fragment:fragment:1.4.1' requires 'compileSdkVersion' to be set to 31 or higher.
     Compilation target for module ':app' is 'android-30'
     
     Dependency 'androidx.activity:activity-ktx:1.4.0' requires 'compileSdkVersion' to be set to 31 or higher.
     Compilation target for module ':app' is 'android-30'
     
     Dependency 'androidx.activity:activity:1.4.0' requires 'compileSdkVersion' to be set to 31 or higher.
     Compilation target for module ':app' is 'android-30'
     
     Dependency 'androidx.core:core:1.7.0' requires 'compileSdkVersion' to be set to 31 or higher.
     Compilation target for module ':app' is 'android-30'
     
     Dependency 'androidx.lifecycle:lifecycle-process:2.4.0' requires 'compileSdkVersion' to be set to 31 or higher.
     Compilation target for module ':app' is 'android-30'
     
     Dependency 'androidx.lifecycle:lifecycle-runtime:2.4.0' requires 'compileSdkVersion' to be set to 31 or higher.
     Compilation target for module ':app' is 'android-30'`

2.Then I changed the param  'compileSdkVersion' from 30 to 31 in android/build.graddle.
3. Ran react-native run:android and this time the compilation was sucessfully.
4. Opened the app, touched the Cast Button, appeared the chromecast device, touched this and the app closed and give the crash message above.

**Expected behavior**
I tested the release apk exposed in https://github.com/react-native-google-cast/RNGCExpo/releases/download/1.0.0/0c8faa9c-7f44-424c-9c92-0006064c5e93-7f948c918fce4fa39054c06cf485ac58.apk and this connect and disconnect the devices whitout problems I don't understand why with my own compilation the app does't run similarly, the only change was the compileSDKversion because the error compilation. 

I tested this in two devices Poco F3 and Motorola G5s Plus.

**Device:**
 - Device: [Poco F3, Motorola G5s Plus]
 - OS: [Android 12, Android 7.1]

**Checklist:**
 -  My problem is not described in [Troubleshooting](https://react-native-google-cast.github.io/docs/getting-started/troubleshooting)
 -  I have searched [existing issues](https://github.com/react-native-google-cast/react-native-google-cast/issues?q=is%3Aissue) and have not found a similar one

**Additional context**
I think that change the compileSDK generate the error but i can't compile in 30 version.

**Comment by AmauryLiet** [comment]
@petrbela It seems linked to #447 
I see that you mention sticking to com.google.android.gms:play-services-cast-framework:**21.0.0** fixes the issue, although in v4.5.0 you specified a later version **v21.1.0** ([commit](https://github.com/react-native-google-cast/react-native-google-cast/commit/41cca84169932b17f22274ab2ce8cfd6514e20ca))

Currently checking the fix (downgrading to 21.0.0) on my side

**Comment by redcartel** [comment]
I found a temporary(?) workaround by updating android/build.gradle. I commented out the expo-prebuild config and set a specific castFrameworkVersion as suggested above. I didn't have to change my compileSdkVersion.

```
// @generated begin react-native-google-cast-version - expo prebuild (DO NOT MODIFY) sync-...
        //castFrameworkVersion = "+"
// @generated end react-native-google-cast-version
        castFrameworkVersion = "21.0.0"
```

**Comment by Nasseratic** [comment]
Who ever is using expo, it's easier to pass this config-plugin parameter in `app.json`
```json
[
      "@config-plugins/react-native-google-cast",
      {
        "androidPlayServicesCastFrameworkVersion": "21.0.0"
      }
]
```

**Comment by ThanhTrung09** [comment]
I used castFrameworkVersion = "21.0.0" but the app still crashes. Is there any other way?

**Comment by ThanhTrung09** [comment]
@petrbela I tried rebuilding but still crash app

**Comment by ThanhTrung09** [comment]
Update: This error came from the package and I added "client.getMediaStatus() != null" and the crash stopped
![Screenshot 2022-11-25 at 12 18 33](https://user-images.githubusercontent.com/81958312/203906434-139c245a-6593-4001-ad7b-aa77036e56a4.png)
 In ./node_modules/react-native-google-cast/android/src/main/java/com/reactnative/googlecast/GoogleCastOptionsProvider.java

**Comment by techleaddev** [comment]
@taschik, Instead of using the package patch-package, I used the package replace-in-file and I created the config.js file like this

`module.exports = {
    files: './node_modules/react-native-google-cast/android/src/main/java/com/reactnative/googlecast/GoogleCastOptionsProvider.java',
    from: ['client != null', 'client != null && client.getMediaStatus().getMediaInfo().getMetadata().getMediaType()'],
    to: ['client != null && client.getMediaStatus() != null', 'client != null && client.getMediaStatus() != null && client.getMediaStatus().getMediaInfo().getMetadata().getMediaType()'],
};
`
