### ISSUE TITLE
Is it possible to use another player to cast to ?

### ISSUE THREAD

**Issue by YoucefBen47** [react-native-google-cast/react-native-google-cast#455]
Hi, after casting to a TV the player doesn't seem to read our dash links. We are trying to figure out why but is there a possibility to use a custom player to cast to ?

**Comment by petrbela** [comment]
Yes, you can send to a custom receiver, the only thing you need to do is to set your receiver app id, see [Setup](https://react-native-google-cast.github.io/docs/getting-started/setup)
