### ISSUE TITLE
How to add a drm url to play drm protected content?

### ISSUE THREAD

**Issue by YoucefBen47** [react-native-google-cast/react-native-google-cast#456]
I tried some methods to add customData and add a drm url to play the protected videos however it doesn't work.

**Comment by petrbela** [comment]
You'll need to build a [custom receiver](https://developers.google.com/cast/docs/media#delivery_methods_and_adaptive_streaming_protocols) and apply whatever customData you send from the sender (mobile app) on the Cast device. If there's a specific issue please post a reproducible example.
