### ISSUE TITLE
mini controller?

### ISSUE THREAD

**Issue by ScottZhu12** [react-native-google-cast/react-native-google-cast#457]
Hi, I see we have doc for setup and usage of expanded controller.

I wonder if we could also have doc for displaying the default mini controller? or is it still a feature needs to be implemented?

I've checked the official SDK doc, seems like there's Android fragment and iOS component/class for this purpose, but I'm not sure how to integrate them into react native project. any help/guide would be appreciated.

Or instead is it easier for me if I just build a react native component which uses APIs we have here?

**Comment by petrbela** [comment]
Unfortunately, the native mini controller is not implemented yet.

I suppose you could build a custom one in React Native. I believe all the necessary APIs should be there.

**Comment by ScottZhu12** [comment]
@petrbela sounds good, thank you for the clarification!
