### ISSUE TITLE
 ld: in /Users/expo/workingdir/build/ios/Pods/google-cast-sdk-no-bluetooth/GoogleCastSDK-ios-4.7.0_static/GoogleCast.framework/GoogleCast(GCKCastUISubcontext.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/expo/workingdir/build/ios/Pods/google-cast-sdk-no-bluetooth/GoogleCast

### ISSUE THREAD

**Issue by Nasseratic** [react-native-google-cast/react-native-google-cast#458]
**Describe the bug**
I am using expo 46 to build using the latest config plugin 3.0.0

Fastlane fails:

```
❌  ld: in /Users/expo/workingdir/build/ios/Pods/google-cast-sdk-no-bluetooth/GoogleCastSDK-ios-4.7.0_static/GoogleCast.framework/GoogleCast(GCKCastUISubcontext.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/expo/workingdir/build/ios/Pods/google-cast-sdk-no-bluetooth/GoogleCastSDK-ios-4.7.0_static/GoogleCast.framework/GoogleCast' for architecture arm64
```

**Device:**
 - Device:  iPhone Simulator
 - OS: IOS
 - Library Version: 4.5.0

**Checklist:**
 - [X] I have followed [Installation](https://react-native-google-cast.github.io/docs/getting-started/installation) and [Setup](https://react-native-google-cast.github.io/docs/getting-started/setup)
 - [X] My problem is not described in [Troubleshooting](https://react-native-google-cast.github.io/docs/getting-started/troubleshooting)
 - [X] I have searched [existing issues](https://github.com/react-native-google-cast/react-native-google-cast/issues?q=is%3Aissue) and have not found a similar one

**Comment by Nasseratic** [comment]
I batched [react-native-google-cast.podspec](https://github.com/react-native-google-cast/react-native-google-cast/blob/main/react-native-google-cast.podspec)

to make the default spec from
``` 
s.default_subspec = 'NoBluetooth'
```
To:
``` 
s.default_subspec = 'NoBluetoothArm'
```

**Comment by fabio-carvalho88** [comment]
hi @Nasseratic ! do you know why this happens?

**Comment by Nasseratic** [comment]
I think it's because if you are using M1 the simulator expects lib that is built for Arm.
