### ISSUE TITLE
The Cast button renders in iOS emulator, but it fails to render inside Android emulator.

### ISSUE THREAD

**Issue by tyrant-davis** [react-native-google-cast/react-native-google-cast#461]
**Describe the bug**
Chromecast has been added to our app. The Cast button renders in the iOS emulator but fails to show inside the Android emulator.  

**Error Panel**
1. Error Msg 2: E/SQLiteCastStore: Skip saving CastDeviceInfo: "Nearby device" (__cast_nearby___.… alpha-numeric string ID here…..)
2. E/ACodec: [OMX.google.h264.decoder] setPortMode on output to DynamicANWBuffer failed w/ err -1010
3. E/cracynow.mobil: Invalid ID 0x0000....

**Debug Panel**
1. E/wifi_forwarder: RemoteConnection failed to initialize: RemoteConnection failed to open pipe

4. E/GnssHAL_GnssInterface: gnssSvStatusCb: a: input svInfo.flags is 8

5. E/memtrack: Couldn't load memtrack module

6. D/BoundBrokerSvc: onBind: Intent { act=com.google.android.gms.checkin.START pkg=com.google.android.gms }

7. D/BoundBrokerSvc: Loading bound service for intent: Intent { act=com.google.android.gms.checkin.START pkg=com.google.android.gms }

**To Reproduce**
1. Install and setup Chromecast for Android
2. Build the app
3. See if the Cast button renders inside a third-party app and casts

**Expected behavior**
The chrome Cast button is expected to render, to be detectable for casting, and to cast.

**Device:**
 - Device: Android Emulator
 - OS: Android
 - Library Version Android Studio 4.2.2
- Device: Android Emulator
 - react-native: “0.60.3”
"react-native-google-cast": "4.0.0"

**Checklist:**
 - [x] I have followed [Installation](https://react-native-google-cast.github.io/docs/getting-started/installation) and [Setup](https://react-native-google-cast.github.io/docs/getting-started/setup)
 - [x] My problem is not described in [Troubleshooting](https://react-native-google-cast.github.io/docs/getting-started/troubleshooting)
 - [x] I have searched [existing issues](https://github.com/react-native-google-cast/react-native-google-cast/issues?q=is%3Aissue) and have not found a similar one

**Comment by scottg489-tw** [comment]
I'm also working with @tyrant-davis on this.

I've been able to run the app on my physical phone and the button will show up.

Also, if I open up the YouTube app inside the Android emulator, I'm able to see the casting button and when I click on it I'm able to see some of my devices on my network. This would indicate that it isn't a network issue.

**Comment by petrbela** [comment]
Google Cast just doesn't work on an Android emulator. See https://github.com/googlecast/CastVideos-android/issues/104

**Comment by scottg489-tw** [comment]
@petrbela I'm not sure this is true. In the YouTube app in my emulator I'm able to see devices on my local network and successfully cast to them.

**Comment by petrbela** [comment]
Please read the linked issue.

**Comment by scottg489-tw** [comment]
I see, they use the DIAL protocol. Also, thanks for updating the troubleshooting guide with this info. That would have been good to know.
