### ISSUE TITLE
Cast not showing any devices

### ISSUE THREAD

**Issue by soufiansaidi** [react-native-google-cast/react-native-google-cast#463]
ON ios Devices the castbutton working just find but it stuck `No devices available` and `Make sure Locale Netwok access is on`
I did everything in documentation but still the same issue.

[Screenshot](https://ibb.co/GVJZfBH)

Is it required to have an my own `app_id` to test the my application, or i can make it work wihtout having `[google cast account](https://cast.google.com/publish/#/signup)`

**Comment by petrbela** [comment]
You don't have to sign up for a custom app. Please read [Troubleshooting](https://react-native-google-cast.github.io/docs/getting-started/troubleshooting) for known discovery problems. Unfortunately, I can't help more since it's dependent on your network.
