### ISSUE TITLE
Application tried to present modally a view controller error when triggering showCastDialog method

### ISSUE THREAD

**Issue by neilakoh** [react-native-google-cast/react-native-google-cast#465]
**Describe the bug**
When pressing/triggering `GoogleCast.showCastDialog()` in iOS, the app crashes due to two modals overlapping created by the show cast dialog. Here is the error:

`Application tried to present modally a view controller <UINavigationController: 0x7fd193922000> that is already being presented by <UIViewController: 0x7fd19310c080>.`

**To Reproduce**
pressing/triggering `GoogleCast.showCastDialog()` in iOS

**Screenshots**
<img width="674" alt="Screen Shot 2022-11-11 at 5 59 18 PM" src="https://user-images.githubusercontent.com/15863359/201316061-c36a1abb-5195-43fe-8445-c30df39b5cd0.png">

**Device:**
iPhone Simulator

**Comment by neilakoh** [comment]
My bad . . my implementation on android does not work in iOS so I had to refactor the code for iOS specific approach

**Comment by PradeepVL** [comment]
@neilakoh I am facing the same issue, could you please share your approach for iOS.
