### ISSUE TITLE
[Question] Can I chromecast a media in a WebView

### ISSUE THREAD

**Issue by Impre-visible** [react-native-google-cast/react-native-google-cast#467]
Hi, I'm working on a simple app who act like a "navigator" so, I use webview to show the webpage, I want to enable an option to chromecast the video currently playing, can I interact with the WebView to add a button, and be able to chromecast ? Thanks

**Comment by petrbela** [comment]
There are two steps:
1. First, you need to connect your app to a Chromecast device. You can't do that from the webview but you can add a <CastButton> in your app header, for example.
2. To start playing a video, you could send a message from the web page to the app using https://github.com/react-native-webview/react-native-webview/blob/master/docs/Guide.md#communicating-between-js-and-native. Then in the app you can call loadMedia.

**Comment by arnegolemar** [comment]
Hello Mr. @Impre-visible good day, do you managed to implement this one?

**Comment by Impre-visible** [comment]
> Hello Mr. @Impre-visible good day, do you managed to implement this one?

Hi, no, sadly I didn't managed to implement that. It's sad.

**Comment by arnegolemar** [comment]
Ohh, but did you come up any other solution for your problem?

**Comment by arnegolemar** [comment]
> > Hello Mr. @Impre-visible good day, do you managed to implement this one?
> 
> Hi, no, sadly I didn't managed to implement that. It's sad.

Ohh, but did you come up any other solution for your problem?

**Comment by Impre-visible** [comment]
> > > Hello Mr. @Impre-visible good day, do you managed to implement this one?
> > 
> > Hi, no, sadly I didn't managed to implement that. It's sad.
> 
> Ohh, but did you come up any other solution for your problem?

I tried to add directly a chromecast button on the website, didn't work

**Comment by arnegolemar** [comment]
> > > > Hello Mr. @Impre-visible good day, do you managed to implement this one?
> > > 
> > > 
> > > Hi, no, sadly I didn't managed to implement that. It's sad.
> > 
> > 
> > Ohh, but did you come up any other solution for your problem?
> 
> I tried to add directly a chromecast button on the website, didn't work

Ohh okay2, Thanks for your response, really appreciate it.
