### ISSUE TITLE
How to enable guestMode in Arm (M1/M2) Macs

### ISSUE THREAD

**Issue by srihitawork** [react-native-google-cast/react-native-google-cast#486]

**Comment by petrbela** [comment]
Google hasn't published v4.7.1 to CocoaPods yet (in fact they haven't updated in several months) so the setup is a bit more complicated but you should be able to download the framework from https://developers.google.com/cast/docs/ios_sender#xcframework_beta and install based on the instructions. Alternatively, you can publish it to CocoaPods yourself like I've done here https://github.com/react-native-google-cast/google-cast-sdk-dynamic-xcframework-no-bluetooth

**Comment by petrbela** [comment]
If both devices are on the same WiFi, you don't need Guest Mode (that's only required for Bluetooth connections). In the latest version of this package, ARM support is enabled by default so you should just follow the standard setup (ignore the yellow box in Installation, I need to update the docs)

**Comment by srihitawork** [comment]
yeah, if both the devices are on the same Wifi , am fine with that , it's working. I need to setup if both devices are not on the same wifi connection, then comes the guest mode into picture right. Can you please help me with that.

**Comment by petrbela** [comment]
I'm sorry I don't have much time to help beyond what I've written above.

**Comment by srihitawork** [comment]
Thank you
