### ISSUE TITLE
Some of the m3u8 video links are not playing

### ISSUE THREAD

**Issue by srihitawork** [react-native-google-cast/react-native-google-cast#487]
![Screenshot 2023-02-15 at 4 52 49 PM](https://user-images.githubusercontent.com/112868090/219014132-c5124fb8-458f-4f43-b3de-144885cc112f.png)

Above Added error is coming when i tried to load the uri link of : 

https://manifest.prod.boltdns.net/manifest/v1/hls/v4/clear/6132741238001/a8d2ef5a-0aac-40ad-ad92-3a44d13df060/10s/master.m3u8?fastly_token=NjNlZDA5YjhfMWE2YzUyOGY3ZGFiMDdlNDliODkzZWE5Yzk5NjRhM2M1YWMyNzRiYTQ2MzU0NTU4Zjc4NjRiYTljOTExODU4NQ%3D%3D
 

the below added is the code

```js
   client.loadMedia({
      mediaInfo: {
        contentUrl:
        'https://manifest.prod.boltdns.net/manifest/v1/hls/v4/clear/6132741238001/a8d2ef5a-0aac-40ad-ad92-3a44d13df060/10s/master.m3u8?fastly_token=NjNlZDA5YjhfMWE2YzUyOGY3ZGFiMDdlNDliODkzZWE5Yzk5NjRhM2M1YWMyNzRiYTQ2MzU0NTU4Zjc4NjRiYTljOTExODU4NQ%3D%3D',
        contentType: 'application/x-mpegURL',
        metadata: {
          images: [
            {
              url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/CastVideos/images/480x270/BigBuckBunny.jpg',
            },
          ],
          title: 'Big Buck Bunny',
          subtitle:
            'A large and lovable rabbit deals with three tiny bullies, led by a flying squirrel, who are determined to squelch his happiness.',
          studio: 'Blender Foundation',
          type: 'movie',
        },
        streamDuration: 596, // seconds
      },
      startTime: 10, // seconds
    })
```

**Comment by petrbela** [comment]
This is beyond the scope of this library. I suggest you consult the Google Cast docs on supported HLS format https://developers.google.com/cast/docs/media/streaming_protocols#http_live_streaming_hls and file an issue through official channels https://developers.google.com/cast/support

**Comment by srihitawork** [comment]
On which bases this format is not supported in the library? This is M3u8 format itself right? please correct me if am wrong

**Comment by srihitawork** [comment]
On which bases this format is not supported in the library? This is M3u8 format itself right? please correct me if am wrong

**Comment by petrbela** [comment]
This library is just a React Native wrapper. Its job is to send the URL to the Cast device, which it does. Whether the media can be played, however, is an issue with the Cast SDK.

**Comment by srihitawork** [comment]
But I am able to play this m3u8 link http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8
then why not the above , as both are #EXTM3U

**Comment by petrbela** [comment]
As I said, I don't know the answer to that, please reach out to official channels. Feel free to report back if you find anything.

**Comment by srihitawork** [comment]
okay thank you

**Comment by LuisAPPDev** [comment]
@srihitawork please did you find the issue?
