### ISSUE TITLE
App not compiling for Intell architecture

### ISSUE THREAD

**Issue by ToshKoevoets** [react-native-google-cast/react-native-google-cast#502]
App not compiling.

ld: in /Users/expo/workingdir/build/ios/Pods/google-cast-sdk-no-bluetooth/GoogleCastSDK-ios-4.7.0_static/GoogleCast.framework/GoogleCast(GCKCastUISubcontext.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/expo/workingdir/build/ios/Pods/google-cast-sdk-no-bluetooth/GoogleCast #458

Building on intell chip, but RN chromecast is compling for ARM.

The docs describe how to compile for M1 / M2 as an exception. But in latest versions it seems it's now the default. Im not sure how to link now correctly in podfile to build for intell.

What I did was change the default in the src of the node modules 

Mentioned in this ticket: https://github.com/react-native-google-cast/react-native-google-cast/issues/458

I reverted to 

```
s.default_subspec = 'NoBluetooth'
```

Which allowed me to build apps, but would be great to have a stable solution that doesn't break in future.

I wouldn't mind writing a new version for the docs that assume m1 as the default, but first need to understand the correct way to go about this.

**Comment by khurramwaqar** [comment]
Hi, @ToshKoevoets, We have faced same issue after upgrading the pods, have you find something for that.

**Comment by petrbela** [comment]
With the latest version of the Cast SDK v4.8.1, there's only a single variant that should support both architectures. Please update and let me know if there are still any issues.
