### ISSUE TITLE
iOS build fails with: 'GoogleCast/GoogleCast.h' file not found

### ISSUE THREAD

**Issue by chrisshiplet** [react-native-google-cast/react-native-google-cast#51]
Hello, I recently had this library start failing to build on iOS when included in my project. I have tried reinstalling, relinking, etc. 

I have tried both `'google-cast-sdk', '2.10.4.1'` and `'google-cast-sdk'` in my podfile. I've tried manually adding the `$(SRCROOT)/../node_modules/react-native-google-cast/ios` path to the header search paths in Build Settings, and I even tried to manually add the GoogleCast.h and GoogleCast.m files into my project as mentioned in issue #21. 

I also cloned a fresh copy of the repo from here and tried the example project in both the master branch and 1.3.0 branch. In every single one of these circumstances I get the following error:

```In file included from /Users/chris/Desktop/react-native-google-cast/ios/GoogleCast.m:1:
/Users/chris/Desktop/react-native-google-cast/ios/GoogleCast.h:2:9: fatal error: 'GoogleCast/GoogleCast.h' file not found
#import <GoogleCast/GoogleCast.h>
        ^
1 error generated.
```

Any more ideas to try? I'm running out... Thanks!

**Comment by undef1ned** [comment]
The only solution which worked for me was to manually replace all the sdk Headers/* (~20 files) from

`#import <GoogleCast/GCKApplicationMetadata.h>`

to

```#import "Pods/google-cast-sdk/GoogleCastSDK-2.10.4-Release/GoogleCast.framework/Headers/GCKApplicationMetadata.h"```

**Comment by pudility** [comment]
Yup, this is a **Major** annoyance. Here is a script that I made to help me out:
```js
const fs = require('fs');

const rw = (file) =>
  fs.readFile(file, 'utf8', (err, data) => {
    console.log(file, data);
    if (err) throw err;
    fs.writeFile(file, data.split("<GoogleCast").join('"<your project dir>/ios/Pods/google-cast-sdk/GoogleCastSDK-2.10.4-Release/GoogleCast.framework/Versions/A/Headers'), (err) => {
      if (err) throw err;
      console.log('The file ' + file + ' has been saved!');
    });
  });

  fs.readdir('./', (err, files) => {
    files.forEach(file => {
      rw(file)
    });
  })
```

**Comment by mtkopone** [comment]
Here's how to fix that:

In the xcode project navigator, open Libraries/GoogleCase.xcodeproj
Choose the GoogleCast target, and Build Settings
Add the following to "Framework Search Paths": $(PROJECT_DIR)/../../../ios/Pods/google-cast-sdk/GoogleCastSDK-2.10.4-Release

**Comment by AndreaMaggi** [comment]
Try to close the `.xcodeproj` and open the `.xcworkspace` in `Xcode` and build from there...it did work here \m/

**Comment by petrbela** [comment]
Please check if it's still a problem in the latest version.

**Comment by ansonyao** [comment]
It is still a problem. 
Here is the versions of packages. The error is the same.

 "react-native":
      "version": "0.57.0",

- google-cast-sdk (3.5.6):
    - google-cast-sdk/Core (= 3.5.6)
  - google-cast-sdk/Core (3.5.6)

    "react-native-google-cast": {
      "version": "3.0.5",
      "resolved": "https://registry.npmjs.org/react-native-google-cast/-/react-native-google-cast-3.0.5.tgz",
      "integrity": "sha512-1IIuWCak0O7GWa64JOyTDpzICnyD6H01538DV45w4lND2HTfsUlhMacFg5RFe8MLjHGPJy3jm1GPnBHlb+vUOQ==",
      "requires": {
        "prop-types": "^15.6.0"
      }
    },

**Comment by ansonyao** [comment]
Tried to add this to the frame search path

$(PROJECT_DIR)/../../../ios/Pods/google-cast-sdk/GoogleCastSDK-Public-3.5.6-Release

But had no luck

**Comment by petrbela** [comment]
@ansonyao Are you sure you've opened `.xcworkspace`? Can you post your directory structure here?

**Comment by ansonyao** [comment]
Yes. I am sure about it. I am also integrating with another 10 libraries...

**Comment by ansonyao** [comment]
Hey, @petrbela. I got it compiling by adding: $(SRCROOT)/../../../ios/Pods/google-cast-sdk to the framework search paths and header search paths.

**Comment by RohitRox** [comment]
Could not get this fixed even by adding: $(SRCROOT)/../../../ios/Pods/google-cast-sdk to the paths. Any other ideas?

**Comment by PedroPovedaQ** [comment]
I used the no-bluetooth variation of the library so I got this working by adding $(SRCROOT)/../../../ios/Pods/google-cast-sdk-no-bluetooth to the search paths to "great success!" (borat voice).

**Comment by lulirl** [comment]
Hi! I have added $(SRCROOT)/../../../ios/Pods/google-cast-sdk-no-bluetooth to the search paths, but I still get: 

❌  ld: library not found for -lDoubleConversion



❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)

Does anyone know how to solve it?

**Comment by petrbela** [comment]
@lulirl This is an old thread around an outdated version of the library. You might want to open a new issue with details of your specific case. Btw looking at the error, it seems your issue might not be with this library but with `DoubleConversion` instead.

**Comment by jonelvinnaorbe** [comment]
The issue might be caused by missing Cocoapods install. Go to ios folder and run:
`pod 'google-cast-sdk'`
