### ISSUE TITLE
Chromecast.startScan(); is not working

### ISSUE THREAD

**Issue by aditya27dev** [react-native-google-cast/react-native-google-cast#52]
I am trying to scan chrome cast but it's not working...

``import Chromecast from 'react-native-google-cast';
Chromecast.startScan();``

When i run the app it doesnt scan and when i turn off mobile screen and turn on they check for devices then i am getting devices. And while doing turn off and turn on... it is firing onCastAvailabilityChange event. Why and How?

**Comment by joshyg** [comment]
I am seeing the exact same behavior ( though only on android, ios seems to work ok ).  @MrPeproni Did you ever get to the bottom of this?  Is there a workaround?

**Comment by cobarx** [comment]
I saw this behavior as well and discovered that the scan works on the Nexus 6P but not a Galaxy S8. I'm not sure what's different in the lower level code that is causing it to misbehave.

**Comment by petrbela** [comment]
Hi! We're deprecating the manual scan in favor of the automatic device discovery available in the latest version of the SDK. Please upgrade this package to the latest version (>= v3). I'd also accept a pull request if you want to fix v1 yourself.
