### ISSUE TITLE
CastButton always disabled in React Native v0.73.2

### ISSUE THREAD

**Issue by AndrRum** [react-native-google-cast/react-native-google-cast#523]
**Describe the bug**
After updating react native from version 0.69.4 to version 0.73.2, CastButton stopped displaying. After reading the documentation, I updated the code in AppDelegate.mm: 

```objc
@implementation AppDelegate

static NSString *receiverAppID = kGCKDefaultMediaReceiverApplicationID;

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  GCKDiscoveryCriteria *criteria = [[GCKDiscoveryCriteria alloc] initWithApplicationID:receiverAppID];
  GCKCastOptions* options = [[GCKCastOptions alloc] initWithDiscoveryCriteria:criteria];
  [GCKCastContext setSharedInstanceWithOptions:options];
  
  [FIRApp configure];

  self.moduleName = @"MyApp";
  self.initialProps = @{};
  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}
```

I also reconfigured the InfoPlist. 
It was like this:
```xml
        <key>NSBonjourServices</key>
	<array>
		<string>_googlecast._tcp</string>
		<string>_org.reactjs.native._googlecast._tcp</string>
	</array>
	<key>NSLocalNetworkUsageDescription</key>
	<string>Chromecast needs access to local network</string>
```

It became like this:
```xml
	<key>NSBonjourServices</key>
	<array>
		<string>_googlecast._tcp</string>
		<string>_CC1AD845._googlecast._tcp</string>
	</array>
	<key>NSLocalNetworkUsageDescription</key>
	<string>MyApp uses the local network to discover Cast-enabled devices on your WiFi network.</string>
```

However, now nothing happens when you click on the CastButton. In Android CastButton all the time disabled. 

**Expected behavior**
chromecast is working again 

**Device:**
 - Device: iPhone 13 mini, iPhone 14, Samsung Galaxy A23
 - OS: iOS 17.3.1, android 14
 - Library Version react-native: 0.73.2, react-native-google-cast: 4.8.0

**Comment by MartinGambit** [comment]
Hey, I just had the same issue lately that took me a whole day to figure out. 
I had to downgrade to -v 4.7.0 to make it work on iOS. On Android the 4.8.0 worked fine tho, you just have to add a necessary configurations into AndroidManifest.xml and initialize CastContext inside of MainActivity.java

**Comment by AndrRum** [comment]
> Hey, I just had the same issue lately that took me a whole day to figure out. I had to downgrade to -v 4.7.0 to make it work on iOS. On Android the 4.8.0 worked fine tho, you just have to add a necessary configurations into AndroidManifest.xml and initialize CastContext inside of MainActivity.java

I trust downgrade to 4.7.0, but its dont work for me.

**Comment by AndrRum** [comment]
Just put together a clean project with only three dependencies:
 "dependencies": {
    "react": "18.2.0",
    "react-native": "0.73.7",
    "react-native-google-cast": "4.7.0"
  }, 
  I'm trying build project with 4.8.0 and 4.7.0
  
  Always code:
  import React from 'react';
import {StatusBar, useColorScheme, View} from 'react-native';
import {Colors} from 'react-native/Libraries/NewAppScreen';
import {CastButton, useRemoteMediaClient} from 'react-native-google-cast';

function App(): React.JSX.Element {
  const isDarkMode = useColorScheme() === 'dark';

  const client = useRemoteMediaClient();

  if (client) {
    client.loadMedia({
      mediaInfo: {
        contentUrl:
          'https://commondatastorage.googleapis.com/gtv-videos-bucket/CastVideos/mp4/BigBuckBunny.mp4',
        contentType: 'video/mp4',
      },
    });
  }

  const backgroundStyle = {
    backgroundColor: isDarkMode ? Colors.darker : Colors.lighter,
  };

  return (
    <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
      <StatusBar
        barStyle={isDarkMode ? 'light-content' : 'dark-content'}
        backgroundColor={backgroundStyle.backgroundColor}
      />
      <CastButton style={{width: 24, height: 24, tintColor: 'black'}} />
    </View>
  );
}

export default App;

Always configs:
1. InfoPlist
    <array>
      <string>_googlecast._tcp</string>
      <string>_CC1AD845._googlecast._tcp</string>
    </array>
    <key>NSLocalNetworkUsageDescription</key>
    <string>${PRODUCT_NAME} uses the local network to discover Cast-enabled devices on your WiFi network.</string>
2. AppDelegate.mm
@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSString *receiverAppID = kGCKDefaultMediaReceiverApplicationID;
  GCKDiscoveryCriteria *criteria = [[GCKDiscoveryCriteria alloc] initWithApplicationID:receiverAppID];
  GCKCastOptions* options = [[GCKCastOptions alloc] initWithDiscoveryCriteria:criteria];
  [GCKCastContext setSharedInstanceWithOptions:options];
  self.moduleName = @"ChromecastTestRN";
  // You can add your custom initial props in the dictionary below.
  // They will be passed down to the ViewController used by React Native.
  self.initialProps = @{};

  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

It still doesn't work

**Comment by farhan-pathan-us** [comment]
"dependencies": {
    "react": "18.2.0",
    "react-native": "0.73.6",
    "react-native-google-cast": "4.8.0"
  }, 
  
For me, it's also not working on iOS.

**Comment by Vashiru** [comment]
Same issue here:

```
    "react-native": "0.73.6",
    "react-native-google-cast": "4.8.0",
```

Tried dowgrading to 4.7.0, no dice. Not been able to try it on Android 14 unfortunately. Most recent I have available is 12 and that's still working.

**Comment by farhan-pathan-us** [comment]
I am using "react-native-google-cast": "4.8.0"

"dependencies": {
"react": "18.2.0",
"react-native": "0.73.6",
"react-native-google-cast": "4.8.0"
},

**### Android issue**
I was having casting crash issues in android 14 it got fixed by adding this permissions

**Solution:-**
```
  <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
  <uses-permission android:name="android.permission.FOREGROUND_SERVICE_MEDIA_PLAYBACK" />
```
  
###  iOS issue
In iOS cast button was not working use this patch to fix on iOS
 
  **Solution:-**
  
```
diff --git a/node_modules/react-native-google-cast/react-native-google-cast.podspec b/node_modules/react-native-google-cast/react-native-google-cast.podspec
index d1948aa..39212a4 100644
--- a/node_modules/react-native-google-cast/react-native-google-cast.podspec
+++ b/node_modules/react-native-google-cast/react-native-google-cast.podspec
@@ -32,7 +32,7 @@ Pod::Spec.new do |s|
 
   s.subspec 'NoBluetoothArm' do |ss|
     ss.dependency "#{package['name']}/RNGoogleCast"
-    ss.dependency 'google-cast-sdk-dynamic-xcframework-no-bluetooth'
+    ss.dependency 'google-cast-sdk-dynamic-xcframework-no-bluetooth', '4.7.1'
   end
 
   s.subspec 'RNGoogleCast' do |ss|
```

**Comment by AndrRum** [comment]
> '4.7.1'

it's not work for me, because when im trying run pod install, return error:  CocoaPods could not find compatible versions for pod "google-cast-sdk-no-bluetooth-xcframework":
  In snapshot (Podfile.lock):
    google-cast-sdk-no-bluetooth-xcframework (= 4.8.0)

  In Podfile:
    react-native-google-cast (from `../node_modules/react-native-google-cast`) was resolved to 4.8.0, which depends on
      react-native-google-cast/NoBluetoothArm (= 4.8.0) was resolved to 4.8.0, which depends on
        google-cast-sdk-no-bluetooth-xcframework (= 4.7.1)

Specs satisfying the `google-cast-sdk-no-bluetooth-xcframework (= 4.8.0), google-cast-sdk-no-bluetooth-xcframework (= 4.7.1)` dependency were found, but they required a higher minimum deployment target.

**Comment by YoucefBen47** [comment]
@farhan-pathan-us Thank you so much. Adding these 2 permissions fixed the app crashing after casting starts on Android 14.

**Comment by YoucefBen47** [comment]
> I am using "react-native-google-cast": "4.8.0"
> 
> "dependencies": { "react": "18.2.0", "react-native": "0.73.6", "react-native-google-cast": "4.8.0" },
> ### Android issue
> 
> I was having casting crash issues in android 14 it got fixed by adding this permissions
> 
> **Solution:-**
> 
> ```
>   <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
>   <uses-permission android:name="android.permission.FOREGROUND_SERVICE_MEDIA_PLAYBACK" />
> ```
> 
> ### iOS issue
> 
> In iOS cast button was not working use this patch to fix on iOS. Patch with [ds300/patch-package](https://github.com/ds300/patch-package)
> 
> **Solution:-**
> 
> ```
> diff --git a/node_modules/react-native-google-cast/react-native-google-cast.podspec b/node_modules/react-native-google-cast/react-native-google-cast.podspec
> index d1948aa..39212a4 100644
> --- a/node_modules/react-native-google-cast/react-native-google-cast.podspec
> +++ b/node_modules/react-native-google-cast/react-native-google-cast.podspec
> @@ -32,7 +32,7 @@ Pod::Spec.new do |s|
>  
>    s.subspec 'NoBluetoothArm' do |ss|
>      ss.dependency "#{package['name']}/RNGoogleCast"
> -    ss.dependency 'google-cast-sdk-dynamic-xcframework-no-bluetooth'
> +    ss.dependency 'google-cast-sdk-dynamic-xcframework-no-bluetooth', '4.7.1'
>    end
>  
>    s.subspec 'RNGoogleCast' do |ss|
> ```

@farhan-pathan-us Thank you so much. Adding these 2 permissions fixed the app crashing after casting starts on Android 14.

**Comment by farhan-pathan-us** [comment]
> > '4.7.1'
> 
> it's not work for me, because when im trying run pod install, return error: CocoaPods could not find compatible versions for pod "google-cast-sdk-no-bluetooth-xcframework": In snapshot (Podfile.lock): google-cast-sdk-no-bluetooth-xcframework (= 4.8.0)
> 
> In Podfile: react-native-google-cast (from `../node_modules/react-native-google-cast`) was resolved to 4.8.0, which depends on react-native-google-cast/NoBluetoothArm (= 4.8.0) was resolved to 4.8.0, which depends on google-cast-sdk-no-bluetooth-xcframework (= 4.7.1)
> 
> Specs satisfying the `google-cast-sdk-no-bluetooth-xcframework (= 4.8.0), google-cast-sdk-no-bluetooth-xcframework (= 4.7.1)` dependency were found, but they required a higher minimum deployment target.

@AndrRum 
Try using 
`pod update`

**Comment by duveborg** [comment]
> > Same issue here:
> > ```
> >     "react-native": "0.73.6",
> >     "react-native-google-cast": "4.8.0",
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Tried dowgrading to 4.7.0, no dice. Not been able to try it on Android 14 unfortunately. Most recent I have available is 12 and that's still working.
> 
> @Vashiru Try this [#523 (comment)](https://github.com/react-native-google-cast/react-native-google-cast/issues/523#issuecomment-2133022796)

This patch doesnt seem to work anymore?

**Comment by YoucefBen47** [comment]
We had an issue once where the cast button was always greyed out. Try this if I remember well it helped solve the issue.
```
import GoogleCast from 'react-native-google-cast';
  const discoveryManager = GoogleCast.getDiscoveryManager();
  discoveryManager.startDiscovery();
```

**Comment by duveborg** [comment]
> We had an issue once where the cast button was always greyed out. Try this if I remember well it helped solve the issue.
> 
> ```
> import GoogleCast from 'react-native-google-cast';
>   const discoveryManager = GoogleCast.getDiscoveryManager();
>   discoveryManager.startDiscovery();
> ```

Wow. Thanks! spent 16-ish hours debugging this and this solved it :) should probably be added to the docs somewhere 😅

**Comment by petrbela** [comment]
For iOS see #510.
For Android 14, I haven't been able to reproduce but some solutions have been mentioned above. If you're still having troubles, please report a new issue with an example project setup.
