### ISSUE TITLE
Namespace Issue with Gradle 8

### ISSUE THREAD

**Issue by jsilvers1996** [react-native-google-cast/react-native-google-cast#525]
Namespace not specified error when using gradle plugin 8
Adding something like this to the build gradle should keep backwards compatibility with previous gradle versions and allow for 8 to work properly
```
    def agpVersion = com.android.Version.ANDROID_GRADLE_PLUGIN_VERSION
    // Check AGP version for backward compatibility w/react-native versions still on gradle plugin 6    
    if (agpVersion.tokenize('.')[0].toInteger() >= 7) {
        namespace = "com.reactnative.googlecast"
    }
```

**Comment by nhoffmann-fts** [comment]
Opened [pull request](https://github.com/react-native-google-cast/react-native-google-cast/pull/536) to fix this issue.
