### ISSUE TITLE
After upgrading to React Native 0.73.6 that used Kotlin in the MainActivity the app is crashing when Casting is about to start.

### ISSUE THREAD

**Issue by YoucefBen47** [react-native-google-cast/react-native-google-cast#530]
**Describe the bug**
After adding this inside MainActivity Kotlin file the app started to crash:
```
import com.google.android.gms.cast.framework.CastContext

    override fun onCreate(savedInstanceState: Bundle?) {
      super.onCreate(null)

     try {
      // lazy load Google Cast context
      CastContext.getSharedInstance(this);
    } catch (ex: Exception) {
      // cast framework not supported
    }
 
}
```

**Device:**
 - Device: Pixel 7 pro
 - OS: Android 14
 - Library Version ^4.6.2

**Comment by mezalejandro** [comment]
Hello @YoucefBen47 try removing the ; in this line:
 CastContext.getSharedInstance(this);
it should be like this
`CastContext.getSharedInstance(this)`

**Comment by YoucefBen47** [comment]
Hi @mezalejandro thank you for replying. We will test it however I should have been clearer. The app doesn't crash at build time or when started. The app works fine but when the Cast button is clicked it starts to cast then the app crashes before the cast start playing on TV. We will test with the latest version and try to capture a video recording.

**Comment by mezalejandro** [comment]
@YoucefBen47 try to test on the real device, and with Android Studio opened you should see the error

**Comment by YoucefBen47** [comment]
@mezalejandro I added the 2 permissions suggested in this comment https://github.com/react-native-google-cast/react-native-google-cast/issues/523#issuecomment-2113993291 and that fixed the app crashing after casting starts. Thank you
