### ISSUE TITLE
IOS - Cast button disabled and not showing discovered devices

### ISSUE THREAD

**Issue by noahschwagele** [react-native-google-cast/react-native-google-cast#531]
Im encountering a error with IOS as its showing the cast button but its not pressable and no Discovery popup is shown to select a device im using a custom receiver and followed the instructions from the usage and setup page.

any idea why ?

**Comment by YangJonghun** [comment]
https://issuetracker.google.com/issues/298066142
We need to downgrade iOS google cast sdk version or wait new version
