### ISSUE TITLE
Google Cast v4.8.1

### ISSUE THREAD

**Issue by noahschwagele** [react-native-google-cast/react-native-google-cast#533]
Hi @petrbela,

I noticed that Google has released SDK v4.8.1, which might address the iOS casting issues we've been experiencing. Do you have any plans to update the project to this version soon? You can find the release notes [here](https://developers.google.com/cast/docs/release-notes).

more info [here](https://developers.google.com/cast/docs/ios_sender/permissions_and_discovery#need_to_remove_guest_mode_support)

Thank you!

**Comment by petrbela** [comment]
Thanks for the heads up, I'll test the update and publish a new version this week!

**Comment by petrbela** [comment]
Btw this package doesn't pin a specific version of the Google Cast SDK so you should be able to use the latest already.

However, it seems the [bug in the SDK](https://issuetracker.google.com/issues/298066142?pli=1) that causes the issues as discussed in #510 hasn't been released yet...
