### ISSUE TITLE
Unable to disable discovery on app boot with Expo

### ISSUE THREAD

**Issue by JustJoostNL** [react-native-google-cast/react-native-google-cast#534]
**Describe the bug**
In the latest version (V4.8.1) the option `options.startDiscoveryAfterFirstTapOnCastButton` is automatically set to `false`, because of a bug in the Google Cast SDK. However, I can't seem to find an option for Expo to set this back to `true`. I don't want my app automatically asking Bluetooth permission on initial boot.

**To Reproduce**
N/A

**Expected behavior**
An option to set this back to `true` should be available for Expo users.

**Device:**
 - Device: Apple iPhone 12
 - OS: iOS 17
 - Library Version V4.8.1

**Checklist:**
 - [x] I have followed [Installation](https://react-native-google-cast.github.io/docs/getting-started/installation) and [Setup](https://react-native-google-cast.github.io/docs/getting-started/setup)
 - [x] My problem is not described in [Troubleshooting](https://react-native-google-cast.github.io/docs/getting-started/troubleshooting)
 - [x] I believe the bug is in the React Native Google Cast library, not in the Google Cast SDK. Otherwise please use the official [Google Cast Support](https://developers.google.com/cast/support) as I'm not able to help with native SDK issues.
 - [x] I have searched [existing issues](https://github.com/react-native-google-cast/react-native-google-cast/issues?q=is%3Aissue) and have not found a similar one

**Comment by petrbela** [comment]
Added in 4.8.2

**Comment by JustJoostNL** [comment]
Thanks!

**Comment by Aximem** [comment]
Setting `startDiscoveryAfterFirstTapOnCastButton` to `true` doesn't prevent bluetooth permission to pop on app launch.
@JustJoostNL How did you manage to prevent bluetooth permission to pop on initial boot ?

**Comment by JustJoostNL** [comment]
`iosStartDiscoveryAfterFirstTapOnCastButton` setting this to `true` worked for me.
