### ISSUE TITLE
Chromecast Shows White Screen When Casting Local URL

### ISSUE THREAD

**Issue by noahschwagele** [react-native-google-cast/react-native-google-cast#548]
**Description:**

When attempting to cast a local URL hosted by `@kccd/expo-http-server` to a Chromecast using `react-native-google-cast`, the Chromecast only displays a white screen. The custom receiver is set up to handle the incoming message and load the provided URL into an `iframe`. The same URL works when accessed from other devices on the same network.

**Steps to Reproduce:**
1. Host a local server using `@kccd/expo-http-server` with the following URL: `http://192.168.1.195:9666/html`.
2. Use `react-native-google-cast` to connect to a Chromecast and send a message to load the URL via a custom receiver.
3. Observe the white screen on the Chromecast.

**Expected Behavior:**
The Chromecast should load and display the content from the local URL.

**Actual Behavior:**
The Chromecast shows a white screen. The URL works correctly when accessed from other devices on the same network.

**Code Snippet:**
```javascript
import React, { useEffect } from 'react';
import { CastButton, useRemoteMediaClient, useCastChannel } from 'react-native-google-cast';

export default function ChromeCast({ target }) {
  const channel = useCastChannel('urn:x-cast:com.url.cast', message => console.log('Received message', message));
  const client = useRemoteMediaClient();

  useEffect(() => {
    const loadReceiverUrl = async () => {
      try {
        if (client && channel) {
          await channel.sendMessage(`{"type":"iframe","url":"http://192.168.1.195:9666/html"}`);
          console.log('Sent message', `"url":"http://192.168.1.195:9666/html"`);
        }
      } catch (error) {
        console.error('Error loading custom receiver URL:', error);
      }
    };

    loadReceiverUrl();
  }, [client, channel]);

  return <CastButton style={{ width: 24, height: 24, tintColor: 'blue' }} />;
}
```

**Additional Context:**
- The URL is accessible via other devices on the network.
- No visible errors on the Chromecast, but the white screen persists.

**Environment:**
- `react-native-google-cast`
- `@kccd/expo-http-server`

**Comment by petrbela** [comment]
This is an issue with the custom cast receiver page, not this library. I'm not able to help with this. Please, use other channels to seek help.
There's https://developers.google.com/cast/docs/debugging/remote_debugger to debug what's happening on the custom page. If I had to guess, Chromecast doesn't support iframes.
