### ISSUE TITLE
Is it possible to use custom receivers with this plugin?

### ISSUE THREAD

**Issue by goinnovative** [react-native-google-cast/react-native-google-cast#56]
Hey,

I want to stream a website to the Chromecast and I found a custom receiver which shows websites in an iframe.

https://github.com/DeMille/url-cast-receiver

Is it possible to use trigger a custom receiver with this plugin?

**Comment by secretyouth** [comment]
+1

Interested, casting views is extremely useful for me. Something I want to know more about. Can anyone chime in?

**Comment by petrbela** [comment]
Yes, please see the latest version.

**Comment by singerbj** [comment]
@petrbela how though? Is there an example that can be provided?
