### ISSUE TITLE
Error running on XCode evaluating undefined GoogleCast.DEVICE_AVAILABLE

### ISSUE THREAD

**Issue by thesubway** [react-native-google-cast/react-native-google-cast#57]
![img_1302](https://user-images.githubusercontent.com/5408549/35706098-5d186026-0759-11e8-830b-6b9a6ab07a84.PNG)
So far I have only tested on iOS.

In order to get here, I did:
Started new project
$ npm install react-native-google-cast --save
$ react-native link react-native-google-cast
I created a Podfile, and added:
pod 'google-cast-sdk', '2.10.4.1'
then did pod install and npm install.

Here is my repo (pods/ directory is in my gitignore, so you would have to re-run pod install):
https://github.com/thesubway/GoogleCastRN

**Comment by Raghavendra7** [comment]
I am facing the same issue.

**Comment by mtkopone** [comment]
Try opening the project in xcode, i'm guessing that compiling in xcode will fail with:
https://github.com/charliesbox/react-native-google-cast/issues/51
https://github.com/charliesbox/react-native-google-cast/issues/21

If so, solve like this: https://github.com/charliesbox/react-native-google-cast/issues/21#issuecomment-372065414

**Comment by petrbela** [comment]
Please upgrade to the latest version.
