### ISSUE TITLE
How can I control the volume?

### ISSUE THREAD

**Issue by chaocharleswang** [react-native-google-cast/react-native-google-cast#59]
How can I control the volume? Thanks.

**Comment by petrbela** [comment]
Awesome, I'll add it to the docs.

I'll still leave this issue open for programmatic control of volume.

**Comment by gazedash** [comment]
I have a problem with audio too. Whenever I use this library, even if I am not connected to any device, when I click on volume buttons on my phone, cast volume changes, but no the media/call volume. Help please

**Comment by petrbela** [comment]
@gazedash iOS or Android? Which version of the library?

**Comment by gazedash** [comment]
@petrbela Android , latest version

**Comment by jonathanm-tkf** [comment]
Please I have same problem...

**Comment by celestial-rose** [comment]
any idea on how to do it with expo ? with the config plugin maybe ?
