### ISSUE TITLE
Not detecting any devices

### ISSUE THREAD

**Issue by fbn4sc** [react-native-google-cast/react-native-google-cast#61]
I have the following on a component:
```

public componentDidMount() {
    Chromecast.startScan();

    DeviceEventEmitter.addListener(Chromecast.DEVICE_AVAILABLE, existance =>
      this.setState({ available: existance.device_available })
    );

    setInterval(() => {
      Chromecast.getDevices().then(d => console.log(d));
    }, 2000);
  }
```
But all I get is an empty array, even though other apps on the same device are able to find my Chromecast.

At first I was getting this error:

```
node_modules/react-native-google-cast/android/src/main/java/com/googlecast/GoogleCastPackage.java:29: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error
:react-native-google-cast:compileReleaseJavaWithJavac FAILED
```
And, following a suggestion on a different issue, I commented out the offending method I was able to build the app.

Maybe this caused the problem?

How can I get the component to list the available devices?

**Comment by fabiancarlos** [comment]
remove @Override , or fork this project, remove the @Override, and install by your package from github.

**Comment by msebgf** [comment]
I have the same issue, no devices are being detected

**Comment by petrbela** [comment]
Please upgrade to the latest version, it handles connection automatically.

**Comment by sarahussie** [comment]
@petrbela I used the last version but i had the same issue no device avilable and the cast button didnt apperar

**Comment by petrbela** [comment]
Can you go through the troubleshooting list and see if anything helps? https://react-native-google-cast.github.io/docs/getting-started/troubleshooting
