### ISSUE TITLE
App crashes on reload when developing ([GCKDeviceScanner stopScan] must be called on main thread)

### ISSUE THREAD

**Issue by aecorredor** [react-native-google-cast/react-native-google-cast#62]
Ever since I added this package my app crashes when I am developing (and testing on simulator) when I try to reload to see new changes.

This is the error I get:
*** Assertion failure in -[GCKDeviceScanner stopScan], /Volumes/BuildData/pulse-data/agents/601160/recipes/947848375/base/google3/googlemac/iPhone/Chromecast/SDK/Framework/Classes/GCKDeviceScanner.m:466
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '-[GCKDeviceScanner stopScan] must be called on main thread'

I also get this message which I think might be what is causing the problem:

Module GoogleCast requires main queue setup since it overrides `constantsToExport` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.

**Comment by TheSavior** [comment]
@aecorredor did you ever solve your issue? I'm looking at this PR to react-native-udp which is essentially trying to solve the same problem: https://github.com/tradle/react-native-udp/pull/16

**Comment by petrbela** [comment]
Please upgrade to the latest version, it handles discovery automatically.
