### ISSUE TITLE
How to integrate this library without using Cocoapods?

### ISSUE THREAD

**Issue by jonnyn** [react-native-google-cast/react-native-google-cast#63]
I'm trying to integrate this library but not using Cocoapods, but not working so far

Things I tried:
npm install react-native-google-cast --save
react-native link react-native-google-cast

then following this to download SDK, and added the framework to xcode manually
https://developers.google.com/cast/docs/ios_sender_setup

but couldn't make xcode to build
got error: 'GoogleCast/GoogleCast.h' file not found

**Comment by tnaughts** [comment]
Check out this issue [Header not found](https://github.com/react-native-google-cast/react-native-google-cast/issues/51)

**Comment by petrbela** [comment]
Added instructions to readme
