### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by Angelk90** [react-native-google-cast/react-native-google-cast#69]
Hi @vmseba , @DracoBlue , @petrbela : 
![image](https://user-images.githubusercontent.com/20476002/50767699-180a0580-127e-11e9-8a11-d30d31ab46f1.png)

I installed the module but I'm facing some problems, as you can see from the image above.

How can I solve the problem?

```
ext {
        buildToolsVersion = "28.0.0"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }
```

P.Š.
In the new version according to the new specifications you should replace compile with implementation.

**Comment by petrbela** [comment]
Please upgrade to the latest version, it should fix this.
