### ISSUE TITLE
Media Progress Listener

### ISSUE THREAD

**Issue by lukebaker** [react-native-google-cast/react-native-google-cast#72]
@petrbela, it looks like the media progress listener was not migrated from the flextv repo in the most recent changes. Any chance of getting that ported to this repo? https://github.com/flextv/react-native-google-cast/pull/34

**Comment by petrbela** [comment]
Seriously I had ONE job 🤦🏻‍♂️

Thanks for pointing it out, I'm adding it back.

**Comment by petrbela** [comment]
Added in 3.0.4 via https://github.com/react-native-google-cast/react-native-google-cast/commit/90a35d11ef4a3c8f1acaa00199fb9f5381ee0c01
