### ISSUE TITLE
tintcolor doesn't work? button is always blue

### ISSUE THREAD

**Issue by MarianBe** [react-native-google-cast/react-native-google-cast#75]
setting the tint color doesn't do anything for me, the button is always in this blue color? How can i change that?

**Comment by petrbela** [comment]
I'm assuming this is on iOS? It's a known issue that the tint color is not always applied and instead defaults to blue. I'll look into why it's happening.

**Comment by padampadam** [comment]
Yeah sorry forgot top include that, its on iOS yes

**Comment by jedashford** [comment]
Has anyone tried to fork and set the default style to white? Wonder if this is on the react side or the native side? We're also having this issue. Maybe just set the default to white anyway (is white on youtube, google play movies, netflix, etc)

**Comment by padampadam** [comment]
@jedashford i manually Changes it with No success

**Comment by jedashford** [comment]
Ok I understand more about how this works and how RCT_EXPORT_VIEW_PROPERTY is used. Are you able to reliably recreate it? If so, what steps? 

Mine seems to be random, but haven't played with it enough. The code seems solid, so it may be something like the cast library re-initializing itself and not applying the tintColor property from the bridge.

**Comment by padampadam** [comment]
actually i am not able to reliably recreate this, it seems very random to me?
@jedashford the library reinitializing sounds about right to me, i will try to find a way to recreate this so we can pin it to something specific

**Comment by gazedash** [comment]
How to style the button? What if I need to style the button for different states (e.g. connected, available etc)?

**Comment by petrbela** [comment]
@gazedash The framework displays the different states automatically. The native SDK allows custom icons but that is not supported by this library yet. Only the tint for now.

**Comment by petrbela** [comment]
On iOS, the support is spotty or sometimes doesn't work at all (that's what this issue is about). Haven't figured out yet what the proper solution should be.

Changing the icon itself is very unlikely to happen until v4 due to priorities, although technically there's nothing stopping it from working in the current version so you're free to implement it yourself and add a PR.

**Comment by crwecker** [comment]
Upgraded to 3.1.2, but the chrome icon is still blue most of the time instead of the tintColor that I am setting :/

**Comment by petrbela** [comment]
@crwecker Can you provide some code sample? I can't reproduce it on the example project anymore.

**Comment by crwecker** [comment]
Hmm. Not easily. Here are the basic components I'm using (Sorry if this isn't actually helpful):
```import GoogleCast, { CastButton } from 'react-native-google-cast'

export const Casting = () => {
  return (
    <CastButton style={{ width: 60, height: 60, tintColor: 'white', marginRight: -15 }} />
  )
}

const registerListeners = () => {
  GoogleCast.EventEmitter.addListener(GoogleCast.SESSION_STARTED, sessionStarted)
  GoogleCast.EventEmitter.addListener(GoogleCast.SESSION_ENDED, sessionEnded)
  GoogleCast.EventEmitter.addListener(GoogleCast.MEDIA_PLAYBACK_STARTED, MediaPlaybackStarted)
  GoogleCast.EventEmitter.addListener(GoogleCast.MEDIA_PLAYBACK_ENDED, MediaPlaybackEnded)
}

const unregisterListeners = () => {
  GoogleCast.EventEmitter.removeListener(GoogleCast.SESSION_STARTED, sessionStarted)
  GoogleCast.EventEmitter.removeListener(GoogleCast.SESSION_ENDED, sessionEnded)
  GoogleCast.EventEmitter.removeListener(GoogleCast.MEDIA_PLAYBACK_STARTED, MediaPlaybackStarted)
  GoogleCast.EventEmitter.removeListener(GoogleCast.MEDIA_PLAYBACK_ENDED, MediaPlaybackEnded)
}

componentDidMount () {
  GoogleCast.getCastState().then((status) => {
    ...
  })
}
```

**Comment by petrbela** [comment]
Hmm well this isn't much helpful haha. Does it happen in a production app, or in development when (hot) reloading?

**Comment by jonnynfb** [comment]
To get it working on iOS and Android I have to do this:
`<CastButton style={styles.castButton} tintColor={Colors.black} />`
but iOS is still not working half of the time. Then I have to hardcode it in RNGoogleCastButtonManager.m
`
- (UIView *)view {
  GCKUICastButton *castButton = [[GCKUICastButton alloc] init];
  castButton.tintColor = [UIColor blackColor];
  return castButton;
}
`
It's now always black on both platforms. Of course, you can change to different color of choice.

**Comment by petrbela** [comment]
@jonnynfb Are you on the latest version? Could you test if the example project works correctly? I haven't been able to reproduce the problem since https://github.com/react-native-google-cast/react-native-google-cast/commit/954e47db3899ce66560a9825ef0e453b3055420a

**Comment by jonnynfb** [comment]
Ah... I'm on my own repo but I see the fix. OS it probably has been fixed on main repo.
