### ISSUE TITLE
Expanded Media Controller on Android missing Cast Button

### ISSUE THREAD

**Issue by MarianBe** [react-native-google-cast/react-native-google-cast#77]
On iOS the Expanded Media Controller has a cast button which lets you cancel the casting
![image](https://user-images.githubusercontent.com/773986/51675016-bca47b00-1fd2-11e9-978d-72dd156505e9.png)
on android the button is missing.
I found some code commented out in [GoogleCastExpandedControlsActivity.java](https://github.com/react-native-google-cast/react-native-google-cast/blob/master/android/src/main/java/com/reactnative/googlecast/GoogleCastExpandedControlsActivity.java) but reenabling it resulted in crashes for me as i am not very fluent with native android.
Any hints?

**Comment by petrbela** [comment]
Hi! Unfortunately, I haven't had much time to explore the expanded media controller yet. If anyone else has a fix I'd be glad to accept it.

**Comment by MarianBe** [comment]
@petrbela i think i found a solution, creating a PR asap. let me know if this works for you.

**Comment by MarianBe** [comment]
#78

**Comment by RoiDayan1** [comment]
add this to `styles.xml` file

    <style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
        
        .......
        <item name="mediaRouteButtonTint">#EEFF41</item>.  <-- add this line
    </style>
