### ISSUE TITLE
[iOS 12] no devices found with SDK 3

### ISSUE THREAD

**Issue by nbennink** [react-native-google-cast/react-native-google-cast#79]
With the current version (3.0.5) I have an issue where I don't see the Chromecast button on iOS (12). I can see the button on other apps like Youtube or Twitch but not in my app.

In the readme there is a note about a work in progress version for V4 but that branch doesn't exist. Is this still in the works? It's a little bit better when I update to `google-cast-sdk 4.1` (pod). With that version I can stream using Bluetooth but over network is not working.

**Comment by petrbela** [comment]
V4 is in the works, however, it's a bit more massive undertaking than I'd originally thought. I'll see if I can get out a preview sometime during next week.

You should still be able to use the current library with `google-cast-sdk '4.3.0'` (there's a [duplicate symbol issue](https://issuetracker.google.com/issues/113069508) in the most recent versions); I don't think there are any breaking changes other than the default `kGCKDefaultMediaReceiverApplicationID` which you can change manually.

**Comment by nbennink** [comment]
The problem was apparently quite easy to fix. You have to enable "Access WiFi Information" in your project to scan over the network. This is added in xcode 10 when targeting iOS 12. I have added a small note to the docs because it's disabled by default (#82)

SDK 4.3 works fine with the master branch so I keep using that now. `initWithReceiverApplicationID` is deprecated as well. So I think you should initialise Google Cast like this now:
```
GCKDiscoveryCriteria *criteria = [[GCKDiscoveryCriteria alloc] initWithApplicationID:kGCKDefaultMediaReceiverApplicationID];
GCKCastOptions* options = [[GCKCastOptions alloc] initWithDiscoveryCriteria:criteria];
[GCKCastContext setSharedInstanceWithOptions:options];
```

**Comment by petrbela** [comment]
Updated instructions in readme.

**Comment by nenjamin2405** [comment]
Hi @nbennink @petrbela, I'm having the issue like this https://github.com/react-native-google-cast/react-native-google-cast/issues/114 when using google-cast-sdk '4.3.0' together with "react-native-google-cast": "^3.1.3". Any idea how to resolve this? When the popup `Connect to nearby device` appears, I cannot even touch any option of it
