### ISSUE TITLE
How can i catch 'GoogleCast.castMedia' function error?

### ISSUE THREAD

**Issue by owenjeon** [react-native-google-cast/react-native-google-cast#80]
When media request is fail, i can't catch error.

my suggestion.

1. add event listener
```
GoogleCast.EventEmitter.addListener(GoogleCast.MEDIA_START_FAIL, (error) => {
  /* callback */
})
```

2. `GoogleCast.castMedia` function return Promise error to catch it.
```
GoogleCast.castMedia().catch(e => ...)
```

**Comment by petrbela** [comment]
Hi! This (using a promise) will be added in v4, probably available sometime next week.
