### ISSUE TITLE
Control playback of other content

### ISSUE THREAD

**Issue by robertherber** [react-native-google-cast/react-native-google-cast#81]
Is there any possibility to use this to connect to already playing media - and control playback and get metadata about it? If not - is it on the roadmap?

**Comment by petrbela** [comment]
Hi! This is possible and on the roadmap, and should be available from the early v4 (next week hopefully?).

**Comment by robertherber** [comment]
That's great news, thanks!

**Comment by robertherber** [comment]
@petrbela Is this available now?

**Comment by petrbela** [comment]
Yes it's been available for a while. Check out the latest version.
