### ISSUE TITLE
initChannel() and SendMessage they are not in the project

### ISSUE THREAD

**Issue by danielgssp** [react-native-google-cast/react-native-google-cast#83]
Hi, I have a problem with methods GoogleCast.initChannel()  and GoogleCast.sendMessage() 

Undefined is not a function (evaluating 'GoogleCast.sendMessage(message, namespace )') 
sendMessage
D:\Workspace\ChromecastReactNative\node-modules\react-native-google-cast\index.js: 83:34

I opened Google Cast Module and I did not really find the methods responsible for initializing the channel and sending messages.

**Comment by petrbela** [comment]
Hi! I'm assuming this is on Android? I just recently noticed these methods weren't added to the Android project. You're welcome to open a pull request or wait for v4 which should be coming out in a week or so.

**Comment by danielgssp** [comment]
Ok, I would love to collaborate ><
