### ISSUE TITLE
No media selected

### ISSUE THREAD

**Issue by gazedash** [react-native-google-cast/react-native-google-cast#86]
I'm running the example app, but when I click on the video nothing happens, although Google Cast is connected successfully and if I click on cast icon, it says "No media selected". 

It happens on both platforms, and I stream content from network (url), as in example.
Although I can successfully cast content from other apps that support google cast.
What is the possible problem?

**Comment by petrbela** [comment]
Not sure why that might be happening. I'm preparing a new set of examples as part of v4 so hopefully, they will help resolve it!

**Comment by gazedash** [comment]
It seemed to be a problem with Chromecast apparently, now it works after restarting it completely

**Comment by petrbela** [comment]
Okay glad it got figured out. v4 will have much better logging for catching and understanding such errors.
