### ISSUE TITLE
How to use getSharedInstance() 

### ISSUE THREAD

**Issue by danielgssp** [react-native-google-cast/react-native-google-cast#87]
I have a problem with extends GoogleCastActivity, 
my app alredy extends react-native-navigation, I followed the exemple using CastContext.getSharedInstance(this) in onCreate() but dons't work .. 

I had that to create onCreate() because usually there is not (ReactNative).

I would like  an example  how use getSharedInsance();

**Comment by danielgssp** [comment]
hi, sorry for I ask around here but Could you look at my pull requests ? ty..

**Comment by harrydema** [comment]
Do we have an example with the integration of react navigation?

**Comment by Nitesh-Kanyal** [comment]
Hi any updates on how to use with react-native-navigation?
