### ISSUE TITLE
GoogleCast.initChannel is not a function

### ISSUE THREAD

**Issue by ronit-kadwane** [react-native-google-cast/react-native-google-cast#88]
Hello,
I want to receive messages from receiver application for that I need to initialize channel, but While I am initializing channel using GoogleCast.initChannel() API, it is showing error message GoogleCast.initChannel is not a function.
How can I init the channel and get a message from the receiver app?

**Comment by petrbela** [comment]
Hi! This method isn't implemented yet in Android but it's being worked on and will be added in a bit. On iOS, this should already be working.

**Comment by ronit-kadwane** [comment]
ok.
Thank you @petrbela

**Comment by ronit-kadwane** [comment]
Hello @petrbela ,
I have implemented missing two methods for android `GoogleCast.intChannel()` and `GoogleCast.sendMessage()`.

Please check and review the [pull request.](https://github.com/react-native-google-cast/react-native-google-cast/pull/90)

**Comment by ronit-kadwane** [comment]
As I have implemented [missing methods](https://github.com/react-native-google-cast/react-native-google-cast/pull/90) so closing the issue.
