### ISSUE TITLE
Connecting to different device

### ISSUE THREAD

**Issue by TheSavior** [react-native-google-cast/react-native-google-cast#92]
I have multiple chromecast devices on my network and I'd like to be able to select and bring up the controls for a specific device. I don't see anything in the public API for getting a list of devices or picking which one to connect to. Is this currently supported?

**Comment by petrbela** [comment]
When you press the Cast button, the library presents a dialog that allows you to select which device to cast to. (Previously, in SDK v2, this had to be handled manually.) I'm not sure off the top of my head if the SDK also enables you to connect to a specific device programmatically; if it does, we might add support to the RN wrapper in the future in v4. Is having a programmatic access a priority for you?

**Comment by TheSavior** [comment]
Ah, got it. I can give the cast button a try. I’m not using this to actually cast content, I’m purely building an app that acts as a remote for my chromecast so I want to be able to connect to and pause / change volume of the currently playing media. Essentially what you get when you open the Google Home app in the devices tab.

The cast button might let me do this so I’ll check it out.
