### ISSUE TITLE
Can't stream hls content

### ISSUE THREAD

**Issue by gazedash** [react-native-google-cast/react-native-google-cast#93]
Reproducible on both platforms.

react-native-google-cast version: 3.0.5

I send 

```"contentType": "application/x-mpegURL",``` among other keys, but it doesn't work.

Other types of content works, e.g. DASH, mp3 etc

**Comment by petrbela** [comment]
Hi @gazedash, that's weird, we have no problem with HLS. Just to be sure, are you using a custom receiver?

**Comment by gazedash** [comment]
@petrbela No, I am not using custom receiver. Could you send me example HLS m3u8 file so I test it and see if it works?

**Comment by petrbela** [comment]
Hmm, so it does look like it works with the default receiver, too. Here's a sample stream https://mnmedias.api.telequebec.tv/m3u8/29880.m3u8

**Comment by thanhdanh1089** [comment]
Hi @petrbela ,
I am trying to cast video hls version > 3.2 and it not work on chromecast gen 1. I am not sure the reason. But could you help me check my file is work on chromecast gen 1?
"https://cdn-trinity-christian-centre-01.akamaized.net/Content/HLS/Live/channel(play1)/index.m3u8"

Thank in advance

**Comment by luis-f-lins** [comment]
@petrbela @thanhdanh1089 I am also trying to stream M3U8 files with no success... Any updates on this?

**Comment by thanhdanh1089** [comment]
@luis-f-lins u
I see with hls file version > 3.2 it's not work. if hls file <=3.2 it's work well. I think the problem is player of chromecast but i'm not sure.

**Comment by petrbela** [comment]
Let's continue the discussion in #58.

**Comment by nriccar** [comment]
@thanhdanh1089 I see that https://cdn-trinity-christian-centre-01.akamaized.net/Content/HLS/Live/channel(play1)/index.m3u8 works. Did you enable CORS? Or how did you manage to fix it?
