### ISSUE TITLE
error: package com.reactlibrary does not exist

### ISSUE THREAD

**Issue by LaiBai** [react-native-google-cast/react-native-google-cast#98]
I had just update to 3.1.0 as I wanted to try the message channel feature of Android (it should be newly added to this version). However, I faced two problems when I try to follow the new installation steps:

1. I think step 1 of Android installation steps should be MainApplication.java but not MainActivity.java, so I just do the sub-steps in MainApplication.java

2. I got the following error when I build the app.
`error: package com.reactlibrary does not exist`
`error: cannot find symbol new RNGoogleCastPackage(),`

Then I skipped step 1 and followed the other steps. The app could be build and connected to google cast device as expected, but the message channel feature of Android still couldn't be used...

**Comment by danielgssp** [comment]
bud, use import com.reactnative.googlecast.GoogleCastPackage;
and put new GoogleCastPackage() on getPackages()

**Comment by chloeching-amino** [comment]
@danielgssp I tried to use them. Then, the app can be built, and media can be casted, but still cannot connect the message channel of Android sender to the receiver (GoogleCast.CHANNEL_CONNECTED event didn't be triggered).

I had used the same code in iOS, and all things worked perfectly. The channel can be connected, message can be send to the receiver from iOS, and vice versa.

**Comment by danielgssp** [comment]
So this happens because `initChannel()` does not exist yet on android !
the last PR was been accepted that contains this functionality for Android, Please wait a while before updating.

**Comment by petrbela** [comment]
Ah looks like I resolved the merge conflict incorrectly. Sorry about that. Publishing a new version in a bit.

**Comment by danielgssp** [comment]
Ow. I tryed use `sendMessage()` and nothings happens, he is not triggered when invoked !

**Comment by petrbela** [comment]
Should be fixed in 3.1.1

**Comment by lukepighetti** [comment]
I can't get 

`import com.reactnative.googlecast.GoogleCastPackage;`
or 

`import com.facebook.react.GoogleCastActivity;`

to work.

Does it matter if I'm using build flavors? Is there any step I have to run in Android Studio to bring these in?

**Comment by petrbela** [comment]
@lukepighetti I've noticed sometimes Gradle sync doesn't run automatically when I open a project with a new auto-linked react native library but you can run in manually (I believe it's Project > Sync with Gradle or something like that).

**Comment by lukepighetti** [comment]
Wish I could remember how I resolved it, but I did get it resolved and I believe it was a gradle setting.
